### ISSUE TITLE
Storage drawers doubled output

### ISSUE THREAD

**Issue by rockett1** [Divine-Journey-2/Divine-Journey-2#1000]
### Modpack version

2.19.3

### Description

When you left click or right click on a storage drawer (Oak basic drawer are the ones im using) if you hold down your mouse click, you will get double the output, so instead of 1 block you get 2, or instead of 1 stack you get 2 stacks of the block. This will only happen if you inventory is creating a fresh stack of an item, if you inventory does not have a full stack, you will get the normal intended 1 item.

### Steps to reproduce

Have an oak storage drawer placed down in the world with several stacks of an item eg: redstone inside

(before doing the next step, ensure you inventory does not contain any impartial stacks of the item in the drawer, or the bug will not work. The bug will work if the stack of item is full in your inventory or there is no item in your inventory)

left click the drawer (or right click) but hold down your click

get 2 items out

### Expected behavior

Only one item to be output

### Additional context

I thought I was getting the famous double mouse click issue, I kept randomly getting 2 outputs instead of 1 when using these things but after a bit of testing it appears the drawers are bugged.

### Your Divine Journey 2 Discord Username

Rockett#7433

**Comment by Preta-Crowz** [comment]
This is known mod issue
When user get item to selected slot, it will get refreshed and drawer works more time

**Comment by rockett1** [comment]
RIP

https://github.com/jaquadro/StorageDrawers/issues/507
