### ISSUE TITLE
My game crashes when i open a specific world

### ISSUE THREAD

**Issue by TheVorplex** [Divine-Journey-2/Divine-Journey-2#1005]
### Modpack version

1.5.7

### Java version

1.8.0_51

### RAM Allocated

I dedicated 4gb and my computer has 32 gbs of ram

### Description

once i opened my world

### When did the crash happen?

When entering the world

### Steps to reproduce

open the world

### Minecraft crash report

[crash-2023-06-02_16.45.30-server.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/11634929/crash-2023-06-02_16.45.30-server.txt)

### Your Divine Journey 2 Discord Username

_Vorplex # 0423_

**Comment by WaitingIdly** [comment]
this repo is for Divine Journey 2 - you are playing Divine Journey 1.
the error appears to be related to HardCoreQuesting, the data for it has probably been corrupted for that world, and you will need to delete it.
