### ISSUE TITLE
Typos in demonic code

### ISSUE THREAD

**Issue by winco0811** [Divine-Journey-2/Divine-Journey-2#1008]
### Modpack version

2.19.3

### Where is the typo located?

Ch18:

`Quest #9`: "It describes an ancient belief":
-  "... do not dist - urb ᚣᛗᚦ ᚣᛊ!" should be "... do not dist - ᚣᛗᚦ ᚣᛊ!" (urb is repeated)
- "... as we conti - ᚣᚼ..." should be "... as we conti - ᛣᚣᚼ.." or  "... as we contin - ᚣᚼ.." (n is missing)

`Quest #43`: "The tablet awakens...!":
- "ᚣᛣᚸᚼᛊᛊ ᚠᛞᚣᛗ ᛊᚣᛋᛋᚣᚭᚦ!" should be "ᚣᛣᚸᚼᛊᛊ ᚠᛞᚣ ᛊᚣᛋᛋᚣᚭᚦ!" (you instead of your)

Ch30:
`Quest #793`:
- "ᚠᛞᚣ ᛣᚼᛥᚨ ᚨᛤᛊᛇ ..." should be "ᚠᛞᚣᛗ ᛣᚼᛥᚨ ᚨᛤᛊᛇ ..." (your instead of you)

### Exact fix

See above.

### Your Divine Journey 2 Discord Username

winco

**Comment by winco0811** [comment]
Issues linked are just github being wierd about quest numbers...

**Comment by King65868** [comment]
Is the chapter 30 quest supposed to be opposite what you said? I already see " ᚠᛞᚣᛗ ᛣᚼᛥᚨ ᚨᛤᛊᛇ ... "

**Comment by winco0811** [comment]
Maybe it was fixed already on github but wasn't released? It definitely should be ᚠᛞᚣᛗ (your), not ᚠᛞᚣ (you)

**Comment by King65868** [comment]
Ah it was fixed by #985

**Comment by WaitingIdly** [comment]
as stated by King, this was resolved in #985

**Comment by King65868** [comment]
This is only partially fixed by #985

**Comment by WaitingIdly** [comment]
oh yeah whoops misread that, thanks
