### ISSUE TITLE
Thermoelectric boiler rendering error

### ISSUE THREAD

**Issue by n1ret** [Divine-Journey-2/Divine-Journey-2#1011]
### Modpack version

2.19.3

### Java version

1.8.0_371-b11

### RAM Allocated

8 GBs

### Description

Mekanism thermoelectiric boiler rendering fatal error.

### When did the crash happen?

For a while everything was ok. Then I moved the bowl of water closer to the boiler and left the base. When returning and loading the base, a crash occurred. Now game crushes on entering the world.

### Steps to reproduce

1. Render my base (thermoelectric boiler)

### Minecraft crash report

[crash-2023-07-04_17.26.11-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/11949726/crash-2023-07-04_17.26.11-client.txt)

### Your Divine Journey 2 Discord Username

n1ret

**Comment by Preta-Crowz** [comment]
Make sure this can be reproduced without optifine. Otherwise, this can be issue with optifine and will not fixed.

**Comment by n1ret** [comment]
I already tried uninstalling optifine.

**Comment by Preta-Crowz** [comment]
> I already tried uninstalling optifine.

Then please upload crash report without optifine.

**Comment by n1ret** [comment]
[crash-2023-07-07_14.59.26-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/11980528/crash-2023-07-07_14.59.26-client.txt)

**Comment by n1ret** [comment]
> Then please upload crash report without optifine.
any ideas?
