### ISSUE TITLE
Items in inventory don't update until character die

### ISSUE THREAD

**Issue by DarkStas** [Divine-Journey-2/Divine-Journey-2#1018]
### Modpack version

2.19.3

### Description

Time to time Items in inventory don't update until character die

### Steps to reproduce

Time to time Items in inventory don't update until character die

### Expected behavior

Items in inventory update all time I pick them up.

**Comment by DarkStas** [comment]
Re checked it. It start to happen after pressing K key.

**Comment by DarkStas** [comment]
After changing key of "Open Spell Library" from K key, problem stop occurs so its because of this library. (Yes, pressed new key of  "Open Spell Library" and same problem occurs).

**Comment by DarkStas** [comment]
Ah, and there no quest on K key. I need to press for 3 sec key that higher TAB to go to quests.

**Comment by DarkStas** [comment]
And don't know bug it or not, time to time I have 5x5 blocks destroyed (with cobbelstone instruments), but cant control it. 
How I get it, it must be "Ore Excavation" mod, but it keys don't 'on' function when I press them. I even rebind keys to unique, but it not helped.

**Comment by DarkStas** [comment]
Get it, I need to press "Ore Excavation" key when work with instrument, then it harvest 5x5 blocks and destroy 60 durability item. But must it be like that? How I think it must be 1 block = 1 durability...

**Comment by DarkStas** [comment]
In quest about Arc Furnace need to be added words about "Graphite Electrode" and that it need it for functioning.

**Comment by DarkStas** [comment]
It would be nice to easy of crafting of fluid tank for 80k to get it on immersive level.
Also it would be nice to have more ways to get "Coal Coke".

**Comment by DarkStas** [comment]
Ah, and quests in 2nd tier (Totemic) about finding animals is so awful, please think about ways to give players items like cage to craft for easy ways for transporting animals.

**Comment by DarkStas** [comment]
Tier 6 (AE2) in Meteorite Compass quest needed description what Atum is... Or link or sub quest before Meteorite Compass quest...

**Comment by Preta-Crowz** [comment]
1. main issue is already known and will hard to fix.
 it called "inventory desync" and most common thing is "press spell library while not holding roots wand"

2. don't put random & many issues on one issue. they aren't have any connections.

**Comment by Preta-Crowz** [comment]
https://github.com/Divine-Journey-2/Divine-Journey-2/issues/994#issuecomment-1551701490

**Comment by Atricos** [comment]
Please open a separate issue for each of the issues listed here, don't just dump comments on once issue.

Inventory desync can commonly occur if you press the Roots "Open Spell Library" key without a Staff in hand. You can fix it by relogging.
