### ISSUE TITLE
Please add something like Chunk-Pregenerator

### ISSUE THREAD

**Issue by DarkStas** [Divine-Journey-2/Divine-Journey-2#1020]
### Mod Name

Chunk-Pregenerator

### Reasons why this should be added

To Pre-generate chunks, mostly ask to add it for servers that give rights only to install modpack, and don't create or change it myself.

**Comment by Atricos** [comment]
This is not gonna be used by players who don't own servers (which, let's be honest, is the majority of players), and it's only going to add additional load time when starting up the modpack. If a server owner needs this mod, they can add it, pregenerate chunks, then remove the mod and open the server to the public.

**Comment by DarkStas** [comment]
Chunk-Pregenerator needed for solo servers too, by pre generate chunk its much better to fly on glider (with perf mods that I wrote it even better). 
As of now I pregen 100 chunks, have perf mods and could fly without load lags on glider with render distance of 16... 
Without perf mods but with pregen I could some-how, with timed lags, load chunk issues fly with render distance 7-10. 
Without perf mods and pregen I have 100% preload chunk lag and cant fly on glider at all...

**Comment by DarkStas** [comment]
But surely, perf mods better then Chunk-Pregenerator.

**Comment by Atricos** [comment]
As I have commented, feel free to add Chunk-Pregenerator to the pack, use it, and once the server opens, remove it. You can add it back later when you want to pregenerate even more chunks.
