### ISSUE TITLE
Complete Blue Screen Crash

### ISSUE THREAD

**Issue by Ezdrunich** [Divine-Journey-2/Divine-Journey-2#1023]
### Modpack version

2.19.2

### Java version

1.8.0_51

### RAM Allocated

8GB with 16GB space (does not max my memory or CPU/GPU)

### Description

As I was putting items away from an adventure into the nether (betternether/DivineRPG items) I was completely fine, maybe a few frame stutter from leaving inventory to inventory.  Once I was beginning to put away vanilla ores into the small crates my frames stopped and completely blue screen crashed.  Once I rebooted everything and got back into the game the entirety of my achievements were lost.  I had to completely restart on my achievements.  This isn't too much of a setback as you now have this stuff and the means to semi-automate things necessary, but it is still a pain to have to go through a lot of the tedious achievements that are in some of the farther chapters of the mod.

### When did the crash happen?

When entering an inventory to put vanilla ores away as soon as I shift clicked to quick stack the items.

### Steps to reproduce

Do not necessarily know how to reproduce.
1. Opened game through curseforge, started the modpack, got into world.
2. Went on a nether trip for ores and resources only found in the nether (I did quit the game after I left the nether then came back later).
3. Travelled for a long distance (13,000m) back to my base.
4. Began filtering through my inventories and putting resources and ores away.
5. Entered a small crate inventory and shift-clicked a stack of 7 iron specifically then complete blue screen crash during game.
6. Rebooted everything and find my achievements completely reset.

### Minecraft crash report

[latest.log](https://github.com/Divine-Journey-2/Divine-Journey-2/files/12188011/latest.log)

**Comment by Preta-Crowz** [comment]
If it doesn't happen anymore, tracking this issue will be hard.
Also, bluescreen can happens on other programs than minecraft, you must provide error code at least.


This one is not about issue, but may important.
CurseForge uses very outdated java and doesn't download files correctly sometimes. Using other launcher will recommended.

**Comment by Atricos** [comment]
Could be faulty hardware or it could even be a [Single-event upset](https://en.wikipedia.org/wiki/Single-event_upset). Otherwise I can't see how that line of events would cause a bluescreen. Sorry that it happened to you!
