### ISSUE TITLE
Unable to spawn Asorah the Fallen

### ISSUE THREAD

**Issue by ultimatewhale** [Divine-Journey-2/Divine-Journey-2#1024]
### Modpack version

2.19.3

### Description

Unable to summon Asorah the Fallen (in AbyssalCraft) even though have the correct items and in the right dimension.
We are playing a local hosted multiplayer server (with 2 people)

### Steps to reproduce

Tried 3 separate times with new items each time (the gem is 100% (brand new) and the tanks are full), these would get consumed each time, and we had a sheep as the sacrifice, after consuming the items it would display text but nothing would spawn.
Recreated the ritual pedestals in a new area and elevation
We tried a combination of them placing items and using their own Necronomicon, me placing items and them using their own Necronomicon, and me placing items and using my own Necronomicon 

### Expected behavior

Summoning of Asorah the Fallen

### Your Divine Journey 2 Discord Username

ultimatewhale34

**Comment by Preta-Crowz** [comment]
Make sure you killed sheep after activation. If not, ingredients will gone and ritual will failed.

**Comment by WaitingIdly** [comment]
i can summon Asorath - without further reproduction steps, this isnt resolvable. could you share a video of you trying to summon Asorath?

**Comment by WaitingIdly** [comment]
no response given, couldnt reproduce
