### ISSUE TITLE
Demon Ingots Don't Craft When the Gold is Dropped By Most Modded Droppers

### ISSUE THREAD

**Issue by NickZumb** [Divine-Journey-2/Divine-Journey-2#104]
**Modpack version:**
Beta 0.1

**Description:**
When a Modded Dropper (Ex. Open Crate, Precision Automatic Dropper) drops the gold for crafting demon ingots, the gold will ALWAYS burn up.

**Steps to reproduce:**
1. Place lave surrounded by nether bricks
2. Put an open crate above the lave
3. Use a hopper to pump gold ingots into the open crate
4. The gold will burn up in the lava

**Expected behavior:**
The gold will turn into demon ingots

**Additional context:**
The vanilla dropper works fine

**Comment by KleinGrrmpf** [comment]
This has been circumvented by allowing Demon Ingots to be crafted in Fire Water
