### ISSUE TITLE
Arc Furnace main crafting area and additive area seem to be switched for Steel production

### ISSUE THREAD

**Issue by Khrumbs** [Divine-Journey-2/Divine-Journey-2#1040]
### Modpack version

2.20.0

### Description

I could be mistaken but Since 2.20 is there an issue with using coke dust as an additive for steel in the Arc Furnace.

It appears the main area and additive area are switched (this may apply to other recipes, don't have the time to check).

Originally (to memory) i recall putting IRON in the large 3x4 area of the furnace, now it appears coke is required to go into the main section and iron into what i thought was the additive section (2x2). 

### Steps to reproduce

Create an Arc Furance with power, Graphite Electrodes. Attempt to use Coke Dust as an additive with Iron to make Steel. Shift clicking moves both the iron and dust into the main crafting area. You need to manually move the iron into the 2x2 area. 

### Expected behavior

The iron should be in the larger main 3x4 crafting area, and the coke dust in the smaller 2x2 additive area.

**Comment by WaitingIdly** [comment]
having them be in that order prevents the iron dust + coke dust recipe from breaking due to the iron dust -> iron ingot recipe.
this is intentional, not a bug
