### ISSUE TITLE
AE2 Unable to handle recipes involving water/lava buckets

### ISSUE THREAD

**Issue by hoifanrd** [Divine-Journey-2/Divine-Journey-2#1041]
### Modpack version

2.20.0

### Description

AE2 is unable to process recipe chains involving water/lava buckets.
It assumes an empty bucket will be returned to AE2 after processing, even if no empty buckets are encoded in the output slot of the pattern.
This bug occurred after I updated my game version from 2.19.3 to 2.20.0

### Steps to reproduce

1. Create an AE2 system.
2. Add the following 2 recipes in AE2 (putting the pattern inside an interface for example):
    a) 1 Bucket -> 1 Water Bucket
    b) 1 Water Bucket + Some input items (e.g. 1 dirt) -> Some output items (e.g. 1 stone)
3. Request a few output items in AE2 (e.g. 10 stones)
4. The crafting summary indicates that only 2 buckets are required.

### Expected behavior

The crafting summary should indicate that 10 buckets are required.

### Additional context

This breaks some of the recipes since AE2 failed to calculate the correct amount of input items needed, causing stuck when crafting involves water/lava buckets.

### Your Divine Journey 2 Discord Username

hoifanrd

**Comment by 1235789gzy1** [comment]
You can use 'ME Fluid Assembler' or 'August: Fluid Fabric' to avoid this issue

**Comment by ByThePowerOfScience** [comment]
This is a bug with AE2-Unofficial-Extended-Life, and is not something we can patch in DJ2.
