### ISSUE TITLE
Difficulty

### ISSUE THREAD

**Issue by MaisZapfen** [Divine-Journey-2/Divine-Journey-2#1044]
### Modpack version

2.19.4

### Description

I cant change the difficulty. We are playing on a server and in the Escape Menu the game is set to "easy", on our server Webinterface its on "peaceful" and i cant change it. When I change it on the Webinterface it resets to "peaceful" and if i change it via console (command) it doesnt change anything. Any ideas?

### Steps to reproduce

change difficulty with the Webinterface (difficulty hard)
change difficulty with command (difficulty hard)
doesnt change anything (game is still on "easy")

### Expected behavior

Game should change to "hard"

### Your Divine Journey 2 Discord Username

maiszapfen

**Comment by Preta-Crowz** [comment]
I don't think it's pack issue, try to ask on web interface instead

**Comment by WaitingIdly** [comment]
this is not an issue with DJ2 - this is an issue with your server host.
