### ISSUE TITLE
Modify the item required for task # 818 to Quantum Link Card

### ISSUE THREAD

**Issue by 1235789gzy1** [Divine-Journey-2/Divine-Journey-2#1045]
### Modpack version

2.20.0

### Description

After the version update, I noticed that the Infinity Booster Card has been abandoned and replaced with the Quantum Link Card. I would like to modify the task to match the text of the item

### Steps to reproduce

After version update

### Expected behavior

Modify the items required for the task to Quantum Link Card
Change the task prompt to include the Quantum Link Card in the ME Quantum Ring for using Wireless Terminal anywhere

### Your Divine Journey 2 Discord Username

1235789gzy1

**Comment by King65868** [comment]
Update your questbook, that was already changed

**Comment by 1235789gzy1** [comment]
Sorry, it looks like I asked a stupid question
