### ISSUE TITLE
Galacticraft Core cause crash

### ISSUE THREAD

**Issue by D1monn18** [Divine-Journey-2/Divine-Journey-2#1047]
### Modpack version

2.20.0

### Java version

1.8.0_371-b11

### RAM Allocated

6 gb

### Description

Galacticraft just cause crash

### When did the crash happen?

during loadup

### Steps to reproduce

start the modpack, maybe last or pre-last phase, and crash with Description : Initializing game

### Minecraft crash report

[crash-2023-08-29_20.45.29-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/12468532/crash-2023-08-29_20.45.29-client.txt)

### Your Divine Journey 2 Discord Username

NotBadDoctor#1886

**Comment by Preta-Crowz** [comment]
Wrong java version, curseforge never uses user installed one.
Correct Java Version: 1.8.0_51

**Comment by WaitingIdly** [comment]
tlauncher is not, and will never be, supported
