### ISSUE TITLE
Elastic Fiber

### ISSUE THREAD

**Issue by TheNoobieGamer** [Divine-Journey-2/Divine-Journey-2#1052]
### Modpack version

2.20.0

### Description

In the Erebus Dimension dragonflies don't drop the elastic fiber, after 5 hours of farming and not getting one with a looting sword I'm pretty sure it is a bug

### Steps to reproduce

Go to Erebus and kill some dragonflies 

### Expected behavior

Dragonflies drop elastic fiber again

**Comment by Preta-Crowz** [comment]
> Elastic Fibre can be obtained as a common drop from Locusts in Elysian Fields/Subterranean Savannahs and as an uncommon drop from Punchrooms in Fungal Forests.

> Dragonfly
> Drops 0-2 Dragonfly Wing
> Rare Drops 1 Compound Eyes

can not confirm dragonfly drops elastic fibre

**Comment by Preta-Crowz** [comment]
ref1) [Elastic Fibre](https://the-erebus.fandom.com/wiki/Elastic_Fibre)
ref2) [Files](https://the-erebus.fandom.com/wiki/Flies)

**Comment by Dragneelius** [comment]
![2023-10-22_23 29 03](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/148723700/08c575d1-fb78-4944-9de8-104e9f035294)
For me it only dropped from the punch shrooms.
And i have looting 3.

**Comment by Cloudninjakip** [comment]
This is what they look like currently, they should probably be swapped

// Dragonfly Wing Tooltip
<erebus:materials:24>.addTooltip(game.localize("dj2.erebus_drops.desc0"));
<erebus:materials:24>.addTooltip(game.localize("dj2.elastic_fibre.desc0"));
<erebus:materials:24>.addTooltip(game.localize("dj2.elastic_fibre.desc1"));

// Elastic Fibre Tooltip
<erebus:materials:9>.addTooltip(game.localize("dj2.erebus_drops.desc0"));
<erebus:materials:9>.addTooltip(game.localize("dj2.dragonfly_wing.desc0"));
<erebus:materials:9>.addTooltip(game.localize("dj2.dragonfly_wing.desc1"));
