### ISSUE TITLE
AE2 items stack over 800 in a single 1k storage disk

### ISSUE THREAD

**Issue by Radukan** [Divine-Journey-2/Divine-Journey-2#1053]
### Modpack version

2.20.0

### Description

On the latest Divine Journey 2 modpack, have a ae2 system with 64 1k and 4k storage drives. Having problems with unstackable items in the system, usually can't withdraw them if there is few of them, but it works 50/50. Reinserting the disks in the ME Drive solves the problem until I reinsert the item in the system. But the main problem is with Energy Tablets from Mekanism - ae2 somehow stored 800 of them in a single 1k disk and I can't autocraft anything with them - trying to craft 1st tier enegy cube either sees only a few tablets and refuses to craft or refuses to craft while only showing the energy cube in red with no previous necessary steps. All crafts use oredic with manual insertion of already crafted items - tablets have no energy in them when making patterns, recipes don't require energy in them. Tried putting them in the drawers but me system won't insert them in the drawer at all(drawers priority set correctly). Can only insert them one by one manually.

How can I fix this? Never had a problem like this with similar items - nor with drives stacking more than 63 types of items within itself... I can't find any information about this, only the solution for reinserting the drives that only temporary fixes the problem.

Java variation is jdk8u382-b05 - adoptium, version 1.8.0_382 64 bit

arguments:

-XX:+UseShenandoahGC -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs/ -Daikars.new.flags=true

![1](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/13166506/1fa9a1ed-3200-4938-a881-d906dc6ad0ae)

### Steps to reproduce

1. Make ae2 system
2. Set patterns for all prerequisite items before energy tablet
3. Set pattern for the Energy Tablet
4. Try to craft
5. Weep in despair

![2](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/13166506/8a24885b-92ad-470c-9618-6218d64efff6)
![3](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/13166506/2bb36cae-8b82-49fc-b284-50fd386777c1)

### Expected behavior

Unable to craft anything requiring Energy Tablets and themselves too.
Non stack items stack in 1k drive with more than 800 items

**Comment by noel357** [comment]
It's a problem with Meka storing all information in NBT and AE being bad with NBT, you can get the items out with an Export Bus + Fuzzy Card. You have to remake the Patterns and put in an item crafted by AE in your Pattern Terminal for it to exactly know which item to use. This also isn't new, was the case a year ago and probably earlier, it's just a bit random when the problem occurs or if it does at all.

**Comment by Radukan** [comment]
> It's a problem with Meka storing all information in NBT and AE being bad with NBT, you can get the items out with an Export Bus + Fuzzy Card. You have to remake the Patterns and put in an item crafted by AE in your Pattern Terminal for it to exactly know which item to use. This also isn't new, was the case a year ago and probably earlier, it's just a bit random when the problem occurs or if it does at all.

Does it mean that I need to remake ALL of the mekanism patterns? Because I can't craft the energy tablet at all, but osgloglass and alloys no problem. Tried already with fuzzy and exporter, not exporting, but I can move them manually with me chest thingy

**Comment by noel357** [comment]
Yes you need to remake all Meka Patterns which involve items with NBT so all machines, tanks and other items, it's just a bad design only have like 5 items and then distinguish them with NBT.

**Comment by Radukan** [comment]
this is super weird - I've purged all mekanism patterns, redone everything without my inventory touching it - it can craft, but it cannot complete the craft... 
Solution? It looks like the freaking oredic in the pattern terminal made it go nuts and by extension - myself - so if anyone has a similar problem, try turning off oredic in ae2 pattern terminal for mekanism patterns. 
Weirdly enough, the disks can still hold more than 63 energy tablets, but oh well, it can see them all, and use them all, which is important. 

Thank for the help noel357 ;)

**Comment by Radukan** [comment]
Now it is happening with thermal jetpacks... too tired to try to fix it today

**Comment by noel357** [comment]
Yes it'll happen with most items which have NBT data which are many, it's just AE being bad with them. You're gonna have to manually make Patterns for a lot of items.
