### ISSUE TITLE
EMC value for Actually Additions black lotus flowers

### ISSUE THREAD

**Issue by penguinprogrammer1** [Divine-Journey-2/Divine-Journey-2#1058]
### Describe the feature

An EMC value for Actually Additions black lotus flowers should be added to the transmutation table.

### Reasons why this should be added

Black lotus flowers are a single block tall flower which unlike other flowers such as the minecraft flower, mystical flowers, and even hellebore, does not have a crafting recipe or method to make. The pack would be better because it would allow for easier decoration on a massive scale.

### Describe alternatives you've considered

Even if EMC recipe is not added, a recommended alternative would be adding a nature essence and dye essence recipe instead.

### Additional context

![javaw exe Screenshot 2023 09 29 - 22 40 00 67](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/42327703/dddf379b-7445-4d6f-ad25-91056b8e9e4f)

Collecting 1000+ black lotus for decoration seems painful, and they don't spawn often enough for a builder to be efficient.

### Your Divine Journey 2 Discord Username

sabre_penguin

**Comment by Preta-Crowz** [comment]
if you need it for black dye, there are many alternates.
squid farm, or ink bush (I'm using this one)

**Comment by penguinprogrammer1** [comment]
I do not need it for black dye. Again, the main reason is decoration. There aren't that many dark colored flowers, and this one adds variety. If I need it in large scale (thousands because the image is a showcase for large-scale decoration), then I need to spend a long time moving around builders to get them. I guess it kind of is a niche item, so I'll just close this.
