### ISSUE TITLE
Villager Trading is possible

### ISSUE THREAD

**Issue by Wilmsi** [Divine-Journey-2/Divine-Journey-2#1059]
### Modpack version

2.20.0

### Description

You can trade with Villager and can easy buy some items.

### Steps to reproduce

If a Villager stands inside a block like wheat/flowers/grass (not the block) you can rightclick the block and go into the overlay to trade. water doesnt work.

### Expected behavior

VillagerTradingBan-2.0.0.6-universal should disable the villager trading.

### Additional context

[here](https://youtu.be/_SCCjyxCGZI) is an video where i show it. if you have questions about it. dm me on discord

### Your Divine Journey 2 Discord Username

chris._.2000

**Comment by jwalty** [comment]
I installed forge 14.23.5.2859 and VillagerTradingBan 2.0.0.6-universal in a clean instance and could not replicate the issue, doesn't seem to be a problem with the mod itself - maybe another mod overriding how right clicks are handled?

https://github.com/Divine-Journey-2/Divine-Journey-2/assets/1341835/b5096015-4590-4a3e-a283-f4828ffcec3b

**Comment by Preta-Crowz** [comment]
Maybe UniversalTweaks, it has Swing Through Grass amd can be toggled from config
