### ISSUE TITLE
Missing apostrophe in quest #398

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#1064]
### Modpack version

2.20.0

### Where is the typo located?

Quest title #398 "ITS MADE OUT OF CHEESE!"

### Exact fix

Should be "IT'S MADE OUT OF CHEESE!", not "ITS MADE OUT OF CHEESE!"

Or, my recommendation, in contrast to the previous quest: "IT IS MADE OUT OF CHEESE!"

### Your Divine Journey 2 Discord Username

kleingrrmpf

**Comment by Atricos** [comment]
seriously

**Comment by KleinGrrmpf** [comment]
A typo is a typo ^^
