### ISSUE TITLE
Server cannot start

### ISSUE THREAD

**Issue by 7bloice** [Divine-Journey-2/Divine-Journey-2#1069]
### Modpack version

2.20.0

### Description

After downloading the servo package and decompressing it, click launch.bat and eula.txt will not appear.

### Steps to reproduce

1) Download the file.

2) Extract it into a folder.

3) Run the launch.bat or launch.sh file

### Expected behavior

1) Download the file.

2) Extract it into a folder.

3) Run the launch.bat or launch.sh file, and accept the EULA generated.

4) If any errors related to java version or memory occur during the launch process, open the launch.bat/launch.sh and edit accordingly. There are designated placeholders for java version, minimum ram, maximum ram, and any java arguments.

5) Launch the server with launch.bat/launch.sh.

6) You might need to Port Forward so that others can join your server.

### Your Divine Journey 2 Discord Username

blo_ice_youtube

**Comment by WaitingIdly** [comment]
cant reproduce this, youll need to be more descriptive

**Comment by Preta-Crowz** [comment]
everyone else working right, can't reproduce or find what's wrong without log

**Comment by 7bloice** [comment]
After decompressing the server package use lauch.bat:
Checking java version...


The expected java version is 1.8. Not higher, not lower.

Launching the server...

> java -server -Xms4096M -Xmx4096M  -jar forge-1.12.2-14.23.5.2860.jar nogui


> The server has stopped. If it's a crash, please read the output above.

Press any key to continue . . .



No modules added  The java version is 1.8-331

**Comment by Preta-Crowz** [comment]
Run `java -version` and post your output

**Comment by WaitingIdly** [comment]
no response, couldnt reproduce
