### ISSUE TITLE
Dragon Egg mill

### ISSUE THREAD

**Issue by Etroll780** [Divine-Journey-2/Divine-Journey-2#1070]
### Modpack version

2.20.0

### Description

Dragon egg mill's Grid Power buff is negated by the diminishing Grid Power benefits, 

### Steps to reproduce

1.start game
2.progress to rainbow stone
3.place dragon egg mill
4.read tooltip once placed
5. 1300 GP produced (87% Efficiency Loss)

### Expected behavior

10000 GP produced (minus some loss)

### Your Divine Journey 2 Discord Username

charmquark

**Comment by WaitingIdly** [comment]
the current functionality is correct. the first gives +1300 and each mill afterwards gives +500
