### ISSUE TITLE
Can We update mods like AE2 extended life etc.

### ISSUE THREAD

**Issue by Edgars-Cirulis** [Divine-Journey-2/Divine-Journey-2#1071]
### Describe the feature

Seems the modpack is discontinued.  Can we get list of mods that shouldn't be updated and that we can update easily?

### Reasons why this should be added

Up to date/bug fixes from mod side?

### Your Divine Journey 2 Discord Username

@edgarscirulis

**Comment by King65868** [comment]
Modpack is still getting updates, just be patient

**Comment by Edgars-Cirulis** [comment]
> Modpack is still getting updates, just be patient

How do you know in that case? Any source?
