### ISSUE TITLE
Improve the explanation of Wind Chime mechanics in its quest in Chapter 2

### ISSUE THREAD

**Issue by ToasterKoishi** [Divine-Journey-2/Divine-Journey-2#108]
I read through Totemic's source code and have determined how the heck Wind Chimes actually work. All the relevant information can be found in this Discord post by me on the DJ2 server: https://discord.com/channels/691927762755387402/865766973908451328/875860136692944977

I would recommend rewriting the quest description to explain the relevant parts of Wind Chime mechanics. In particular, I think it is worth explaining how to tell with particles if one is "congested," mentioning that there is a way to hang 12 Wind Chimes around a totem, that placing them under leaves IS actually useful (instead of the Totemic book being like, "uhh we herd that leaves are cool xD"), maybe a bit about the RNG nature of their contribution, and maybe something about how they don't actually contribute that much so it's ok to start with 3 and figure out other arrangements if people are struggling... etc

I also recommend changing the quest to require only 3 Wind Chimes, because 3 is the highest number of Chimes you can place without thinking about placement and have none of them be congested.

If needed, I can write the quest description in full, but I'll need to take a bit more time to sit down and focus on that later.

**Comment by Nidaelie** [comment]
Just did the diagrama of chimes like the questbook says and im unable to get all 12 working there is always 1-3 congested. 

My server people is bypassing this thing using 2+people with instruments but no way solo...
