### ISSUE TITLE
ME crafting Terminal not working

### ISSUE THREAD

**Issue by TinedPoppy385** [Divine-Journey-2/Divine-Journey-2#1080]
### Modpack version

2.20.0

### Description

Without making any changes in what I was doing, the ME crafting terminal stopped working, I cant access the terminal. On the other hand if I use a regular ME Terminal, It was as intended. Tried changing chunks on creative and all but nothing happens.

### Steps to reproduce

I don't really know what happened differently, Now It just doesn't work

### Expected behavior

I should be able to access the ME system like before, no Idea why this happens

**Comment by noel357** [comment]
Has been reported multiple times by now and there're some crash-reports in #tech-support in the Discord, should be looked at tbh.
