### ISSUE TITLE
Solar flux reborn solar panels dupe

### ISSUE THREAD

**Issue by kingkongbong6** [Divine-Journey-2/Divine-Journey-2#1084]
### Modpack version

2.20.1

### Description

When breaking solar flux reborn solar panels with immersive engineering drill you get twice as much solar panels (almost twice as much actually, if breaking 9 you get 17 so its like double-1)

### Steps to reproduce

Open the game / Start the modpack / Get into a world / ...
Get the item atleast 2 solar panels / place them / break them with immersive engineering drill / get 3 panels instead of 2

### Expected behavior

expected behavior is not getting double the amount

### Your Divine Journey 2 Discord Username

kingkongbong6

**Comment by WaitingIdly** [comment]
following your reproduction steps, i cannot reproduce this issue. could you demonstrate it?

**Comment by kingkongbong6** [comment]
> following your reproduction steps, i cannot reproduce this issue. could you demonstrate it?

https://youtu.be/9Vffj3FmAqo

i tried reproducing it with various upgrades, the iron drill bit and it worked with all of them, the only mod i have that is not up to date with pack is roots of higher version so it wont crash when opening spell library but it worked before and after updating, also i started playing(and created my world) at divine journey pack version 1.19.4 but the world i showcased it in is new like a week old so unless its some kind of old files messing with my game i dont think it is my client side fault, thats probably all the info needed and everything i can think of right now

**Comment by WaitingIdly** [comment]
you have linked a private video, i am unable to see it. i tested via the steel drill bit, with and without the second fortune upgrade, with and without the solar panel being charged via sunlight, and with and without veinminer. i tested Solar Panel II specifically, with no upgrades.

**Comment by kingkongbong6** [comment]
> you have linked a private video, i am unable to see it. i tested via the steel drill bit, with and without the second fortune upgrade, with and without the solar panel being charged via sunlight, and with and without veinminer. i tested Solar Panel II specifically, with no upgrades.

https://youtu.be/9Vffj3FmAqo

fixed

**Comment by WaitingIdly** [comment]
figured out how to reproduce this. the critical component wasnt mentioned, and thats that it needs to have Biodiesel in it.
