### ISSUE TITLE
Chapter 3 - Tricky Transitions #1725 - Energized Clathrate unobtainable before Chapter 5 (Nether)

### ISSUE THREAD

**Issue by jo-ka** [Divine-Journey-2/Divine-Journey-2#1091]
### Describe the request

I'm on a first playthrough and while all the quests so far could be solved by means I had access to at that point in time, it appears that Tricky Transitions #1725 requires Energized Netherrack, thus access to the Nether. It would indeed be possible to open a portal at this point since Flint and Steel can be crafted (and incidentally I already did that), but that is supposed to happen only in chapter 5 (?).

I also found this thread discussing the same topic: [Energized Netherrack](https://www.reddit.com/r/Minecraft/comments/11m4lyw/divine_journey_2_help/)

### Reasons why this should be changed

There are explicit hints that chapters 3 and 4 should be worked on in parallel, which worked fine for me so far, but jumping forward to chapter 5 and having to backtrack later to solve this quest is a little confusing. Maybe add a hint to that quest or adapt the recipe?

**Comment by noel357** [comment]
1. You can go into the Nether in ch1 with fire spread, it's just soft gated,
2. you can't always do all quests of a chapter before you enter the next, this won't be the last time.

**Comment by jo-ka** [comment]
Thanks for your reply. Fair enough, that will set my expectations straight for things to come. Normally, I would not have posted at all, it's just a surprising jump from all the quests until then.
