### ISSUE TITLE
Roots staff spell library doesnt open in multiplayer

### ISSUE THREAD

**Issue by IkerimI** [Divine-Journey-2/Divine-Journey-2#1097]
### Modpack version

2.20.1

### Description

The staffs spell library from the mod roots does not open and bugs out the inventory when pressing the "open spell library" keybind. This works in singleplayer but causes a bug in multiplayer.

### Steps to reproduce

1. Join a 2.20.1 Server
2. get a staff
3. press the "open spell library" keybind (default shift+o)
4. spell library doesnt open and inventory is clitched (try to drop an item, switch slots, etc)

### Expected behavior

spell library opens

### Additional context

this only happens in 2.20.1 since the newest roots mod version. There are pending issues on the roots github, but till it gets fixed there, maybe you can downgrade the roots mod in the 2.20.1 DJ2 Pack

**Comment by noel357** [comment]
It's a known bug with Roots 3.1.7 which will be hopefully fixed in 2.20.2 with Roots 3.1.8, right now you have to either downgrade Roots or the pack by 1 version.
