### ISSUE TITLE
me storage bus interaction with drawer controller

### ISSUE THREAD

**Issue by ZztuiozZ** [Divine-Journey-2/Divine-Journey-2#1098]
### Modpack version

2.20.1

### Description

when i was connecting a ME storage bus ( AE2) with a drawer controller(storage drawers) that has other drawers with items on them it would appear  that it was online but in the ME system it wouldn't show any of the items that are stored in the drawers 

### Steps to reproduce

1.opened the game without any problem
2.picked the storage bus
3. connected the storage bus to the drawer controller with avaible energy and channels 
4. system not  recongnizing the items even when it said it was online

### Expected behavior

it should show the items that are in the drawers on the system but it isn't showing 

### Additional context

there are other storage bus on the same system in  different drawers that were recognized by the system and they are closer to the system

### Your Divine Journey 2 Discord Username

zztuiozz

**Comment by noel357** [comment]
Are the Drawers more than 12 blocks away from the Drawer Controller?

**Comment by ZztuiozZ** [comment]
the drawers are directly connected to the drawer controller

**Comment by noel357** [comment]
Doesn't matter, the Controller range is 12 blocks.

**Comment by ZztuiozZ** [comment]
yes they are in the range of the controller

**Comment by noel357** [comment]
Post a screenshot in #tech-support in the Discord because it works for others.

**Comment by WaitingIdly** [comment]
cant reproduce this one. could be user error involving subnets?

**Comment by WaitingIdly** [comment]
no response and couldnt reproduce, presumed to be user error involving subnets.
