### ISSUE TITLE
Pink-black textures in ContentTweaker mod and "dja2.quest.ql.0.title" titles. 

### ISSUE THREAD

**Issue by 1kuroo** [Divine-Journey-2/Divine-Journey-2#1101]
### Modpack version

1.12.2

### Description

The problem is the 95% textures of the all items from the ContentTweaker mod are broken and titles of the quests look like "dja2.quest.ql.0.title". 

### Steps to reproduce

1. Open game / Engine the modpack / Create world
2. The "Bag of Truth (Locked)" texture is pink-black. 

### Expected behavior

I don't know.

### Additional context

Me and my friends played this modpack in May 2023 and all were good. We also have the latest NVIDIA drivers version 546.33 (12/12/2023). I don't know what's real point of this problem because i'm not a modpacks creator and apologize for my English. If u want to text or call me i left my discord acc. 

### Your Divine Journey 2 Discord Username

1kurokuro

**Comment by Preta-Crowz** [comment]
It's not pack problem and your install is corrupted. You don't have resource files to use on CT, reinstall pack to fix.

**Comment by 1kuroo** [comment]
> It's not pack problem and your install is corrupted. You don't have resource files to use on CT, reinstall pack to fix.

I reinstall the modpack a few times, but the problem doesn't disappeared.

**Comment by Preta-Crowz** [comment]
> I reinstall the modpack a few times, but the problem doesn't disappeared. 

can't reproduce because it never happens to everyone else, make sure you installed pack with right way (use AT Launcher or Prism Launcher recommended)

**Comment by WaitingIdly** [comment]
If ContentTweaker has the missingno texture, and the lang keys are untranslated, that means you do not have the correct files in the resources folder. This is not a pack issue, this is an installation issue.
