### ISSUE TITLE
[Mystical World] Antlers too hard to get without luck.

### ISSUE THREAD

**Issue by agabeluga** [Divine-Journey-2/Divine-Journey-2#1103]
### Describe the request

I think some of the plants/mobs can be difficult to find, but the deer is the most difficult one. And when you find it most of the time it doesn't drop its antlers, which are necessary for the Wildwood Armour.  Maybe you could make them more common.

### Reasons why this should be changed

it is really anoying. I had to travel ~7000 blocks to find the deer, and I only got one antlers item.

### Describe alternatives you've considered

If you can't/don't want to do that, maybe you can make the antlers drop rate bigger, like 100%. Or you could change the Wildwood Armour crafting recipe.

**Comment by Preta-Crowz** [comment]
armor isn't required on main quest line, you can do better ways later

**Comment by agabeluga** [comment]
Like what ways?

**Comment by Preta-Crowz** [comment]
> Like what ways?

Capture mob and use mob grinder with looting 10

**Comment by agabeluga** [comment]
Ok
