### ISSUE TITLE
[Roots] Game crashes when opening Roots staff menu

### ISSUE THREAD

**Issue by agabeluga** [Divine-Journey-2/Divine-Journey-2#1104]
### Modpack version

2.20.1

### Java version

1.8.0_51

### RAM Allocated

Dedicated-16G Computer has-32G

### Description

I was in creative and went into the Roots staff menu. Then it crashed.

### When did the crash happen?

While in the Roots staff menu

### Steps to reproduce

1.Get into a world
2. Get a Roots staff
3. Open Roots staff menu
4. The game crashes

### Minecraft crash report

https://pastebin.com/VqXLNx2E

### Additional context

I tried changing the keybind to "o" but it only delayed the crash
After crashing the game says it was caused by: Roots, Extra Utilities 2, Lag Goggles.

**Comment by noel357** [comment]
Known issue, downgrade Roots by 1 version.

**Comment by agabeluga** [comment]
Ok
