### ISSUE TITLE
"Return from Nothing!" (Quest #634) doesn't accept Advanced Charged Porters with NBT

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#1114]
### Modpack version

2.20.1

### Description

The quest "Return from Nothing!" (Chapter 27, quest #634) doesn't accept Porters that have already been charged. So if there is a wireless charger near you, you can't get this quest. 

### Steps to reproduce

Unlock the quest "Return from nothing!"
Place and power a Wireless Charger close to you
Craft the Advanced Charged Porter

### Expected behavior

The quest is accepted

### Additional context

If there was no way to disable NBT checking on this quest (for whatever reason), a crafting recipe to reset the Porter could work too.

### Your Divine Journey 2 Discord Username

@kleingrrmpf

**Comment by noel357** [comment]
You're gonna have fun in ch29, there're several recipes which will break with any inv charger, should definitely disable them that entire chapter.
