### ISSUE TITLE
Nature's Compass crashes your game.

### ISSUE THREAD

**Issue by Craosien1** [Divine-Journey-2/Divine-Journey-2#1116]
### Modpack version

2.20.0

### Java version

1.8.0_252

### RAM Allocated

6.8 Gigs of RAM to the game, 8 gigs of RAM for the server.

### Description

I tried to teleport using a Nature's Compass and it crashed the server, i have tried many times with the same outcome. Looking at the Discord there's been a few other people that reported the same issue.

### When did the crash happen?

When using the Nature's Compass.

### Steps to reproduce

Get into a world, get a Nature's Compass, search for a biome, try to teleport to that biome.

### Minecraft crash report

https://pastebin.com/spw0wDJN

### Additional context

No additional context.

### Your Divine Journey 2 Discord Username

Crao

**Comment by KleinGrrmpf** [comment]
I recently used the Nature's Compass on a server to locate a Coralium Swamp and I had no problems. That was on 2.20.1. So maybe updating fixes it?
