### ISSUE TITLE
Duplicate commands "/dj2 bugs" and "/dj2 issues"

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#1117]
### Modpack version

2.20.1

### Description

As stated in the title, "/dj2 bugs" and "/dj2 issues" do the exact same thing. They show the same text in chat which links you to the same page, the issues page.

### Steps to reproduce

Type "/dj2 bugs" into chat
Type "/dj2 issues" into chat
Compare the two

### Expected behavior

Only one of them exists or they point to different places (which doesn't make sense)

### Additional context

I'd suggest just removing the issues command

### Your Divine Journey 2 Discord Username

@kleingrrmpf

**Comment by WaitingIdly** [comment]
the `bugs` is an alias of issues, this is intended
