### ISSUE TITLE
Tooltip on Abyssalcraft Crystal Clusters doesn't show up and is incorrect

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#1118]
### Modpack version

2.20.1

### Description

In scripts/ModSpecific/Abyssalcraft.zs, there are two lines adding tooltips to the mod's Crystal Clusters. They state that the Clusters can only be mined with a Pickaxe of Mining Level ≥8 or ≥10 respectively. The tooltips are incorrect as both types of crystals can be mined with a Pickaxe of Mining Level Obsidian. Additionally this tooltip does not show up in game.

### Steps to reproduce

Search for Abyssalcraft's Crystal Clusters in JEI and hover over one of them
Open scripts/ModSpecific/Abyssalcraft.zs and scroll to line 652 to find the part that adds the tooltips

### Expected behavior

I was expecting the tooltip to show up and to be factually correct. If the mining level nerf is not desired anymore, the lines in the code can be removed.

### Your Divine Journey 2 Discord Username

@kleingrrmpf

**Comment by WaitingIdly** [comment]
commented out code is commented out. commented out code not appearing in the game is not a bug. the information being incorrect is why its commented out.
not a bug
