### ISSUE TITLE
Mekanism Sawdust output for some Sawmill recipes

### ISSUE THREAD

**Issue by noel357** [Divine-Journey-2/Divine-Journey-2#1120]
### Modpack version

2.20.1

### Description

The Meka Sawdust should've been replaced with the Thermal one for all outputs with the unifying script but there're 2 recipes where it still gets produced:
Menril Wood and all Natura Sticks in a Meka Sawmill.

### Steps to reproduce

Look at the usage of Menril Wood in a Sawmill, then look at the recipe of the Meka Sawdust to see both recipes.

### Expected behavior

Replace those last Meka Sawdust outputs with the Thermal one.

### Additional context

![image](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/35464991/51148270-3da5-4b52-9258-c234490b70d1)

### Your Divine Journey 2 Discord Username

NOEL357

**Comment by WaitingIdly** [comment]
the Natura Sticks -> Mek Sawdust recipes still appear in JEI, but are never actually run. i couldnt remove them, not sure why or even what adds them as a recipe? couldnt find it in Mekanism or Natura source code.

**Comment by noel357** [comment]
Yeah the Natura Sticks don't produce the Meka Sawdust but the Menril Wood does, I hope that can be fixed.
