### ISSUE TITLE
Coalstone Furnace products not extracting

### ISSUE THREAD

**Issue by SeerOfSystems** [Divine-Journey-2/Divine-Journey-2#1128]
### Modpack version

2.20.1

### Description

We were attempting to use the coalstone furnace for auto stone smelting, and ran into an issue. We could successfully insert cobblestone through the top of the coalstone furnace using a hopper, but any attempt of ours to output the stone from the product slot did not work. 

### Steps to reproduce

1. Acquire a cobblestone furnace.
2. Insert cobblestone from the top using a hopper.
3. Wait for the cobblestone to smelt into stone.
4. Attempt to automatically extract the stone using nodes/servos/hoppers/any equivalent mechanic. 

### Expected behavior

The stone in this case should be successfully pulled from the output slot of the coalstone furnace into the pipe's/hopper's inventory and piped/transported onward. 

### Additional context

We tried to extract the stone only using hoppers from the bottom, and itemducts/pipes from all sides but the top, as this is the ingame tech we currently have available to us. 

### Your Divine Journey 2 Discord Username

LordYanti

**Comment by WaitingIdly** [comment]
there isnt any way for this to be modified by the pack, so my fix is just stating that it (being any of the DivineRPG Furnaces) cannot be automated
