### ISSUE TITLE
Add Ultimate Crafting Table synthesis prompt

### ISSUE THREAD

**Issue by 1235789gzy1** [Divine-Journey-2/Divine-Journey-2#1131]
### Describe the request

After upgrading the server to 2.20.1, it seems that I still haven't solved the problem of retaining the Crafting Unit after synthesizing the Ultimate Crafting Table on the Automation Interface. However, I have found that it is possible to avoid being replaced with a Crafting Unit by pre placing an excess of 16k Crafting Storage in the Elite Crafting Table
Just like this
![image](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/52618207/314ed9f6-7eb9-4cf6-867e-16b5694802be)

### Reasons why this should be changed

Adding this method to the task may save developers the effort to fix this issue. After checking the issues, I found that it seems to have been fixed twice in a row. Although this is irresponsible, there is indeed a way to ignore this issue, isn't it?

### Your Divine Journey 2 Discord Username

1235789gzy1

**Comment by WaitingIdly** [comment]
cannot reproduce this in 2.20.1. are you sure the server updated properly?
