### ISSUE TITLE
Roots Non-Detection Effect Causes Crash

### ISSUE THREAD

**Issue by Darien490** [Divine-Journey-2/Divine-Journey-2#1134]
### Modpack version

2.20.1

### Java version

1.8.0_401

### RAM Allocated

8 GB; PC has 16 GB

### Description

While under the effect of Roots' Nondetection buff, attempting to attack a mob or when mobs attempt to attack each other, the game crashes. 

### When did the crash happen?

Crash occurs when attack makes contact with a mob.

### Steps to reproduce

1. Use Roots' "Extension" spell with the "Nondetection" augment enabled.
2. Try to attack a mob.
3. Game crashes.
4. On multiplayer, causes the server to crash.

### Minecraft crash report

[crash-2024-03-18_11.10.30-server.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/14641116/crash-2024-03-18_11.10.30-server.txt)

### Additional context

I manually updated Roots to its most recent version (3.1.9.1) to fix a separate issue I was having with Roots. (Issue #1097)

### Your Divine Journey 2 Discord Username

Anarchy#4603

**Comment by ByThePowerOfScience** [comment]
Moved to Roots repo.
