### ISSUE TITLE
ENDER IO MISSING REGISTRATION

### ISSUE THREAD

**Issue by BlazeWGF2317FRZ** [Divine-Journey-2/Divine-Journey-2#1135]
### Modpack version

2,20,1

### Java version

I dont know

### RAM Allocated

5066 MB allocated 8 GB available

### Description

Every time I start I get this error message at end of phase 4/7:
ENDER IO MISSING REGISTRATION
blockGlassHardened
I'm using TLauncher latest forge version available
Please help me

### When did the crash happen?

During loadup at phase 4/7

### Steps to reproduce

Open the game

### Minecraft crash report

https://www.mediafire.com/file/2excw0rfql3i6kb/latest.log/file

### Your Divine Journey 2 Discord Username

cannot get into server, however my username is: BlazeWGF2317FRZ or SuperDanyyy#9275

**Comment by WaitingIdly** [comment]
TLauncher is not and never will be supported, as it facilitates piracy, and makes very invasive changes. Switch to a different launcher.

**Comment by fbfnysnshnsgnwg** [comment]
also that's not a crash log.
