### ISSUE TITLE
extra utilities 2

### ISSUE THREAD

**Issue by memeskeeper** [Divine-Journey-2/Divine-Journey-2#1138]
### Modpack version

2.20.1

### Description

do NOT mine an extra utilities 2 machine with a tool with the enchantment "scorching heat" it will break the block without dropping it you WILL lose it i just lost my enchanter and crusher because of that

### Steps to reproduce

get the block (enchanter, crusher, ect..)
place it
break it with a tool with the enchantment "scorching heat"
it wont drop the block is destroyed and so lost

### Expected behavior

it should normally drop the block not destroy it

### Your Divine Journey 2 Discord Username

fakememeskeeper

**Comment by WaitingIdly** [comment]
same cause as https://github.com/Divine-Journey-2/Divine-Journey-2/issues/345
