### ISSUE TITLE
Unable to make steel in arc furnace

### ISSUE THREAD

**Issue by Confluxes** [Divine-Journey-2/Divine-Journey-2#1140]
### Modpack version

2.21.0

### Description

I cannot make steel in the Arc furnace

### Steps to reproduce

idk try and make steel i didnt do anything special it just doesnt work for me 

### Expected behavior

steel being made

**Comment by WaitingIdly** [comment]
are the iron and coal coke in the correct slots, respective to one being in the main inventory and one being in the additives inventory?

**Comment by Confluxes** [comment]
I am unable to even put coal coke dust or coal coke in the additive slot with iron in it at all it will just place the coal coke / coke dust into the same slots as the iron

**Comment by Confluxes** [comment]
I have also tried pushing them in with a hopper and that will put them in the correct slot but it will not make steel still

**Comment by Confluxes** [comment]
quick update had my friend load into a brand new world and make an arc furnace to see if it worked for him and he also has the same issue.

**Comment by Preta-Crowz** [comment]
they conflicts with other recipe, that's why it's changed

**Comment by Confluxes** [comment]
What recipe is it conflicting with cause I've had zero issues swapping them around so far. Far as I can tell there are not conflicting recipes
