### ISSUE TITLE
Draconic evolution Tablet not working - no documentation found

### ISSUE THREAD

**Issue by Zarko7** [Divine-Journey-2/Divine-Journey-2#1145]
### Modpack version

2.21.0

### Description

![image](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/166813882/e079d383-83bb-457b-afc1-2495230a8a58)
The tablet doesn´t work, as i saw this issue is already representative in other "older" modpacks, i saw that it had something to do with SSL beeing outdated, even though my error message said something else first:
[08:05:31] [PI-Update-Manager:worker-0/WARN]: ThreadFileDownloader: DL Failed sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[08:05:31] [PI-Update-Manager/ERROR]: [Pi Reported Error]: Failed to download the PI mod manifest from https://pi.brandon3055.com/manifest.json
[08:05:31] [Client thread/ERROR]: [Pi Reported Error]: No documentation pages were found! This most likely means the documentation failed to download for some reason.
[08:05:50] [Client thread/ERROR]: [Pi Reported Error]: No documentation pages were found! This most likely means the documentation failed to download for some reason.

I downloaded and added the Certificate from https://pi.brandon3055.com/manifest.json into the keystore of the java used from curseforge, C:\Users\<username>\curseforge\minecraft\Install\java\Jre_8\lib\security\cacerts. Afterwards the PKIX error was gone, but i still get this failed to download issue.

### Steps to reproduce

Open game
Open draconic evolution Tablet.

### Expected behavior

The Tablet should load the configs properly and display the documentation

### Additional context

If there is an alternative to download the configs and save them locally it would be really helpful, if there is no other fix available.

**Comment by Zarko7** [comment]
The error message is the same in latest.log and debug.log, there are basically no further information than "it doesnt work".
I´d like to debug this more myself, but can´t with no more information available.

**Comment by WaitingIdly** [comment]
from what i remember, if you use a more recent version of Java than java 1.8.0_51 (the version provided by default by CurseForge, and rather difficult to actually change - make sure to check the top right of the f3 screen to ensure its actually changed), you should not have this issue.

**Comment by Zarko7** [comment]
Thank you for the quick feedback.

Java -version showed me some 3xx version but i will verify if thats the java used ingame and try to update it if not, i found some documentation showing how to do so properly.
Tyvm

**Comment by Zarko7** [comment]
Hey, so you were right, the build used was _51.
I was able to easily change it tho. Curseforge has settings for that built in.
With the newest 411 build it works properly.

![image](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/166813882/790cb681-fdaa-4970-ba11-c9d936ff941e)
