### ISSUE TITLE
Crown of Skies skip recipe

### ISSUE THREAD

**Issue by noel357** [Divine-Journey-2/Divine-Journey-2#1147]
### Modpack version

2.21

### Description

On servers the Crown of Skies recipes which lets you skip Erebus only works in a vanilla Crafting Table and not in a Crafting Station or maybe some other crafting blocks, in those you get 64 Diamonds as the output.
In singleplayer it works in a Crafting Station, no idea what causes it.

### Steps to reproduce

Try to craft the Crown of Skies skip recipe on a server in a TiC Crafting Station.

### Expected behavior

Works for all crafting blocks on a server too.

### Your Divine Journey 2 Discord Username

NOEL357

**Comment by King65868** [comment]
Make sure both client and server have the same scripts, that sounds like a conflict

**Comment by noel357** [comment]
People ask about it quite frequently rn and doing it in a Crafting Table worked for everyone of them, no idea if they installed the pack wrong on the server.
