### ISSUE TITLE
Aether Crash

### ISSUE THREAD

**Issue by HaremKingTheLoliDestroyer** [Divine-Journey-2/Divine-Journey-2#1149]
### Modpack version

2.21.0

### Java version

14.23.5.2860

### RAM Allocated

22016 MB

### Description

Well right now i am in the Aether. I was around 10 min in the dimension but after i heard a slime and i think a cloud that shot a ball at me the game crashed. And after joining again it is the same again. I am standing right now infront of a hill. it crashed after i got hit with the air ball from the floating cloud

### When did the crash happen?

when entering the world around a few seconds later, and after going around in the Aether after a while

### Steps to reproduce

standing around 1/5 on a hill, (getting hit by air ball from the floating cloud mob.) (using resource pack(Unity) and optifine) (i have no other idea)

### Minecraft crash report

[crash-2024-05-04_12.56.13-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/15209468/crash-2024-05-04_12.56.13-client.txt)
[crash-2024-05-04_12.42.43-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/15209469/crash-2024-05-04_12.42.43-client.txt)
[crash-2024-05-04_12.35.13-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/15209470/crash-2024-05-04_12.35.13-client.txt)
![image](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/167626197/b9729e97-911b-4a2e-b474-05d8347c66e9)

### Additional context

I personally have no idea how to recreate the scene.

### Your Divine Journey 2 Discord Username

NC_steve#9632

**Comment by noel357** [comment]
Remove any additional mod you have and try again.

**Comment by HaremKingTheLoliDestroyer** [comment]
Well i removed optifine and it worked, but added it and it still works dunno if is because of optifine something other, if it happens again i will update
