### ISSUE TITLE
Incident with discord account.

### ISSUE THREAD

**Issue by Edgars-Cirulis** [Divine-Journey-2/Divine-Journey-2#1157]
### Modpack version

None

### Where is the typo located?

Hello there,

I've had no choice but to contact you here. I know it's stupid, but recently my Discord account was breached and someone spammed entire Discord channels with phishing links. I am really sorry that this incident happened. I've changed my password, reinstalled my OS, and enabled 2FA. May I please be unbanned from the DJ2 Group?

My Discord username: nexurge

### Exact fix

None.

### Your Divine Journey 2 Discord Username

nexurge

**Comment by Edgars-Cirulis** [comment]
UserID: 1018767084336984133

**Comment by WaitingIdly** [comment]
unbanned, but definitely isnt the place for it - mine or another mod's DMs are the current location, although that also isnt the best.
