### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by Tsuraname** [Divine-Journey-2/Divine-Journey-2#1162]
### Modpack version

2.21.0

### Java version

forge 14.23.5.2860

### RAM Allocated

22016 MB

### Description

i flew into an ME-Drive and the game kinda crashed and not. you can still play but the entire picture ist moved upright into the corner, so you only see one bit of it. (it happened on a Server)

### When did the crash happen?

when i played on the server normally and flew into an ME-Drive in sprint mode 

### Steps to reproduce

Have a Armour that allows flight (angle or jetplate)
sprint fly into me drive
crash or somthing i can't really categorize it 
![crash](https://github.com/user-attachments/assets/c8256869-b720-4f84-8d14-bd6995494c6d)
![crash2](https://github.com/user-attachments/assets/35a8df84-4b86-460c-a1d5-2a94c5690b59)
![crash3](https://github.com/user-attachments/assets/930c654e-4c25-4952-a2be-6f7199158d11)

### Minecraft crash report

[crash-2024-07-22_11.38.30-client.txt](https://github.com/user-attachments/files/16331215/crash-2024-07-22_11.38.30-client.txt)

### Additional context

when it first (ME-Drive tower of 4) happend i did not know if it was because i landed on a me-smart cable or the ME-Drive, but this time i flew into an ME-Drive tower(8) that did not happen to have a drive in it. it is still playable but the buttons have strange positions (not that are shown)

### Your Divine Journey 2 Discord Username

NC_steve#9632

**Comment by noel357** [comment]
Rendering an Experience Obelisk at -169,64,274 crashed you, remove it if you can or load a backup. Also update your java 8 version, you're using the years old one which CurseForge uses by default.

**Comment by Tsuraname** [comment]
The Problem is that it happend before when i did not happen to have one, and there was also the problem when i flew into an ME-Drive
