### ISSUE TITLE
Galacticraft core crashes game constantly

### ISSUE THREAD

**Issue by fbfnysnshnsgnwg** [Divine-Journey-2/Divine-Journey-2#1165]
### Modpack version

2.21.0

### Java version

1.8.0_351

### RAM Allocated

13 gb, pc has 64

### Description

I updated my version from 2.16.0 to 2.21.0, downloaded server files, galacticraft core crashes game

### When did the crash happen?

right after loading

### Steps to reproduce

1. run the game
2. wait
3. crash

### Minecraft crash report

crash report
[crash-2024-08-16_17.47.19-client.txt](https://github.com/user-attachments/files/16642023/crash-2024-08-16_17.47.19-client.txt)

**Comment by noel357** [comment]
What's your Discord username, should post it in the tech-support channel in the DJ2 Discord server.

**Comment by fbfnysnshnsgnwg** [comment]
> What's your Discord username, should post it in the tech-support channel in the DJ2 Discord server.

I don't have discord

**Comment by fbfnysnshnsgnwg** [comment]
![image](https://github.com/user-attachments/assets/200d2dcb-5600-41b2-9ae5-b84065b7f348)
[crash-2024-08-16_18.03.03-client.txt](https://github.com/user-attachments/files/16642039/crash-2024-08-16_18.03.03-client.txt)
here's an image and the crash report shown in the image

**Comment by WaitingIdly** [comment]
TLauncher is not and never will be supported, as it facilitates piracy, and makes very invasive changes. Switch to a different launcher.

**Comment by fbfnysnshnsgnwg** [comment]
Good thing I made a copy of the old version before trying to update
