### ISSUE TITLE
Laser Drill wont produce Platinum Ore

### ISSUE THREAD

**Issue by zentaos** [Divine-Journey-2/Divine-Journey-2#1170]
### Modpack version

2.21.0

### Description

Laser Drill wont produce Platinum Ores.
I have 3 white and 3 light blue lenses in the Laser Base.

Blocks placed at y82 but the depth is set to 0.

My guess is the config for platinum ore is y5-y16 instead of y0-y16.

### Steps to reproduce

Laser Base + 4 Laser Drills at y82 with 3 white and 3 light blue lenses

### Expected behavior

Produce Platinum Ore

### Your Divine Journey 2 Discord Username

zentaos

**Comment by WaitingIdly** [comment]
the y location the laser base is placed at is irrelevant to what ores are produced - your depth is `0`, and it need to be between `5` and `16`.
