### ISSUE TITLE
Extra Exploration for Space

### ISSUE THREAD

**Issue by N2K2021** [Divine-Journey-2/Divine-Journey-2#1171]
### Mod Name

Galaxy Space ( More Planets and Galaxies to Explore )

### Reasons why this should be added

Galacticraft alone with planet progression feels solid we should have more planets to progress.

### Your Divine Journey 2 Discord Username

yakhusu

**Comment by KleinGrrmpf** [comment]
I'm not sure if this really adds anything. It would just be more planets for the sake of more planets to explore. I'm not entirely solid on the current GC progression anymore, but I think there is something you gain for later automation on every celestial body you visit currently. So all of them are baked into the progression. Of course you could put the end goal of GC somewhere like pluto, but then everything from the Asteroids onwards would just be more planets for the sake of more planets. And giving every planet something that you'd need for later automation would probably be really hard, and not worth the work, to integrate into the current progression.

**Comment by WaitingIdly** [comment]
Divine Journey 2 progression is in a basically finalized state. significant new mods that change the progression will not be included in the pack (or removed from the pack, depending).
