### ISSUE TITLE
Error During Startup

### ISSUE THREAD

**Issue by Monst3rz** [Divine-Journey-2/Divine-Journey-2#1180]
### Modpack version

2.21.1

### Java version

1.8.0_422

### RAM Allocated

10GB

### Description

Upon launch error screen is displayed.
![ddddddddddd](https://github.com/user-attachments/assets/3b4e02f6-24b8-4cc7-8099-47188bf50bef)

### When did the crash happen?

Upon startup

### Steps to reproduce

Launch modpack using ATlauncher

### Minecraft crash report

https://mclo.gs/IoOxYfo
[latest.log](https://github.com/user-attachments/files/17605923/latest.log)

### Additional context

Tried fresh install, using default java, and allocating more memory.

### Your Divine Journey 2 Discord Username

Selvans

**Comment by WaitingIdly** [comment]
you have `texfix` installed in your instance. this should not the be the case, as it is not included in DJ2.21.1, and is incompatible. the error you are getting is a downstream effect of an error that only occurs if you have `vanillafix` or `texfix` installed.
