### ISSUE TITLE
there are no crafts at the essence foundry

### ISSUE THREAD

**Issue by SmartErr0r** [Divine-Journey-2/Divine-Journey-2#1185]
### Modpack version

2.21.1

### Description

trying to look at the craft of the void metal essence foundry, I found that there was no recipe for it, like all the other smelters. 
Also, while writing this text, I noticed that the crafts of a complex mystical mechanism, a simple mystical mechanism, an essence filter, a taumometer, and others were missing. But you can craft them (I checked only on the taumometer). Some recipes have disappeared on their own, regardless of which workspace is needed to create them.

### Steps to reproduce

1.Install the new version 2.21.1
2. View the crafting recipes for the items listed above.

### Expected behavior

displaying crafting recipes in JEI

### Your Divine Journey 2 Discord Username

XpyCTik🌚

upd : I fixed everything by reinstalling the build

**Comment by WaitingIdly** [comment]
"i fixed it via reinstalling", as your update states, indicates that this is a user error, not something with the pack.
