### ISSUE TITLE
AE2 Energy Cell pattern not working

### ISSUE THREAD

**Issue by RammyT** [Divine-Journey-2/Divine-Journey-2#140]
**Modpack version:**
beta

**Description:**
Cannot autocraft AE2 Energy Cells using the patterns.

**Steps to reproduce:**
1. Make a small ME system
2. Set up an Interface with a Molecular Assembler on it
3. Make a pattern for the AE2 Energy Cell and either have all the other items for the craft or make patterns for those too.
4. Watch it ask for an AE2 Energy Cell to make the AE2 Energy Cell

**Expected behavior:**
I expect it to make the Energy Cell using the items it needs.

**Screenshots:**
![image](https://user-images.githubusercontent.com/72321012/130326966-8afd9457-a69e-4525-8465-dec67800e78d.png)

**Comment by WaitingIdly** [comment]
as this appears to have never been able to be reproduced outside of a now-defunct server environment, going to consider this resolved until further evidence appears.
