### ISSUE TITLE
Conjure Demon Requires a Player to be Within the Ritual Circle to Start

### ISSUE THREAD

**Issue by NickZumb** [Divine-Journey-2/Divine-Journey-2#149]
**Modpack version:**
0.1 Beta

**Description:**
This may be an issue, but I'm not 100% sure.
The Conjure Demon bewitchment ritual tends to not start when a player isn't very close to it. It wouldn't start when I was ~60 blocks away (ritual still in render distance).  The ritual items would be places correctly and villager would be killed, but the ritual wouldn't start. edit: It appears that the ritual requires a player within the ritual circle to start

**Steps to reproduce:**
1. Set up an automatic conjure demon setup (A little easier said then done)
2. Move about ~60 blocks away (outside the circle)
3. The villager will be killed.
4. The ritual won't start

**Expected behavior:**
The ritual starts, summoning a demon.

**Screenshots:**
![image](https://user-images.githubusercontent.com/87913921/131062344-2319e0c9-3eb5-4fb0-b82a-f27ed7c98d15.png)

**Additional context:**
This may be an issue with my setup and I'm unsure how to test it

**Comment by Atricos** [comment]
Currently Demon spawning does not need to be automated with the duplication recipe, so I will close this issue. If it still causes problems, feel free to reopen it.
