### ISSUE TITLE
Another Loading Screen Tip

### ISSUE THREAD

**Issue by Realities5806** [Divine-Journey-2/Divine-Journey-2#157]
**Location:**
Loading screen tips

**Exact fix:**
"Much different from Divine Journey 1, unique recipes, unique progression, and more things to do" should be replaced with something like "This pack is much different than Divine Journey 1 with: unique recipes, (distinctive) progression, and more things to do!"

(You can replace "distinctive" with any other synonym for "unique" or keep it if you like it.)

**Comment by sarperen** [comment]
It is understandable, but it is lacking a subject.
