### ISSUE TITLE
Recipe addition: 2 logs to 16 sticks

### ISSUE THREAD

**Issue by thecodingchicken** [Divine-Journey-2/Divine-Journey-2#174]
**Modpack version:**
2.0.1

**Describe the request:**
The standard 2 logs -> 16 sticks recipe should be added/re-added.  

**Reasons why this should be added:**
Given that the logs ->planks -> sticks ratio has not been changed, it makes sense to have this recipe re-added.  It is a convenience recipe many players, me included have gotten used to.  Few less seconds crafting stuff manually. 

**Describe alternatives you've considered:**
While crafting logs -> planks, and then planks -> sticks works, it isn't as convenient when I want sticks.  

**Additional context:**
I don't believe any more context is needed.  I can work to provide more if it is asked of.  
- thecodingchicken#4835

**Comment by WaitingIdly** [comment]
i dont think its happening. such a minor QoL change, and i kinda just dont want to.
