### ISSUE TITLE
[Balance Request] Increase overworld hostile mob spawns

### ISSUE THREAD

**Issue by DaXcess** [Divine-Journey-2/Divine-Journey-2#215]
**Modpack version:**
2.1.1

**Describe the request:**
In the overworld it is very noticeable that there are very few hostile mobs. If I compare the mob from DJ1 and DJ2 then in DJ2 there are almost no cave and surface mobs with no clear indication as to why.

**Reasons why this should be changed:**
There are certain quests that require hostile mobs (like King Crabs) that take a really long time to finish because the mobs just aren't spawning.

**Describe alternatives you've considered:**
For now we are still playing legitimately but might this issue persist we would have to cheat in the items or /summon the necessary mobs to be able to continue the pack at a relatively normal pace. 

**Additional context:**
Server info: Multiplayer server, Hard difficulty, 32GB ram, Ubuntu server, High player cap.

**Comment by Retrogamesnl** [comment]
I have the same problem :'(

**Comment by RoDaBaFilms** [comment]
Also according to someone on Discord, this issue might be caused by AbyssalCraft.

**Comment by ToasterKoishi** [comment]
The more players there are on a multiplayer server, the more likely there's some random dark cave under someone's chunkloaded area that a bunch of mobs are refusing to despawn from and those mobs are eating up the mob limit. This is actually a common issue in other modded servers and even on Vanilla - one solution is to have a server plugin that kills all mobs counting towards the mob cap periodically.

**Comment by RoDaBaFilms** [comment]
There was only 1 player online during assesment

**Comment by Atricos** [comment]
I can't increase *all* hostile mob spawns, just the *ratio* of certain hostile mobs vs others.

This is caused by the Minecraft mob cap, which (even on vanilla servers) causes very few mob spawns per player, if a lot of players are online.

**Comment by tyler489** [comment]
Even with just 1 person on the server I am getting almost 0 spawns, even from day 1 of the server. In an irl week ive seen like 4 cave crawlers, an enthrawled dramcyx and a couple of spiders, I found skeletons and abyssal zombies but they were spawned from a spawner.

**Comment by NLBlacky** [comment]
I've noticed a low amount of mobs spawning in our multiplayer server as well. We do have view range on 6 which could effect this. I know of some mods that could be used to adjust the mob spawns which might be useful? [InControl!](https://www.curseforge.com/minecraft/mc-mods/in-control) and [IncreaseMobs](https://www.curseforge.com/minecraft/mc-mods/increasemobs)

**Comment by Atricos** [comment]
"IncreaseMobs" claims to work purely server-side as well, so you can simply include it on your server.

**Comment by viveleroi** [comment]
We're having this issue - 2 players are and we can literally AFK outside a night without fear of dying. We've very rarely encountered a hostile mob in a cave.

I came here because I've literally spent *hours* searching for king crabs. I've traveled 30k blocks looking at every beach I can find as well as going AFK for 90 minutes on a beach I know crabs spawn at. Nothing. I *really* do not want to spawn in items, but this isn't looking good.

**Comment by viveleroi** [comment]
Ok, I just went to an ocean monument and there were *literally zero guardians*. I wiped out the three elders and finished it. No chance any other player was there before me. Literally zero guardians are spawning. I can't even get 6 prismarine shards to finish the quest with doing another monument and killing 3 more elders, it's my only source.
