### ISSUE TITLE
Balance request: For the Roots spells removed in 2.2.0 for OP, bring them back, but a more difficult recipe. 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Divine-Journey-2/Divine-Journey-2#232]
**Modpack version:**
2.2.0

**Describe the request:**
Several spells were disabled or changed with the 2.2.0 update. Instead of removing them, how about making them harder, available in the later game. 

**Reasons why this should be changed:**
As I haven't opened both 2.0.1 and 2.2.0 together to check the differences, removing spells just makes more work for yourself. Since the recipes are already different, why not make the higher tier/op spells available during botania or something farther down in the magic block. 

**Describe alternatives you've considered:**
The spells can remain disabled, but would deviate from the full experience of roots 3. 

**Additional context:**
Please and thank you for considering this request.

**Comment by WaitingIdly** [comment]
resolved in #756. most spells were readded, however some were deemed too powerful to ever add back. additionally, some modifiers were disabled, as those were also deemed too powerful.
