### ISSUE TITLE
Change the Tomb Many Graves Mod to the GraveStone Mod

### ISSUE THREAD

**Issue by Aaron13139** [Divine-Journey-2/Divine-Journey-2#255]
**Modpack version:**
2.2.0

**Describe the request:**
I would like the Tomb Many Graves Mod to be removed and have the GraveStone Mod or the Corail Tombstone Mod added in its place.

**Reasons why this should be added:**
Add the GraveStone Mod or the Corail Tombstone Mod would be better as they are getting updates as well as the GitHub for both mods are generally active and have little to no issues left open and/or unanswered. Also, both mods have more downloads than the Tomb Many Graves Mod.

**Describe alternatives you've considered:**
The alternatives for the GraveStone Mod is the Corail Tombstone Mod and for the Corail Tombstone Mod the alternative is the GraveStone Mod.

**Additional context:**
The link to the mods I requested in exchange for the Tomb Many Graves Mod:
https://www.curseforge.com/minecraft/mc-mods/gravestone-mod
https://www.curseforge.com/minecraft/mc-mods/corail-tombstone

**Comment by xoption** [comment]
I second this. The Tomb Many Graves Mod doesn't pick up the dank null on death. This item is way too expensive to not be in your grave.

**Comment by Lgmrszd** [comment]
Corail Tombstone is not exact alternative as it adds many features that need to be addressed/rebalanced (teleportation tablets, disenchanting, etc)

**Comment by Aaron13139** [comment]
Can't we disable them? Or is that not possible?

**Comment by ISurrealI** [comment]
plus, tomb many graves has rendering issues in multiplayer.

**Comment by WaitingIdly** [comment]
changing out the grave mod at this point simply isnt going to happen.
