### ISSUE TITLE
Engineer's Workbench voids internal contents when broken

### ISSUE THREAD

**Issue by cyip92** [Divine-Journey-2/Divine-Journey-2#261]
**Modpack version:**
2.3.0

**Description:**
Breaking an Engineer's Workbench causes all the items currently in its inventory to be completely lost, such as the blueprint, any tools inside, and any stacks of extra items being "stored" inside between crafting things.

**Steps to reproduce:**
1. Open up a test world
2. Place an Engineer's workbench
3. Place a few items in its internal inventory
4. Exit the GUI and break the workbench
5. See no items in the internal inventory drop

**Expected behavior:**
For the workbench to drop its contained items instead of deleting them.  Note that the Engineer's workbench doesn't drop an alternate item version with internal data which causes inventory to be stored - placing the workbench down again results in a new workbench with an empty inventory.  The items seem entirely gone.

**Comment by OneChipBob** [comment]
unfortunately issue has been closed without resolution on IE github 
https://github.com/BluSunrize/ImmersiveEngineering/issues/3143

**Comment by FakeDomi** [comment]
Machines voiding items under various circumstances seems to be a common theme in IE.
