### ISSUE TITLE
Making energized certus/osmium/treated leather with fluid tanks doesn't consume fluid while using AE2 crafting terminal.

### ISSUE THREAD

**Issue by JacupEllis9** [Divine-Journey-2/Divine-Journey-2#262]
**Modpack version:**
2.3.0

**Description:**
Making energized certus/osmium/treated leather using tanks doesn't consume fluid while using the AE2 crafting terminal. The fluid is consumed correctly when using regular crafting tables/crafting station (haven't tried RFTools crafters). Using Enderio fluid tanks creates an error message, while the pressurised version & thermal tanks do not, but both don't consume fluid.

**Steps to reproduce:**
Craft the recipe using a tank in place of a bucket in an ME crafting terminal.

**Expected behavior:**
It should consume 1000mb, but doesn't consume any.

**Screenshots:**
![Honeyview_2021-09-10_16-53-48](https://user-images.githubusercontent.com/37311504/132883518-726651ea-2b76-470f-8d2f-7c0f72e8cafa.png)

Same error message for all 3 crafts with enderio tank

**Comment by Atricos** [comment]
I disabled the recipes that use containers for now (in 2.3.1: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3457866), I plan to reenable them once I figure out how to differentiate between crafting inventories.
