### ISSUE TITLE
Summoning DivineRPG bosses by holding the summoning item in the off-hand doesn't consume the item

### ISSUE THREAD

**Issue by Troxarus** [Divine-Journey-2/Divine-Journey-2#283]
First check if your problem has been submitted before, or if it's a Known Issue. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your issue's been fixed. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.3.0

**Description:**
When summoning a DivineRPG boss by holding the required summoning item in your off-hand it does not consume your off-hand but instead voids the item you are currently holding in your main-hand. This bug also 'works' if you have nothing in your main-hand.

**Steps to reproduce:**
1. Get into a world and put a DivineRPG boss summoning item in your off-hand (and another item in your main hand).
2. Summon the boss with a right-click.
3. The summoning item will still be in your off-hand (and your main-hand will get voided if you have something there).

**Expected behavior:**
I expected that the summoning item would disappear but that did not happen, I instead lost an item from my main-hand.

**Additional context:**
If this problem can not be fixed, I'd recommend adding a warning in the quest book as it can be quite frustrating to lose an important item from your hotbar.

**Comment by Atricos** [comment]
I reported the issue to the DivineRPG team, thank you: https://github.com/DivineRPG/DivineRPG/issues/442

I'll add a tooltip anyway.

**Comment by Ringedtech203** [comment]
Is it possible to blacklist items from off-hand?

**Comment by Atricos** [comment]
I don't think it is.

**Comment by Atricos** [comment]
Well my previous bug report has apparently been closed (https://github.com/DivineRPG/DivineRPG/issues/442), due to the developer saying "some stuff at forge changed and now I cant do much to change anything". They're only updating the 1.16 DivineRPG version now, which is a shame.

**Comment by Lgmrszd** [comment]
Maybe possible solution is to add summoning items using ContentTweaker
