### ISSUE TITLE
Reservoir Crash with lava in Aether

### ISSUE THREAD

**Issue by King65868** [Divine-Journey-2/Divine-Journey-2#295]
**Modpack version:**
2.3.1

**Java version:**
1.8.0_251

**Description:**
I placed down lava with the Thermal Reservoir in the Aether and it placed down a lava source. I placed down a bucket of lava on top of the flowing lava and the game crashed.
**When did the crash happen?**
When placing down a bucket of lava on top of flowing lava.

**Steps to reproduce:**
1. Go into the Aether.
2.  Place down a lava source with the Thermal Reservoir.
3.  Place down a bucket of lava on top of the flowing lava in Survival Mode. 
4. The game crashes. 

**Minecraft crash report:**
https://pastebin.pl/view/6d9589c1  (Orginal Crash)
https://pastebin.pl/view/1e43c575  (In a Test World)

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
I dedicated 8 GBs and my PC has 12 GBs of RAM

**Comment by Atricos** [comment]
I've added a recipe for Aerogel using Tier 1 and 2 Mystical Agriculture Essences, so hopefully fewer people encounter this issue.

Aether is weird with Lava, it tries to not let you place it, but fails, because many modded machines *can* place it.
