### ISSUE TITLE
[Known Issue] Crafting a Skyroot Remedy Bucket duplicates the Skyroot Bucket

### ISSUE THREAD

**Issue by Atricos** [Divine-Journey-2/Divine-Journey-2#3]
**Description:**
Whenever you enchant a Skyroot Poison Bucket into a Skyroot Remedy Bucket in the Enchanter, an Empty Bucket gets left behind, practically duplicating the Skyroot Bucket. (See image below.)
![image](https://user-images.githubusercontent.com/24854267/109619556-35bf1680-7b39-11eb-84ec-dc38ed0171e7.png)

My bug report on the issue: https://github.com/gildedgames/aether-issues/issues/739

**The reason this can't currently be fixed:**
Even though Aether Legacy has received further updates to fix this, Tinkers' Aether doesn't work with these versions. If Tinkers' Aether gets updated, I can update Aether Legacy as well, fixing this issue.

**Workaround:**

Keep your free Skyroot Bucket.

**Comment by WaitingIdly** [comment]
resolved via DJ2 Addons in this release: https://github.com/ByThePowerOfScience/DivineJourney2Addons/releases/tag/v1.2.0-release
