### ISSUE TITLE
Chapter 7 Exploration Grind

### ISSUE THREAD

**Issue by zMultiKiller** [Divine-Journey-2/Divine-Journey-2#303]
Modpack version:
2.3.0

Describe the request:
I personally could not find a Sunspeaker Tower after searching for about 1.5 Hours. I did explore a massive chunk of Atum, and stopped because I didn't want to load anymore terrain. Although it may be that I just didn't notice them.

Secondly the Erebus ores needed for the quest. Gneiss, Bone and Temple are all incredably rare and generate at weird Y-levels making tunnel mining very inefficant. Temple Ore seemed to be rare but managable, while Bone and Gneiss were way too uncommon. Unlike Atum the Erebus is harder to explore, so I wasn't able to explore a huge area due to the multiple layers.

Lastely, Gneiss ore doesn't have a JEI configuration spawnrate. However, I'm not sure if its the mod author who codes that in.

Reasons why this should be changed:
It wasn't enjoyable to be honest. I've never liked exploration personally, but wanted to sit myself down and give them a try. I had fun in the first hour, but after that it felt like an RNG grind hoping to stumble upon the correct ore.

**Comment by Hjaldar** [comment]
I found the Temple and Bone ores fairly quickly without any tunneling by looking in the roof of rocky areas. The Gneiss Ore I couldn't find but instead obtained Gneiss from the outcrops in the lava/desert areas using a water bucket and silk touch.

I enjoy exploration and felt I had sufficient tools (Skysoarer spell, glider, slime boots) at this stage to make traversing Erebus fairly straightforward. I'd suggest possibly fleshing out the quest text of some of the early Erebus quests in Chapter 7 (Onwards, to the Land of Bzz!, Rock'n'Roll) to remind players of the exploration tools they should have available and that the ores can be obtained without blind tunneling.

**Comment by Atricos** [comment]
Sunspeaker Towers spawn in Atum Mountains biomes exclusively. It's vey surprising that you couldn't find any, because in my experience they're quite common.

**Comment by aacidic** [comment]
From my experience - atleast so far, I ended up travelling around a total of 20-30k blocks and found two, my first didn't even have the date trade from 3 maxed sunspeaker trades so had to find a second :( . Luckily I was on a private hosted server, but this can be an issue on a public multiplayer having to travel for so long, it could be possible for an alternate recipe to be added but I can see how it can ruin the progression considering you would need the heart of ra at some point down the line regardless, it could just be a double case of bad luck, but as I said already, it could be impactful on multiplayer servers so this could go either way.

**Comment by Atricos** [comment]
If you exclusively look in mountains biomes, they should be way more common than a couple in 20-30k blocks.

**Comment by fd347657835178** [comment]
Unless I missed it, there is no tool to locate biomes, at least at that point in progression. Once I found a mountain biome the tower was easy to find, but it took a lot of blind chunk generating to get to the mountain biome beforehand.

**Comment by iKurama** [comment]
I had encountered 3 towers next to each by going NW from the portal.
Frankly random, but I needed them regardless for the dang date.

**Comment by zMultiKiller** [comment]
I wasn't aware that Sunspeaker Towers only spawn in Mountains, I only explored one of those biomes in my Atum world so that explains a lot.
However the biomes found in the Erebus are still beyond rare in my opinion. My poor wording caused a missunderstanding. I tried tunnel mining with a hammer for about ten minutes without a single ore drop. So I used a slime sling and hangglider to explore looking for exposed ores, which there was very little.

**Comment by Atricos** [comment]
As of 2.14.0, Enchanted Golden Dates can now be made in the Aether Altar as well, if the player progresses a bit further. Meaning that you can completely skip Sunspeaker Towers if you wish.

I have adjusted Erebus Ores a tiny bit since 2.3.0. Personally I played through Erebus legitimately (at around 2.9.0-ish), and I don't think it's difficult to find these Ores anymore. Look for Lava Fountains for Gneiss.

I think the main issue was the first one, so I'm going to close this now. But feel free to reopen it if you still think these are issues.
