### ISSUE TITLE
Bug: Method to Mine Unbreakable Dungeon Blocks

### ISSUE THREAD

**Issue by wildcriminal** [Divine-Journey-2/Divine-Journey-2#305]
**Modpack version:**
2.3.1

**Description:**
A way to mine Unbreakable dungeon blocks that are meant to be un-minable

**Steps to reproduce:**
1. Open the game / Start the modpack / Get into a world 
2. Get the item Runed Smasher / Go to Atum / Mine a Regular Block right next to an Unbreakable one

**Expected behavior:**
Both the Regular Block, as well as the Unbreakable one will be destroyed

**Screenshots:**

![2021-09-15_23 04 25](https://user-images.githubusercontent.com/90821958/133558483-03abf823-db69-4109-9abe-60f300a813b5.png)
![2021-09-15_23 04 34](https://user-images.githubusercontent.com/90821958/133558492-09dc4303-139c-4af1-b30d-ba1788a20fbb.png)

**Comment by WaitingIdly** [comment]
This issue is with how Atum makes its blocks unbreakable: it doesnt, it just makes it so you can't mine them. there are dozens of ways to break them.
