### ISSUE TITLE
dank nulls do not get picked up within tombstones

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/Divine-Journey-2#312]
**Modpack version:**
2.3.1

**Description:**
Dank nulls do not get picked up within tombstones upon death.

**Steps to reproduce:**
1. obtain a dank/null
2. Die
3. the item will drop into the world instead of in the grave

**Expected behavior:**
The item is supposed to go into the grave.

**Comment by TheonlyTazz** [comment]
Related:
https://github.com/Divine-Journey-2/main/issues/255

**Comment by spyrolcynder** [comment]
ples fix this

**Comment by lMagickl** [comment]
is this fixed ?

**Comment by WaitingIdly** [comment]
this should have been resolved back in June - while technically not fixed (it still doesnt pick them up), all dank/null/s now have soulbound X, which prevents this issue from occurring.
