### ISSUE TITLE
Adding Framed Compacting Drawers

### ISSUE THREAD

**Issue by jwalty** [Divine-Journey-2/Divine-Journey-2#322]
**Modpack version:**
2.4.0

**Describe the request:**
Me and a few of the lads on discord would love to see Framed Compacting Drawers
https://www.curseforge.com/minecraft/mc-mods/framed-compacting-drawers

**Reasons why this should be added:**
Makes drawer arrays infinitely more customizable and has no impact on other mods/balancing/etc.

**Describe alternatives you've considered:**
Added it myself and sulking

**Comment by Aaron13139** [comment]
I'm pretty sure the Storage Drawers Mod has framed drawers in it. I don't see anything saying that the framed storage drawers got removed or anything in the change logs. You should still be able to craft it.

**Comment by King65868** [comment]
Framed drawers are in but not framed compacting drawers

**Comment by Aaron13139** [comment]
ah ic ok.
