### ISSUE TITLE
Direct Causing Crashes With Extra Utilities 2

### ISSUE THREAD

**Issue by luluism** [Divine-Journey-2/Divine-Journey-2#345]
**Modpack version:**
2.4.0

**Java version:**
1.8.0_301

**Description:**
Using a pickaxe with Direct to break an EU2 machine will crash the server.

**When did the crash happen?**
When breaking a machine.

**Steps to reproduce:**
1. Get into world
2. Place a Survival Generator
3. Break with any pickaxe with Direct

**Minecraft crash report:**
Server Crash Log:
https://paste.ee/p/UauXD
Single Player Recreation log:
https://paste.ee/p/XbYL5

**How much RAM did you dedicate to your client and how much RAM does your PC have?**

8GB dedicated to my clientside. 16GB on my computer.

**Additional context:**
Our multiplayer server hard crashed multiple times when using a Tinker's tool with Direct on EU2 machines. I recreated this in a singleplayer world and got VanillaFix crash reports every time when using either a Tinker's Pickaxe with Direct, or a Stellar Pickaxe with the Direct upgrade.

**Comment by Atricos** [comment]
Added warnings to all Extra Utilities machine quests in Chapter 9 that breaking them with a Pickaxe that has "Direct" on it causes the server to crash in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
