### ISSUE TITLE
Exu2 Sun crystal crash while crafting Thermal Conductor Rods

### ISSUE THREAD

**Issue by iKurama** [Divine-Journey-2/Divine-Journey-2#349]
**Modpack version:**
2.4.0

**Java version:**
1.8.0_261 64bit

**Description:**
Out of my paranoid mind, I crafted 12 sun crystals, began crafting some Thermal Conductor Rods.  My first craft to be honest.
**NO MODS HAS BEEN ADDED**

**When did the crash happen?**
First R and shift + worked fine in a crafting station. The second time it 'crashed'. I might have been in a hurry.

**Steps to reproduce:**
Not sure, it was fine after making the 3rd TCR the same way, so speed might have something to do with it.

**Minecraft crash report:**
https://pastebin.com/HLxZ8ijU

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
8 gigs out of 16 gigs.

**Screenshots:**
None

**Additional context:**
None

**Comment by Atricos** [comment]
It says it's some kind of rendering bug, which could happen sometimes. Since you also don't know how to recreate it though, I don't think I can do anything to try to fix this.

**Comment by WaitingIdly** [comment]
cant reproduce this one, and its been quite a while.
