### ISSUE TITLE
Mekanism Dynamic Tank sometimes "forgets" fluid

### ISSUE THREAD

**Issue by Lgmrszd** [Divine-Journey-2/Divine-Journey-2#351]
**Modpack version:**
2.4.0

**Description:**
After some time playing, Mekanism Dynamic Tank stops functioning properly. It shows that it holds fluid, but after attempt to extract it (with Mekanism pipes, TE ducts, etc) Tank instantly shows as empty. After reforming structure (breaking and placing one of the blocks), the fluid apears again and can be normally extracted. Also, the tank was not on the chunk border.
I haven't yet managed to reproduce this bug in singleplayer but I've encountered it several times in multiplayer

**Steps to reproduce:**
1. Build a valid Mekanism tank with two valves, pump some fluid in one valve, setup redstone-controlled extractor (fluiducts with a servo)
2. Leave the chunk area/visit another dimension/relogin to let the chunk unload
3. Come back, check tank: it should display some fluid. If attempt to pump in more fluid, it would be displayed in the interface
4. Attempt to extract fluid: it should instantly "void" fluid in it, and none of it would be extracted. Any pumped in fluid may still increase stored fluid number.
5. Reform the structure: it should display all the fluid that were "voided" before.

**Expected behavior:**
The tank should function properly after chunk it is contained in is unloaded and loaded back.

**Screenshots:**
If I encounter this again, I will try to record the demonstration of this bug.

**Comment by Lgmrszd** [comment]
Also, might be related to https://github.com/mekanism/Mekanism/issues/6996
If there is a way to avoid this bug then I suggest putting some tips in dynamic tank quest.

**Comment by Lgmrszd** [comment]
[Video demonstrating the bug](https://drive.google.com/file/d/1HTt9uWG-Mc9X1NLVU6AHvzc5deqJdS_4/view?usp=sharing)

Timestamps for convenience:
0:00 -- Tank shows as empty
0:21 -- After starting biodiesel production, tank starts filling up
0:27 -- Tank is emptying "successfully"
0:46 -- Tank "voids fluid"
0:59 -- Reformed the structure, biodiesel is back in the tank, everything works as intended.

**Comment by WaitingIdly** [comment]
video not viewable on my device. please edit your message to include an embed of the video (NOT a link, upload the video itself)

**Comment by Lgmrszd** [comment]
Not sure what do you mean; I'm unable to upload the video directly as it's to big for GitHub. I uploaded it to Google Drive, if you want it to be somewhere else, I'll try to upload it here.

**Comment by Lgmrszd** [comment]
@WaitingIdly the message is updated to include direct link to a video

**Comment by Lgmrszd** [comment]
In the meanwhile, IE tank might be interesting alternative, though you can't change the "recipe" (it only uses iron sheetmetal and treated fence for the multiblock) nor the volume of it.

**Comment by iKurama** [comment]
Had it happen to me, so I thought, empty tank, let's fill it with oil. Proceeds to fill tank, empty tank and place empty tank back to its place. Suddenly it was full of lava (again)

**Comment by Atricos** [comment]
As of 2.14.0, I have removed the Dynamic Tank quest, and added warning tooltips to its components not to use it. It still retains its crafting recipe though.

While this doesn't directly fix the issue, new players will more than likely not use the Dynamic Tank, meaning the issue will slowly work itself out as more and more people complete the pack. So I will close this now.
