### ISSUE TITLE
AE2 Bugs and Performance Issues

### ISSUE THREAD

**Issue by lstrobel** [Divine-Journey-2/Divine-Journey-2#361]
**Modpack version:**
2.4.0

**Description:**
On our server, we have encountered multiple bugs relating to the version of AE2 in the pack. We encountered phantom items and crafting recipes in the terminal, power outages, and failing crafts (that shouldn't have been). We fixed a couple of issues by manually upgrading the AE2 version to the latest PrototypeTrousers version, but many still persist. 
I made this issue to present the problem up for discussion. My friends and I have been debating as to what version of AE2 to use, as, to be honest, it doesn't seem that the PrototypeTrousers one is very good. We were wondering if the pack creators had any observations or thoughts on the matter.

**Comment by Atricos** [comment]
I have updated AE2 Trouser's Edition to the latest (v47) version in 2.5.0, but seems CurseForge is taking its time to accept it. AE2 Trouser's Edition is a direct upgrade over AE2, so I don't know if there are any "better" versions out there.

**Comment by skillrax** [comment]
We are experiencing many issues on our server. Manual updating to the latest trousers edition solved none of them. 

No matter what we try, many recipes refuse to complete. Notably thats many of the mekanism machines. The formualic assemblicator has given us problems for many days of trouble shooting. It will craft them but not appear in the system until we cancel whatever autocraft recipe they were apart of. Then re requesting the craft will work as expected. 
Almost all of the factory machine upcrafts do this.

Similarly, requesting these problematic recipes often only shows that it requires itself to craft? The start button is greyed out showing it is just "missing" itself. But if we request an absurd amount that we surely havent the resources for, it will show the recipe as expected. As if it only functions as expected when it cant actually do anything.    
pulling the pattern out and putting it back in (any interface connected to molecular assembler is the same) will _usually_ solve the issue.

We have also observed the system completing crafts as expected but with ghost results. The item will show in the system, but cannot be taken out. Breaking the ME controllers and placing them again will show the completed items and the required resources are both gone. 

Played many modpacks and seen many applied energistics bugs before. But never this bad.

**Comment by Atricos** [comment]
Can you please made a report for this AE2: Trouser's Edition GitHub? (https://github.com/PrototypeTrousers/Applied-Energistics-2/issues) There is nothing on my side that I could do about it.

**Comment by lstrobel** [comment]
Most of our issues have been documented in that repositories issues at some point or another. To be completely honest, the patched mod is a hot wreck, whatever benefits it gave are being eroded by erratic version updates from the author which break or don't work. Our server has seriously considered just reverting to whatever un-patched vanilla AE2 exists. 

While this certainly won't stop us from playing your amazing modpack, it is putting a damper on some of the fun. We are curious what your motivation was behind adding the trousers version - obviously, we are lacking the context of development you had. Have you tried the vanilla AE2 version? What about Refined Storage (or even better, a choice between the two)?

**Comment by King65868** [comment]
I’ve had mostly good usage with the patched version of ae2, with all its fixes and QOL stuff I can’t go back to regular ae2. I am suprised you are having so many issues with it though.

**Comment by WaitingIdly** [comment]
RS is a excellent mod in many ways, but it has massive performance issues in 1.12, and will nuke server tps.
AE2 Trousers fixes a number of bugs with AE2 - crafting size ballooning with requests requiring items that are in the system but also have a pattern, crafting cards causing significant lag. Also adds some new features, such as the significantly improved terminal, proper JEI integration with recipes, and interface capacity cards.
If you are running into problems, please report them to ae2 trousers. "most are there" isnt all, and you not reporting means the issues cant get fixed.

**Comment by Atricos** [comment]
Does the issue still hold as of Divine Journey 2.14.0 or `appliedenergistics2-rv6-stable-7-extended_life-v0.52.4`?

**Comment by WaitingIdly** [comment]
no response. presumed that updating ae2 resolved this issue
