### ISSUE TITLE
Me terminal + sacthoth's blade bug

### ISSUE THREAD

**Issue by Bosfik** [Divine-Journey-2/Divine-Journey-2#371]
**Modpack version:**
2.4.0.

**Description:**
You can extract infinite souls from sacthoth's blade using me terminal

**Steps to reproduce:**
^

**Expected behavior:**
it should only extract the number which u've collected

**Comment by Atricos** [comment]
This is actually the exact same bug where Water doesn't get consumed from Treated Leather, but only in the Crafting Terminal: https://github.com/Divine-Journey-2/main/issues/311

I still wasn't able to figure out a solution. The Crafting Terminal doesn't (correctly?) implement `cInfo.inventory.size` or `cInfo.inventory.getStack()`, so I have no idea what to do.
If anyone has an idea, the code is located at `ContentTweakerRecipes.zs`, lines 1058-1079.
