### ISSUE TITLE
Using mechanical user in Aether to create aerogel makes the server go into crashloop

### ISSUE THREAD

**Issue by jeryrep** [Divine-Journey-2/Divine-Journey-2#395]
**Modpack version:**
2.4.0

**Java version:**
1.8.0_292

**Description:**
I made an automated aerogel creation using ender tank with lava, quantum entangloporter, fluid transposer, mechanical user and auto-breaker (actually additions). It was working fine until my guess is block miners inventory is full and it didn't break the aerogel which was created. Then mechanical user most likely got lava bucket back from fluid transposer and tried to place it which caused crash. Now we had to delete aether dimension so that server can work again.

**When did the crash happen?**
It happened while in game, now it's happening right after the server starts.

**Steps to reproduce:**
1. Go to Aether dimension
2. Make automated aerogel creation with ender tank with lava, quantum entangloporter for energy, mechanical user connected to fluid transposer so that mechanical user gets lava bucket and item conduit which takes empty bucket back to fluid transposer; auto-breaker which mines created aerogel.
3. Wait for block miners inventory to be full.
4. Server crashes instantly when mechanical user tries to place lava on not mined aerogel and goes into crashloop. 

**Minecraft crash report:**
https://pastebin.com/wEZnM78Y

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
Server has 6 GB of ram.

**Additional context:**
I did this device because fluid placer doesn't create aerogel (I tested it and it's written in questbook). I should've probably send the items directly back into my ME system, but I didn't do it.

**Comment by Atricos** [comment]
Unfortunately we've been having issues with Aerogel automation. I recently added a Mystical Agrictulture recipe for it, so use that instead for now.

This issue is likely on Aether's end, so I recommend reporting it there as well, hopefully it can be fixed: https://github.com/Gilded-Games/The-Aether-Archived/issues
