### ISSUE TITLE
HOP Graphite Dust - IE Squeezer Recipe

### ISSUE THREAD

**Issue by EpicSwampai** [Divine-Journey-2/Divine-Journey-2#413]
**Modpack version:**
2.6.0

**Description:**
When checking the recipe for "HOP Graphite Dust" in the Immersive Engineering Squeezer, it correctly shows that 8 coke dust goes in but does not show an output in the recipe. It is the same when you check Uses for Coke Dust. It only appears like this in the Immersive Engineering Squeezer receipe and appears fine in other recipes using either dust. I know the recipe but I think it may confuse some other players perhaps. 

**Steps to reproduce:**
1. Search for "HOP Graphite Dust" in JEI
2. Check recipes for the dust and click on Industrial Squeezer Tab

**Expected behavior:**
The recipe should show an output of 1 HOP Graphite Dust rather than being blank.

![2021-10-04_14 22 10](https://user-images.githubusercontent.com/91892907/135859497-687064b0-37da-4fc0-8cc7-7eaeab585a98.png)

**Comment by Atricos** [comment]
The is simply how JEI shows Squeezer recipes. Nothing I can do about it, and Immersive Engineering development for 1.12.2 has concluded, so this likely won't change.
