### ISSUE TITLE
Specify that Command Blocks are required

### ISSUE THREAD

**Issue by LordDeatHunter** [Divine-Journey-2/Divine-Journey-2#423]
**Modpack version:**
2.6.0

**Request description:**
Can you either specify somewhere in the modpack description that Command Blocks are required, or make the Eden dungeon work without them?

**Reasons why this should be added:**
We spent more time than needed in the dungeons before we figured out what the issue was.
Some players might not be as lucky in figuring it out.

**Comment by Lgmrszd** [comment]
As a suggestion, maybe it is possible to use a fill command, to remove command piston and/or command block, once it activates?
