### ISSUE TITLE
Roots Spirit Bag and Reliquary can drop useless metals

### ISSUE THREAD

**Issue by Xynariz** [Divine-Journey-2/Divine-Journey-2#437]
**Modpack version:**
2.6.0

**Description:**
Roots Spirit Bag and Reliquary loot tables include some drops that I cannot figure out how to convert back into regular metals.  Specifically, the loot contains copper nuggets, copper ingots, constantan nuggets, and silver ingots that I cannot find in JEI or convert via the methods I'd expect to be able to (e.g. smeltery, Storage Drawer conversion upgrades)

**Steps to reproduce:**
1. Launch Divine Journey 2.6.0, and open (or create) a world.
2. Unlock the harvest spell from Roots, and also unlock the "Gifts of Undeath" modifier.
3. Use the spell until you have some Spirit Bags and Reliquaries in your inventory.
4. Open the Spirit Bags and/or Reliquaries, and see what loot you get.  Some of this loot will be metals from the Mystical World mod, with no obvious way to transform them back to the normal (i.e. Thermal Foundation) variants.

**Expected behavior:**
I expected either:
* The rewards to be metals from Thermal Foundation, OR
* To be able to convert these nuggets/ingots into the respective metals, via either the smeltery or Storage Drawer Conversion upgrades.

**Screenshots:**
![image](https://user-images.githubusercontent.com/8754737/136669337-87aa016b-e669-4a99-811e-80b3a361c654.png)

**Additional context:**
This is probably something many people don't run into, since most people probably don't bother enabling the Gifts of Undeath modifier on the Harvest spell.  Nevertheless, the completionist in me thinks it'd be nice to be able to convert these back to metals I can actually use.

**Comment by Atricos** [comment]
I couldn't find a loot table for the Spirit Bag. Perhaps report this issue as a feature request for the Roots devs to make the loot table accessible / configurable.

**Comment by WaitingIdly** [comment]
resolved in #756. you can no longer obtain these items, as the modifier is disabled
