### ISSUE TITLE
Breaking Immersive Engineering excavators gives IE steel, not TF steel

### ISSUE THREAD

**Issue by Xynariz** [Divine-Journey-2/Divine-Journey-2#438]
**Modpack version:**
2.6.0

**Description:**
When disassembling a previously completed IE excavator multiblock structure, the steel blocks I got back were from Immersive Engineering.  I cannot find a way to convert these back into "normal" (i.e. Thermal Foundation) steel.

**Steps to reproduce:**
1. Launch Divine Journey 2.6.0, and open (or create) a world.
2. Give yourself (or legitimately obtain) the blocks needed to build an IE Excavator.
3. Build an IE Excavator, and use the engineer's hammer to assemble the multiblock structure.  Specifically, make sure that you build the bucket part of the excavator.
3. After the multiblock structure generates correctly, use a pickaxe to break the multiblock back into its components.
4. Observe that your inventory contains the same blocks as in step 2, except that you have IE steel instead of TF steel.

**Expected behavior:**
When breaking the excavator, the steel mined gives Thermal Foundation steel, or there is a way to turn IE steel into TF steel (such as melting in a Tinker's Construct smeltery, or using Storage Drawer conversion upgrades).

**Screenshots:**
![image](https://user-images.githubusercontent.com/8754737/136669537-e6efcc20-147d-4432-a89b-f3c22f1ee24c.png)

**Comment by KleinGrrmpf** [comment]
And even if they can't, you can uncraft them to steel ingots from Thermal
