### ISSUE TITLE
Dragon egg mill isnt configd right

### ISSUE THREAD

**Issue by Tom4455** [Divine-Journey-2/Divine-Journey-2#45]
**Modpack version:**
 beta-version-0.1

**Description:**
The base power is set to 10,000 not 5k as said in the quest book, and the effiency loss means reguardless most of the gp is wasted.

**Screenshots:**
![image](https://user-images.githubusercontent.com/8618678/128579767-23762542-4372-48db-b626-7b8284737ce6.png)

**Comment by 1234abcdcba4321** [comment]
The description in the quest is still misleading - I think it'd be good to mention that you'll only get 1300GP out of the egg mill. Saying you get 10k and then not actually getting 10k just doesn't seem right.
