### ISSUE TITLE
Uppers

### ISSUE THREAD

**Issue by Realities5806** [Divine-Journey-2/Divine-Journey-2#451]
**Modpack version:**
2.7.0

**Describe the request:**
I feel that it would be good to add the Upper mod, which add a hopper that can transport up instead of down. 

**Reasons why this should be added:**
Two reasons I think the Upper mod should be added are: (1) It would allow for better early-game automation because, before conveyors, hoppers are the only “pipe”, which limits options. The disadvantage of hoppers is that they can only move down or to the side, but Uppers would solve this problem. (2) It only adds one item and is therefore easy to implement.

**Describe alternatives you've considered:**
I can’t really think of any other alternatives except waiting until conveyors in Immersive or Itemducts at Mekanism.

**Additional context:**
This would make hopper transport possible in all directions, rather than just the sides and down, and would allow more uses for hoppers in simple early-game automation.

**Comment by WaitingIdly** [comment]
in a timely response: the duration of the period post-hopper and pre-itemduct is a extremely tiny fraction of the pack, only spanning until the end of Immersive Engineering, the first major mod in the pack. not being able to transport items directly upwards during this section is not a major impediment, and the pack doesnt require automation at this point. after this point, a hopper or upper is simply less effective than your alternatives. 
thus, while it is quite small and easy to add - its just a single block - it doesnt serve any use, and that is why i am rejecting this mod.
thanks for your suggestion from a very recent time.
