### ISSUE TITLE
Autocrafting essences with a breakable infusion crystal crashes the world/server once it runs out of durability.

### ISSUE THREAD

**Issue by IntoxicatedPlatypus** [Divine-Journey-2/Divine-Journey-2#455]
Modpack version:
2.7

Description:
See title.

Steps to reproduce:
Put an infusion crystal into an automatic crafter, put enough essence to break it, server crashes.

So far tested:
Crafter (RfTools) - Crash
Analog/Mechanical Crafter (ExUtils) - Crash
Formulaic Assemblicator (Mek) - Crash
(Simple) Crafter (EIO) - Consumes an entire crystal, crafting only 4 essences; No crash

Expected behavior:
No crash.

This forces the players to manually craft all essences until the master infusion crystal is obtainable.

FIX SUGGESTION 1:
Make the master infusion crystal immiedetely craftable to prevent the crashing. Seed tiers will still be gated by their respective station (TC Infusion, AS Crafting etc.), so there won't be progression skips.

FIX SUGGESTION 2:
Add crafttweaker crystals and replace the originals with them. Since the thermal rod (RF Powder crafting) works fine, I believe it's caused by MA itself.

FIX SUGGESTION 3:
Same as 2, but instead of replacing OGs make them unbreakable.

**Comment by Atricos** [comment]
Reading the crash report, the issue comes from the Bewitchment Tool Protection Poppet trying to protect the Mystical Agriculture Crystal from breaking.

**Question:** Is it always the same crash every time? Please provide a couple more crash reports.

I'm not sure if it's Mystical Agriculture's fault, since this particular crash doesn't even mention that. So I want to wait with this, because if it's Bewitchment's fault, I want to disable the Tool Protection Poppet instead.

**Comment by IntoxicatedPlatypus** [comment]
[RFT Crafter, 1](https://github.com/Divine-Journey-2/main/files/7357826/crash-2021-10-16_18.15.12-server.txt)
[-//-, 2](https://github.com/Divine-Journey-2/main/files/7357828/crash-2021-10-16_18.17.01-server.txt)
[-//-, 3](https://github.com/Divine-Journey-2/main/files/7357834/crash-2021-10-16_18.18.57-server.txt)

[XU Mechanical Crafter, 1](https://github.com/Divine-Journey-2/main/files/7357859/crash-2021-10-16_18.25.24-server.txt)
[-//-, 2](https://github.com/Divine-Journey-2/main/files/7357864/crash-2021-10-16_18.32.27-server.txt)

[Mek Formulaic Assembler](https://github.com/Divine-Journey-2/main/files/7357868/crash-2021-10-16_18.35.09-server.txt)

**Comment by IntoxicatedPlatypus** [comment]
[Other ones from when I tested which machines crash, 1](https://github.com/Divine-Journey-2/main/files/7357877/crash-2021-10-13_16.49.02-server.txt)
[-//-, 2](https://github.com/Divine-Journey-2/main/files/7357878/crash-2021-10-13_16.41.48-server.txt)
[-//-, 3](https://github.com/Divine-Journey-2/main/files/7357879/crash-2021-10-13_16.24.26-server.txt)
[-//-, 4](https://github.com/Divine-Journey-2/main/files/7357880/crash-2021-10-13_16.51.42-server.txt)


All have the poppet in question.

**Comment by Atricos** [comment]
Thank you.

Yeah, literally all of them just say it's the Tool Protection Poppet's fault. So I guess the next question is, did you or anyone else craft/use any Tool Protection Poppets in the same world?

**Comment by Atricos** [comment]
Hmm, not sure why this like would pop up then :|
`at com.bewitchment.common.handler.PoppetHandler.toolProtection(PoppetHandler.java:170)`

Okay, so can you try  the following things:
- Make a new instance without Bewitchment but with Mystical Agriculture Tiered Crystals, RFTools, and some other basic mods and test if the bug still happens?
- If not, then it's Bewitchment's fault. Unfortuantely the Bewitchment bug report section has been archived for 1.12.2 though: https://github.com/Um-Mitternacht/Bewitchment/issues
- If it isn't Bewitchment's fault, then can you report it to the Mystical Agriculture Tiered Crystals devs here? https://github.com/Electrolyte220/MysticalAgricultureTieredCrystals/issues

If it IS Bewitchment's fault, then I'll have to do something, for example, make all the Crystals unbreakable, or have the unbreakable one available earlier, etc.

**Comment by IntoxicatedPlatypus** [comment]
No crashes without Bewitchment

**Comment by JohanniklasLp** [comment]
Can confirm, just removing the Bewitchment mod and removing the bewitchment references in user_recipes.xml (because it won't start otherwise) in a new 2.7 instance before starting it works, no crash.

**Comment by Atricos** [comment]
Interesting. So some items produce a crash, some do not. But it seems like that it IS Bewitchment's fault. Now there are 2 issues:
- Even if the Tool Poppet isn't present, Bewitchment seems to check for it nonetheless, which is very weird.
- Bewitchment is no longer receiving any support for 1.12.2.

Unless we can convince the Bewitchment devs to look into this regardless, the only option I see is to find all (or most) items that produce a crash, and change them to custom items.

Now the problem with custom ContentTweaker items that take damage in each craft, is that AE2 likes to just eat them up. So I might not wanna change the Cutting Knife because of this.

**Comment by Atricos** [comment]
For now I made all Infusion Crystals "practically unbreakable", giving them 2147483647 durability.

**Comment by Atricos** [comment]
Oh there is, I just wasn't looking....

**Comment by KleinGrrmpf** [comment]
It's in the matc config file.

**Comment by Atricos** [comment]
Made the Infusion Crystals unbreakable in 2.8.0, which temporarely fixes the issue (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3493170). However as we discussed earlier, there is still a crash with a bunch of other items that lose durability when crafting. I need an exact list of these so I can fix them too.
