### ISSUE TITLE
Add simple light mod

### ISSUE THREAD

**Issue by InfernalGrumbler** [Divine-Journey-2/Divine-Journey-2#469]
**Modpack version:**
2.8.0

**Describe the request:**
Add simple light mod: https://www.curseforge.com/minecraft/mc-mods/simply-light

**Reasons why this should be added:**
This does not change progression, but it would provide more and earlier aesthetic lighting. I cannot find any good lamps for my factory build and have used this mod in FTB Interactions.

**Describe alternatives you've considered:**
This would be different than having to be gated until actually additions for an okay looking lamp. 

**Additional context:**
No additional context

**Comment by NaminBeforeGamin** [comment]
I don't see recipes for project red lamps. actually additions lamps, by the current recipe, require 4 redstone lamps. 2 palis, a block of black quartz. and two of the respective dyes for ONE lamp. Simple light is a really small mod so I am not sure how crazy it'd be on load time. but I'd prefer it or a recipe buff for the current lamps.
