### ISSUE TITLE
Quest reset problem.

### ISSUE THREAD

**Issue by DuarDragu** [Divine-Journey-2/Divine-Journey-2#480]
**Modpack version:**
2.7.0

**Description:**
The bug consists on every time I open the mospack using the CurseForge the quest pages just reset, so I don't know why...

**Steps to reproduce:**
So I open the modpack using the CurseForge givin 8GB ram to it and every time I open the world the quest page reset.

**Expected behavior:**
As I already did the first two pages, I expect to when I open the modpack it is completed as I already done, but when I open it isn't.

**Screenshots:**
![Inkedfoto para arrumar_LI](https://user-images.githubusercontent.com/92649769/137636378-569b71e1-575d-4d0e-b519-a407f364611f.jpg)

I already did the both marked quest pages 2 times and as soon as I open the game again it resets

**Additional context:**
I really liked the modpack and I really hope that the problem can be solved :)

**Comment by Atricos** [comment]
What launcher are you using? How are you doing the updates exactly? Please write down your step by step method.

**Comment by WaitingIdly** [comment]
no followup, not reproducible
