### ISSUE TITLE
Hellfire Forge automation quest description

### ISSUE THREAD

**Issue by pawkac06** [Divine-Journey-2/Divine-Journey-2#492]
**Location:**
Chapter 15 Questbook "Soul Smith #1541" quest.

**Exact fix:**
Step 3. Make 4 Variable Cards set to boolean "True" and add one each to Item Exporters in the "Export All Items" slot.

**Comment by antrobot1234** [comment]
well specifically, that descriptor is wrong (or unescessary) in another way too.

blank variable cards in integrated dynamics default to true. you don't need to manually assign it the true boolean.
