### ISSUE TITLE
Applied energistics infinite fluids 

### ISSUE THREAD

**Issue by Azelinia** [Divine-Journey-2/Divine-Journey-2#496]
**Modpack version:**
2.8.0

**Description:**
Unlimited fluids with applied energistics

**Steps to reproduce:**
1. Place a tank with applied fluid storage bus and set priority high 
2. Shift click fluid bucket or certain tank into me fluid terminal
3. The fluid gets inserted into tank but the bucket/tank wont empty.

**Expected behavior:**
The bucket/tank empties

**Extra info**
Only works with tank+storage bus. Disc drives work fine.

**Screenshots:**
![image](https://user-images.githubusercontent.com/59640613/138191908-17f3404c-20e0-45d5-bb73-c3333e505863.png)

Shift clicking the tank

![image](https://user-images.githubusercontent.com/59640613/138191942-d7559815-e8c7-4917-82da-d47b97e26c36.png)

**Comment by WaitingIdly** [comment]
this issue was resolved months ago in divine journey 2.10.0
