### ISSUE TITLE
Bewitchment Trading

### ISSUE THREAD

**Issue by luciscout** [Divine-Journey-2/Divine-Journey-2#498]
**Modpack version:**
2.8.0

**Describe the request:**
Disable trading with Bewitchment demons

**Reasons why this should be changed:**
You can get poppets, and other Bewitchment trades, with the demons, for extremely cheap

**Describe alternatives you've considered:**
Increasing costs significantly

**Comment by King65868** [comment]
Maybe this should be removed at some point.

**Comment by Atricos** [comment]
I looked through the Bewitchment config, and this wasn't an option there.

Villager Trading Ban exists in the pack, however, it doesn't recognize Demons and Demonesses as NPCs that can be traded with. There is also only a whitelist for the mod (`config/vtb.cfg`), to re-enable traders that the mod found. (Some DivineRPG Arcana traders are listed there.)

So if Bewitchment itself and Villager Trading Ban can't disable it, I don't know what can. Any ideas?

**Comment by Atricos** [comment]
Fixed through CraftTweaker magic in 2.14.2.
