### ISSUE TITLE
Bound Blood drop from evil craft 

### ISSUE THREAD

**Issue by picklehead8521** [Divine-Journey-2/Divine-Journey-2#504]
have played other packs before that had a bound blood drop where u can use your blood magic blood for evil craft machines 

[https://i.imgur.com/SVmtIwM.png](url)

This would make life a lot better

**Comment by Atricos** [comment]
I don't actually know what you're requesting exactly, the Imgur link has expired.

During development, I decided against using Blood Magic Blood in place of EvilCraft Blood or vica versa, because it would make it so the player can skip automating one of them.
