### ISSUE TITLE
Raise quartzite vein weight

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/Divine-Journey-2#517]
**Modpack version:**
2.8.0

**Describe the request:**
Currently, quartzite has a weight of 5. That relates to around 1% chance of finding a quartzite vein per chunk checked. Please raise this to the standard weight of 30 or at least something more reasonable like 10-15.
**Reasons why this should be changed:**
Quartz is probably one of the most needed excavator resources aside from iron and osmium later in the tech tree, so having it be so much rarer then them feels needlessly annoying. I don't want to have to search hundreds of chunks to find a single quartzite vein.

**Comment by WaitingIdly** [comment]
while Quartz veins in the overworld have not had their chance increased (in fact, with more ore veins, its been reduced), i believe the addition of quartz excavator veins in the nether should completely resolve this issue.
