### ISSUE TITLE
Add Demagnetize mod

### ISSUE THREAD

**Issue by BlackStone5677** [Divine-Journey-2/Divine-Journey-2#526]
**Modpack version:**
2.8.0

**Describe the request:**
Add the Demagnetize Mod to the pack

**Reasons why this should be added:**
The first Magnet that you get access to in the pack is the quantum flux magnet, tho it can be disabled and enabled with a keybind it is still very annoying to do that when you pass any automation that has item entities involved, E.G. Atomic Reconstructor, Demon Ingot, Mob Farms etc. So adding a way to disabled the magnets locally and with filters is very nice

**Additional context:**
https://www.curseforge.com/minecraft/mc-mods/demagnetize

**Comment by Atricos** [comment]
The first Magnet isn't the QuantumFlux Magnet, it's the EnderIO one. Additionally, the Botania Magnets can be disabled using the Solegnolia Flower, so I recommend getting those as soon as they are available. I'm not going to add this, it would just increase loadtime without a significant change.
