### ISSUE TITLE
Mekanism Boiler not Producing the Correct Type of Steam, and beacuse of that, The Steaming Restonia Recipe is Broken.

### ISSUE THREAD

**Issue by ArtpokeBr** [Divine-Journey-2/Divine-Journey-2#529]
**Modpack version:**
2.0.8

**Description:**
Basically it seems that my Mekanism Boiler is making Thermal Foundation's Steam, and this is causing an Issue where the Steaming Restonia Recipe simply does not work.

**Steps to reproduce:**
1. Make an Mekanism Boiler
2. Extract the Steam with Any type of Fluid Pipe
  3. Insert automatically in a PRC with DT-Fuel
4. And Voilá, The Crafting operation doesn't start with an Empowered Restonia

**Expected behavior:**
I Would Expect that Any type of <liquid:steam> would work or my Mekanism Boiler would make the correct steam.

**Screenshots:**
![image](https://user-images.githubusercontent.com/44851727/139163066-8c214785-f5a4-49db-a8b3-96f690023bca.png)
![image](https://user-images.githubusercontent.com/44851727/139163079-a3599396-bf44-4b79-b2f4-58962fa9d21b.png)
![image](https://user-images.githubusercontent.com/44851727/139163091-df89b7a0-d5f9-480d-8c65-3f217259f0f6.png)
![image](https://user-images.githubusercontent.com/44851727/139163402-b8348be2-7b5a-4981-bd88-5d880488c21e.png)

**Additional context:**
An Important info that I need to give is that in my pack here, I have installed:

- Optifine
- ArchitectureCraft
- Blockcraftery
- Xtones
- Immersive Posts

**Comment by WaitingIdly** [comment]
Could not replicate this with a 2.8.0 DJ2 instance. Can you replicate this in a default DJ2 instance @ArtpokeBr?
If not, going to presume its a conflict with one of the mods you added.

**Comment by ArtpokeBr** [comment]
Yeah probally it is, I've had some issues related to Crashes, but wanted to report anyway cause maybe someone could know how to fix it haha. but basically it could be a file in my save that causes that conflict somehow. And it is even crazier cause the steam from thermal even being <liquid:steam> it doesn't work :/ I don't know if you would like that, but I could send you my save file if you want to check for yourself...

**Comment by WaitingIdly** [comment]
it doesnt seem this has ever been reproduced. with that in mind, im going to be closing this.

**Comment by ArtpokeBr** [comment]
Yup, unfortunatly it seem's like this is an Specific Issue that occurred in my World due to a data coruption maybe.
