### ISSUE TITLE
Add a recipe to make abyssalcraft hydrogen from alchemistry

### ISSUE THREAD

**Issue by 1234abcdcba4321** [Divine-Journey-2/Divine-Journey-2#531]
**Modpack version:**
2.8.0

**Describe the request:**
Add a recipe to make abyssalcraft hydrogen from alchemistry.

**Reasons why this should be changed:**
Making a liquid iodine dimension (and yes, you do need one) requires 128 buckets of the liquid. Making that much of an alchemistry ingot is *really* expensive, and currently requires running a hundred crystallizers for days to get enough abyssalcraft hydrogen.

**Describe alternatives you've considered:**
Lower the amount of buckets you need for RFT dimension absorbing.
Reduce the amount of chaos shards you need (and/or amount of iodine needed for chaos shards), such that you don't need to create an iodine dimension.
Give one of the items in the crafting chain, such as hydrogen shards, methane, beam cores, alchemistry iodine, or tiny chaos shards, an EMC value.
Give alchemistry methane some recipe not based on abyssalcraft, such as one from hexane. (And then let that be crafted into abyssalcraft methane.)
Move the alchemistry fusion reactor earlier, such that you have an easier way to get the iodine.
Just make the water bucket give more abyssalcraft hydrogen, or allow using a different item that gives more. (Such as DRPG aqua balls, maybe.)

**Additional context:**
Carbon is also something made from crystallizers, but the ability to do a full block at a time speeds up the process drastically.
You can get the necessary items from rainbow tablets, too... But those are even harder to make than beam cores.

**Comment by Atricos** [comment]
A Liquid dimension now requires 8 buckets now instead of 128.
Additionally, Abyssalcraft Methane can be gotten from Alchemistry Methane; and recently we've added a recipe to convert a Roots Unending Bowl into Abyssalcraft Methane, for faster production.
