### ISSUE TITLE
Unstable Ingot can be crafted without using vanilla crafting table

### ISSUE THREAD

**Issue by VeeArr** [Divine-Journey-2/Divine-Journey-2#547]
**Modpack version:**
2.9.0

**Description:**
The tooltip for Unstable Ingots indicates that they must be crafted in a vanilla crafting table. However, this does not seem to actually be enforced in this pack. As a result, they can be crafted in a variety of workbenches that bypass their explosive drawback (making the stable unstable nugget recipe useless).

In particular, they can safely be created in the TiC crafting station and also auto-crafted via AE.

**Expected behavior:**
I expect that either the vanilla crafting table-only restriction (and its potentially explosive consequences) would be enforced. If the current behavior is intended, I would expect the tooltip to be updated if possible, and the recipe for stable unstable nuggets should probably be removed (since there's no reason to use them).

**Comment by KleinGrrmpf** [comment]
I think the tooltip can't be changed. The behavior that you can craft it in every crafting container is intended tho. The question is just whether another tooltip beneath the orginal tooltip or a note in the Moon Stone quest is better.

**Comment by WaitingIdly** [comment]
resolved in #1003
