### ISSUE TITLE
Disable Recurrent Complex's special trees

### ISSUE THREAD

**Issue by Revemohl** [Divine-Journey-2/Divine-Journey-2#548]
**Modpack version:**
2.9.0

**Describe the request:**
Basically, turn off RC's special trees by changing this option in `reccomplex.cfg` to 0:
```
    # The chance to trigger any special sapling spawns at all. If you want to disable the big trees, set this to 0. [range: 0.0 ~ 1.0, default: 1.0]
    S:saplingTriggerChance=1.0
```

**Reasons why this should be added:**
Doing this makes tree farms a lot more controllable, as you don't have to lock yourself to a few sapling types or carefully manipulate the blocks where they're planted in order to avoid creating those huge trees that risk deleting blocks as they spawn. 

**Describe alternatives you've considered:**
Can't think of any alternative other than straight up disabling them, as merely reducing their chance to spawn wouldn't change much.

**Additional context:**
Sure it's nice to see a few huge trees here and there while exploring, but I assume most people wouldn't want them to grow as uncontrollably large as they do while trying to make farms.

**Comment by Joshua-J-Payne** [comment]
> **Describe alternatives you've considered:** Can't think of any alternative other than straight up disabling them, as merely reducing their chance to spawn wouldn't change much.

Any recurrent complex structure is disabled by reducing its generation chance to 0. This can be done per-structure by using
"/#structures tweak" in-game to open a GUI for modifying structure generation values, or by changing the config file directly. Changes should be effective immediately.

**Comment by WaitingIdly** [comment]
workaround for the huge trees in tree farms: make a checkerboard pattern, use a builder on loop with blacklist of saplings, or grow different trees (use botania sapling transmutation if the farm is for the saplings).

i do not think this change would improve the pack, as it downgrades the early game exploration to benefit something which has easy workarounds. feel free to change it locally, though.
