### ISSUE TITLE
dusk diviner is needlessly expensive

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/Divine-Journey-2#550]
**Modpack version:**
2.9.0

**Describe the request:**
The diviners from blood magic serve as a convenience tool to automatically set up rituals. They provide no extra alternative beyond that function. However, the dusk ritual diviner is much more expensive relative to it's component inscription tools due to the requirement of a suppression core and the crystallized abyssalnite.

**Reasons why this should be changed:**

- The ritual diviner provides a purely convenience function. There is no reason to gate it, as rituals are constructible without it.
- The previous tier diviner cannot function as it's component tools individually. As such, the player is forced to make a secondary set of inscription tools to create dusk rituals, or grind further in progression then necessary.
- The quest for the ritual diviner is required for progression in the pack. However, the player can skip this entirely by simply using the inscription tools manually.

**Describe alternatives you've considered:**
As it stands currently, the gating for the dusk ritual diviner serves no purpose then to force an optional progression boundary or resource sink.

**Comment by KleinGrrmpf** [comment]
The diviner is not just cosmetic. If you construct rituals without the diviner, the inscription tools take damage iirc. So making a diviner is the best alternative if you want to construct a lot of dusk rituals because you don't need to craft many dusk inscription tools, just the ones you need for the diviner.

**Comment by Ringedtech203** [comment]
They could be repaired with blood from your network back on 1.7 I assume 1.12 is probably does the same or something similar

**Comment by WaitingIdly** [comment]
resolved in #756. its still expensive, but now you need it, as you cant build rituals by hand.
