### ISSUE TITLE
Duplicating liquids with mekanism tank

### ISSUE THREAD

**Issue by xeld0or** [Divine-Journey-2/Divine-Journey-2#561]
**Modpack version:**
2.9.0

**Description:**
When you right click a magma crucible with a mekanism tank (similar to thermal expansion tank, i used the mek advanced tank)the tank gets filled with liquid from the machine, but the machine itself doesn't get emptied

**Steps to reproduce:**
1. Get an empty mekanism advanced liquid tank
2. Place a magma crucible and melt some item to liquid
3. Right click the magma crucible with the empty tank
4. The tank is filled with liquid but the magma crucible doesn't get emptied
5. The liquid is duped (?)

**Expected behavior:**
The magma crucible must be emptied when right clicking with the mekanism advanced tank

**Comment by lLuckyLukel** [comment]
Recreated all the steps and it doesn't work for me

**Comment by Atricos** [comment]
Unfortunately this is purely a mod interaction, which I can't fix with external tools. Please report this to either the Mekanism or the Thermal Expansion mod devs, maybe both.

**Comment by WaitingIdly** [comment]
i cannot replicate this. in fact, the exact opposite happens - the magma crucible has its contents deleted, and my tank (tested with: Basic Fluid Tank (Mekanism), Ultimate Fluid Tank (Mekanism), Tank (Openblocks), Fluid Tank (EnderIO), and Blood Tank Tier 1 (Blood Magic), with multiple fluids) does not get filled.
so far as i am aware, nothing has changed such that this behavior would be altered, so i am a bit baffled.

can anyone else reproduce this issue?

**Comment by King65868** [comment]
Seems to work fine on 2.17.1. No duping or voiding

**Comment by WaitingIdly** [comment]
doesnt seem to be reproducible
