### ISSUE TITLE
Processing Recipes for Iron Bars and Jingle Bells

### ISSUE THREAD

**Issue by Havvy** [Divine-Journey-2/Divine-Journey-2#568]
**Modpack version:**
2.9.0

Add the following recipes such that iron rods and jingle bells can be turned back into iron if wanted (e.g. if you craft too many):

* Sag Mill Iron Rod -> ~~2~~ 1 Pulverized Iron
* Sag Mill Jingle Bells -> ~~7~~ 5 Pulverized Iron
* (Same for quartz grinder, crusher, pulverizer, etc.)
* Chemical Dissolve Iron Rod -> ~~32~~ 16 Iron
* Chemical Dissolve Jingle Bells -> ~~112~~ 80  Iron

Also, for consideration, the following recipes for iron rods

* ~~Alloy iron rod + nickel/pulverized nickel -> 3 Invar~~
** ~~It would make making the alloy easier since we'd have equal item stack quantities for both metals)~~
* Blast Furnace iron rod -> steel rod
** Let's the player choose which order to process. So can craft into rod and blast or blast and craft into a rod.

**Comment by WaitingIdly** [comment]
You can make rods for 1 iron. Hopefully obviously, dupe recipes wont be added.

**Comment by Havvy** [comment]
Oh, I missed that. Nevermind this then.

**Comment by Havvy** [comment]
Actually, just process to 1, not 2.

**Comment by WaitingIdly** [comment]
this isnt planned
