### ISSUE TITLE
Grinding down Destabilized Redstone Ore in a SAG Mill gives Abyssalcraft's Crystallized Redstone

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#570]
**Modpack version:**
2.9.0

**Description:**
Grinding down Destabilized Redstone Ore in a SAG Mill gives Abyssalcraft's Crystallized Redstone

**Steps to reproduce:**
1. Place and power a SAG Mill
2. Put Destabilized Redstone Ore into it
3. Observe

**Expected behavior:**
The recipe gives Destabilized Clathrate instead of Crystallized Redstone

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/50833808/143489767-c26809b9-1821-42ff-ac45-a8e32595cdb5.png)

**Additional Context**
Might be related to https://github.com/Divine-Journey-2/main/issues/430

**Comment by WaitingIdly** [comment]
resolved at some point prior to now, likely around 2.9
