### ISSUE TITLE
Please bring back the quest complete chimes from DJ 1

### ISSUE THREAD

**Issue by Dan-Ross** [Divine-Journey-2/Divine-Journey-2#588]
**Modpack version:**
2.9.1

**Describe the request:**
We're long time Please bring back the quest completion fanfare from Divine journey 1. My wife needs the dopamine hit when completing her quests!

**Reasons why this should be added:**

**Describe alternatives you've considered:**
I looked at moving the .ogg file from the DJ1 quest mod into Better questing but couldn't figure it out :(

**Comment by WaitingIdly** [comment]
The sound in question from DJ1 is from HQM - specifically, this sound right here: https://github.com/lorddusk/HQM/blob/f5ac7e773aa874c4419ec2a19d5312de5d763b9d/src/main/resources/assets/hardcorequesting/sounds/complete.ogg. This mod is not in DJ2 (we use Better Questing, not HQM).
Getting this sound over seems pretty easy, however, as it should just be downloading and add HQM to your client and server; then replacing all entries of `minecraft:entity.player.levelup` in `config/betterquesting/DefaultQuests.cfg` with `hardcorequesting:complete`.

As HQM will not be added to the pack, going to close this issue. If you still want it, hope my answer above helps.
