### ISSUE TITLE
Lingering potion of Speed III and IV uncraftable 

### ISSUE THREAD

**Issue by Kherune** [Divine-Journey-2/Divine-Journey-2#598]
**Modpack version:**
2.9.1

**Description:**
Lingering potion of swiftness III and IV are uncraftable

**Steps to reproduce:**
try to craft Lingering potion of swiftness III or IV 

**Expected behavior:**
it crafts

**Additional context:**
Because the potion is uncraftable it results in the Arrow Speed upgrade Key for draconic also being uncraftable as it calls for 2 arrows of swiftness IV which need the lingering Potion of speed IV

**Comment by King65868** [comment]
Was just able to craft it, so it is actually craftable

**Comment by Kherune** [comment]
Its the JEI routing that seems to be the issue, you have to get to the recipe from the speed 4 potion to alchemical imbuer. Not sure if that's something the mod pack can deal with though

**Comment by WaitingIdly** [comment]
lingering potions of swiftness III and IV are craftable. the JEI recipe does not display correctly, but there is nothing we can do about this.
i will edit a quest description (or two?) to clarify this.
