### ISSUE TITLE
Thaumcraft matrix

### ISSUE THREAD

**Issue by redeck1** [Divine-Journey-2/Divine-Journey-2#601]
**Modpack version:**
2.9.1
When I look for recepies on matrix from Thaumcraft my minecraft crushed. I think there is no matrix interface or something similar in the game files, because  in modular magic the recepies are. Please help

**Comment by Atricos** [comment]
Please
- specify the exact steps to reproduce
- provide a crash report
- specify how much RAM your PC has and how much of it is allocated to Minecraft
- what your Java version is
- what launcher you are using.

**Comment by WaitingIdly** [comment]
no followup
