### ISSUE TITLE
World crash when trying to view use in JEI of Atum 2 items

### ISSUE THREAD

**Issue by ArkhamAggron** [Divine-Journey-2/Divine-Journey-2#610]
### Modpack version

2.4.0

### Java version

1.8.0_51

### RAM Allocated

9 gigs

### Description

I picked up a date and tried to see what it was used for by pressing U on it. I saw the glistening Date in the recipe path and pressed U on that aswell. that caused my world to close and didn't save a crash log. I later picked up some tarantula fangs and pressed U on them, which also closed my world and didn't gave a crash log. they both say it was JEI that caused the server shutdown.

### When did the crash happen?

When using the item use keybind in JEI.

### Steps to reproduce

Try to use the item use keybind on a glistening date or tarantula fangs.

**Comment by WaitingIdly** [comment]
if no crash report generated, please use the `latest.log` from the logs folder. 
additionally, java 0_51 can have issues that do not exist in modern versions, so please update your java and confirm the issue still occurs.

**Comment by Ringedtech203** [comment]
Your modpack is also 5 version behind you may want to update that

**Comment by ArkhamAggron** [comment]
[latest.log](https://github.com/Divine-Journey-2/main/files/7966620/latest.log)

I use CurseForge and it shows that i'm using the most updated version

**Comment by WaitingIdly** [comment]
rolling back through here:
i cant reproduce the issue, and this appears like it may be a rendering issue - and you have optifine, texfix (and potentially other unmentioned mods you added that i didnt noticed), and an outdated java version.
if the problem still persists in the latest update (2.14.2) without additional mods, please update java and remove optifine, and if it still persists comment, and the issue will be reopened.
