### ISSUE TITLE
Bewitchment Distillery Recipes does not detect NBT of Florbs or Vis Crystals Types

### ISSUE THREAD

**Issue by Josephw00t** [Divine-Journey-2/Divine-Journey-2#619]
### Modpack version

2.10.0

### Description

The recipe that requires a specific type of Vis Crystals from Thaumcraft and the Empowered Oil Florb are not detected by a Distillery ( Bewitchment ) and accept either an empty Florb or any type of Vis Crystals in the recipe. I don't know if this was known but I have been using this currently for Vis crystals.

### Steps to reproduce

Get to Bewitchment and Use a Distillery
Craft any Recipe that uses a Florb or specific Vis Crystal
Instead of using the proper item use an empty Florb or a more commonly dropped Vis Crystals in the Recipe
The Item is still crafted

### Expected behavior

The Distillery should detect the correct item and not craft when its an empty Florb or any type of Vis Crystals

**Comment by Atricos** [comment]
I know this is an issue, but it's not something I can fix. This is a buggy interaction between Bewitchment and CraftTweaker/MoreTweaker. I think the issue is on MoreTweaker's side to be specific. Please report it to them, and if they provide a fix, I will update MoreTweaker to the fixed verison.
