### ISSUE TITLE
Addition to the "Can be found in moonglow" quest description

### ISSUE THREAD

**Issue by CKNoah** [Divine-Journey-2/Divine-Journey-2#623]
### Describe the feature

After about an hour of looking for nether reeds, I decided to go look for some on a creative world. After a while of exploring and testing, I was just about to make a bug report until I found that nether reeds spawn adjacent to lava. So I ask that you please include that in the quest description (in roots section) so no one else has to go through the same pain I did.

### Reasons why this should be added

read desc

### Describe alternatives you've considered

Make it so nether reeds can spawn anywhere in the nether

**Comment by Ringedtech203** [comment]
I'd assume people would be able to figure out that they would work the same way as the normal version

**Comment by CKNoah** [comment]
Why would anyone remember that they spawn adjacent to lava, (unless they've had the same struggles as me)

**Comment by CKNoah** [comment]
So you're saying it shouldn't be added?
