### ISSUE TITLE
New AE2 Edition has negatively altered export buses.

### ISSUE THREAD

**Issue by HQManiac** [Divine-Journey-2/Divine-Journey-2#624]
### Modpack version

2.11.0

### Description

Filing this because several people have noted issues with the newest version of AE 2.
Export busses appear to behave abnormally. For example, I have noticed that if it is attempting to export two or more items on round robin, it will completely fill one of the items and then only add one per cycle of the other. Others have noticed (and I can corroborate) that export busses have begun not checking if their connected inventories are full, and will infinitely export items. This leads to many items being flooded into the Me system from lower priority storages going to higher ones.

These are just what I have noticed and what others in the discord have corroborated. There could be others for all I Know.

### Steps to reproduce

For both,
1. Get a box or drawer of items set to a low priority storage bus
2. get and second box or drawer with higher priority
3. Get a third box with an export bus attached with two or more acceleration cards
4. Connect everything to the same ME system
5. Observe as the export bus fills its box, and as the remainder of the lower priority box is siphoned into the higher tier one.

For the multiple items, do the same as above except with a 2x2 drawer on the export bus.

### Expected behavior

I would have expected that export busses would not grab more items than they needed to, and thereby overfill the system leading too items moving in undesired ways, as this is how it worked before the mod change.

Additionally, It can be very annoying as this can lead to setups that worked quite well previously suddenly becoming severely broken, as I experienced when my glowstone processor turned 2.5k stack of glowstone into dust, when it should have only done about 10.

Additionally, I seems that some people have noticed the changes have broken parts of their Autocrafting setups, though I have not experienced this.

As for suggested changes, I would revert to the previous version. This one appears to have at least a few annoying, if not outright game breaking, bugs.

**Comment by KleinGrrmpf** [comment]
I have an addition to this. When I autocraft a black hole unit, I get the storage housings from the storage cells back. But it doesn't use them again but crafts new ones every time. And the cells should be consumed with the housings anyway...

**Comment by Atricos** [comment]
As of 2.14.2, I have updated AE2 Unofficial Extended Life from v51e to 0.52.4 (that's 10 versions ahead). Does the issue still stand?

**Comment by WaitingIdly** [comment]
no response, closing
