### ISSUE TITLE
Putting Backpacks into the Handy Bag from Ender Utilities will delete the items inside. 

### ISSUE THREAD

**Issue by EagleHamlet** [Divine-Journey-2/Divine-Journey-2#626]
### Modpack version

2.10.0

### Description

I put my Epic Backpack with some stuff that I got from Erebus in my Handy Bag from Ender Utilities. Upon retrieval, all of the items inside the backpack were gone.

### Steps to reproduce

Put Epic Backpack in Handy Bag from Ender Utilities. 
Retrieve the backpack and all the items inside will be gone. 

### Expected behavior

I should still have my items inside the backpack.

### Additional context

One of the reasons this happened **might** be because I have 2 Epic backpacks in my inventory and when I put them both, the empty backpack might've overwritten the one with loot inside since the Handy Bag wants to stack the items but can't.

**Comment by KleinGrrmpf** [comment]
I am pretty sure that the handy bag is from Ender Utilities and not from Extra Utilities.

**Comment by EagleHamlet** [comment]
> Collaborator

Fixed, I was looking at some items in Extra Utilities which confused me whilst I was making this post. 
Ty

**Comment by Atricos** [comment]
Can you please also report this to the Ender Utilities devs? There is no config option in `enderutilities.cfg` to disallow certain items to be put in Handy Bags.

**Comment by ByThePowerOfScience** [comment]
I've been unable to reproduce the issue.  Could you please explain what specifically happened between putting the backpack into the Handy Bag and retrieving it?  Did you cross dimensions? Did you take off the HB and put it in a chest? Did you remove a memory card?

**Comment by WaitingIdly** [comment]
no response two months after asking for more reproduction steps.
cannot reproduce.
