### ISSUE TITLE
Internal server error on Multiplayer/ Potential cause is RFtool Dimesion by the warning screen

### ISSUE THREAD

**Issue by swear01** [Divine-Journey-2/Divine-Journey-2#637]
### Modpack version

2.11.0, reauth removed

### Java version

Hotspot JVM/ Eclipse OpenJ9 8u321

### RAM Allocated

10GB of 32GB installed

### Description

![image](https://user-images.githubusercontent.com/49574926/158068892-6568a2e3-cac9-4eb8-a9d9-b91f9ce26c63.png)
need help.
Ping show in F3 Hammercore continued increasing
and the game freeze (like the server no respond)
after a whlie I was kicked and the game screen show "an existed connection was forceably closed"
after that, I got the crash report
this happened every time I log in my server
also when I attempted to log in to the pixel gaming server, it shows the following, but I didn't use any VPN or Proxy
![image](https://user-images.githubusercontent.com/49574926/158069003-85f30c5f-afcd-4788-861f-238d21ed00ba.png)

### When did the crash happen?

When I was kicked from the multiplayer
When I create a single player world and after it generated

### Steps to reproduce

1. Download the pack using MultiMC
2. Start the game
3. create a single player world
4. crash

### Minecraft crash report

[crash-2022-03-13_21.55.47-client.txt](https://github.com/Divine-Journey-2/main/files/8240135/crash-2022-03-13_21.55.47-client.txt) multiplayer one
[crash-2022-03-14_00.14.44-server.txt](https://github.com/Divine-Journey-2/main/files/8240136/crash-2022-03-14_00.14.44-server.txt) single player one

### Additional context

IDK if it a problem unique to my computer.
Since when I use my laptop, It works well.
But even I reinstall Windows it didn't work

Following is computer spec:
CPU: R7 3700x
RAM: Mircon 3200 16gb*2
MB: TUF b450M PRO
Wifi: Intel AX200

**Comment by WaitingIdly** [comment]
RFTools Dimensions has a bug wherein attempting to join a singleplayer world after being in a world with RFTools Dimensions registered will cause a crash. RFTools Dimensions is no longer being updated for 1.12.2. The solution is to simply relog.

The "crashed on server" part is entirely irrelevant to this crash.
