### ISSUE TITLE
Remove / Replace CH 12 Fishing Net Quest with Resources Fisher from Industrial Foregoing. 

### ISSUE THREAD

**Issue by EagleHamlet** [Divine-Journey-2/Divine-Journey-2#639]
### Describe the feature

![image](https://user-images.githubusercontent.com/90133613/158394851-7e880d47-e01f-4c79-b3b3-71709e3961c6.png)
This is the quest in question, it can be found in CH 12

Remove or Replace this quest because its item is utterly useless. 

### Reasons why this should be added

It comes to a point where one asks himself where to get fish, name tags, other marine fauna, flora & enchantment books from.
The answer is simple:

- **The resources fisher**

This machine can do all of the above & it's simply the easiest way of generating enchantment books. 

Why replace the fishing net? 

- It's extremely slow at generating resources
- It uses the resources fisher as an ingredient in its recipe. Why craft an inferior block when u can have a Resources fisher?
- No1 that I know talks or uses this item. 
- The Resources fisher bloody exists. Not to mention, it can also accept upgrades, making it even better & faster. 

### Describe alternatives you've considered

2 Things can be done:
- Completely remove this quest & make a quest in CH 11 where you're needed to craft a Resources Fisher from Industrial Foregoing
OR
- Simply replace the fishing net quest with the resources fisher.

### Additional context

I'll even provide the damn description for the resources fisher quest:

"Did you know Finding Dory was one of Pixar's highest grossing movies of all time? 

Craft the Resources fisher! This machine can be easily set up over a 3x3 square of water to gather a variety of marine fauna, flora, ink sacks, nametags & enchantment books. This is probably your best bet at generating enchantment books that u don't own. Best paired with the Enchantment Applicator and the Enchantment Extractor to extract the enchants off a book or item that u want."

"[optional], add this line at the bottom -> If you're looking to copy enchantment books, should consider looking into bibliocraft"

Not just that, but this quest can be followed by another quest where you're supposed to craft an Enchantment Applicator, Fabricator & Extractor. These blocks go so well hand in hand, it's crazy. 

Edits: Typos

**Comment by WaitingIdly** [comment]
resolved in #756
