### ISSUE TITLE
Gamecrash when crafting universal wireless terminal (item gas fluid) with me crafting terminal in an me crafting terminal

### ISSUE THREAD

**Issue by Sebbben** [Divine-Journey-2/Divine-Journey-2#641]
### Modpack version

2.12

### Description

when trying to use a crafting terminal to craft a universal wireless terminal (item fluid gass) with a crafting terminal it crashes the game. 

### Steps to reproduce

1. boot game and open server/world
2. get a wireless terminal (item)
3. craft it together with a fluid terminal then with a gas terminal
4. open a crafting terminal hooked up to an me system
5. craft the newly crafted universal wireless terminal (item gas fluid) with a crafting terminal

### Expected behavior

Should crash the game, but get picked up by a crash mod

**Comment by WaitingIdly** [comment]
you clearly state multiple times that this is a crash. why did you use the "bug" issue form instead of the "crash" issue form
