### ISSUE TITLE
Unending bowl automatically fills meat feeder

### ISSUE THREAD

**Issue by DillePickle** [Divine-Journey-2/Divine-Journey-2#644]
### Modpack version

2.13

### Description

Unending bowl from roots will automatically fill the meat feeder from industrial foregoing to full as long as the bowl is placed inside your inventory.

### Steps to reproduce

1: Open the game and world
2: Get unending bowl and meat feeder
3: Put meat feeder in head bauble slot and unending bowl anywhere in the inventory
4: Meat feeder has max liquid meat and will continue to get filled as long as the unending bowl is in the inventory.

### Expected behavior

Nothing should happen between these two items since unending bowl only provides water.

**Comment by KleinGrrmpf** [comment]
This has already been reported on the Roots GitHub and the last time I checked, the mod author couldn't/didn't want to do anything about it in 1.12.2 anymore... So unless someone creates a fork, I don't think that this is going to get fixed. 
But it is a known issue.

**Comment by ByThePowerOfScience** [comment]
This issue has been fixed in the upcoming Roots 3.1.5 release, and a temporary patch has been put in place for DJ2.

**Comment by KleinGrrmpf** [comment]
This has been fixed in 2.15.0
