### ISSUE TITLE
Quest id 1631 Watch where you cut! omission

### ISSUE THREAD

**Issue by oblivion2k** [Divine-Journey-2/Divine-Journey-2#646]
### Modpack version

Latest (Pixel Gaming server)

### Where is the typo located?

Quest description states:

"Obtain some Fey Leather using your Runic Shears on:
-a Minecraft Cow, Llama, Horse, Donkey, Mule, or
-a Mystical World Deer."

I found out that Rabbits also drop Fey Leather. Not sure if this was an omission or an oversight.

### Exact fix

Either Rabbits should be added to the quest description, or the Runic Shears should not work on Rabbits.

**Comment by CovenantCreamer** [comment]
Same goes for pigs!
