### ISSUE TITLE
Crafting CPUs used in Ultimate Crafting Table Recepies Leaves the Base Crafting CPU Behind

### ISSUE THREAD

**Issue by NickZumb** [Divine-Journey-2/Divine-Journey-2#65]
**Modpack version:**
Beta 0.1

**Description:**
Crafting the automation interface leaves the base Crafting CPUs behind

**Steps to reproduce:**
1. Craft a Automation Interface using a automation interface over an ultimate crafting table
2. The Crafting CPUs will be still be in the Ultimate Crafting Table

**Expected behavior:**
All components of the recipe and will be consumed

**Screenshots:**
![image](https://user-images.githubusercontent.com/87913921/128618858-9d7d8047-da12-401e-bf12-d435c67eced3.png)

**Addition Information**
I'm pretty sure this makes it impossible to autocraft the automation interface.

**Comment by JohanniklasLp** [comment]
There's a similar problem with the ultimate crafting table recipe
![grafik](https://user-images.githubusercontent.com/57828910/138195445-10fb4f82-d32f-4a90-99cf-69eec21b15d2.png)
