### ISSUE TITLE
to make agricraft friendlier

### ISSUE THREAD

**Issue by swear01** [Divine-Journey-2/Divine-Journey-2#658]
### Mod Name

Wasaila curseforge link:  https://www.curseforge.com/minecraft/mc-mods/wasaila

### Reasons why this should be added

After I set up my own Agricraft 10/10/10 automation, I find out that it's hard to check if seeds has mutated or not.
Magnifying Glass is really tricky since it only send message to chat without any highlight.

After installing checking seeds' statues is much easier.

### Additional context

It's such a tiny mod. So I think no mod conflict would be create.
An the mod has over 100k download, so It should be satable.

**Comment by Atricos** [comment]
Added in 2.14.0.
