### ISSUE TITLE
Box of sealed evil in offhand uses main hand item

### ISSUE THREAD

**Issue by Katsuro27** [Divine-Journey-2/Divine-Journey-2#662]
### Modpack version

2.13.0

### Description

I think it is more or a Bewitchment bug than a Divine Journey 2 bug but when you use a box of sealed evil in your offhand the item in your main hand will be consumed instead ... maybe one could add a tooltip or so as a warning?

### Steps to reproduce

1. Get box of sealed evil from bewitchment
2. Put it in your offhand
3. Switch to any other item with your main hand
4. Right click

### Expected behavior

Consume the offhand item (idk if this is possible here)

**Comment by WaitingIdly** [comment]
the only way you can obtain this item is via trading with demons. as the ability to trade with demons will be removed and was never intended, there is no need for anything to address this (it will be unobtainable)
