### ISSUE TITLE
Textury po zapnutí hry

### ISSUE THREAD

**Issue by Tatakuc** [Divine-Journey-2/Divine-Journey-2#663]
### Modpack version

2.14.0

### Description

Špatné textury po startu hry.
![Textury](https://user-images.githubusercontent.com/76770095/166194520-ae304f8e-b4d1-41d7-b286-9b902d1e2234.png)
 

### Steps to reproduce

Nevím

### Expected behavior

Nevím

**Comment by Tatakuc** [comment]
Toto je úvodní stránka.

**Comment by Tatakuc** [comment]
Vyřešeno

**Comment by Atricos** [comment]
Fixed in 2.14.1.

**Comment by Tatakuc** [comment]
Thanks mr. Atricos
______________________________________________________________
> Od: "Atricos" ***@***.***>
> Komu: "Divine-Journey-2/Divine-Journey-2" ***@***.***>
> Datum: 02.05.2022 12:18
> Předmět: Re: [Divine-Journey-2/Divine-Journey-2] Textury po zapnutí hry (Issue #663)
>
 
Fixed in 2.14.1.
