### ISSUE TITLE
Content Tweaker Items and Main Screen

### ISSUE THREAD

**Issue by i-eat-tacos** [Divine-Journey-2/Divine-Journey-2#664]
### Modpack version

2.14.0

### Description

All Content Tweaker Item and the Main Screen is replaced with the default unrecognised minecraft purple/black item

### Steps to reproduce

Just open the game on 2.14.0

### Expected behavior

It should show the proper item and the main screen should have the initial DJ2 design as it doesn't say Singleplayer, Multiplayer etc.

**Comment by Atricos** [comment]
Fixed in 2.14.1.
