### ISSUE TITLE
Inventory doesn't update

### ISSUE THREAD

**Issue by Ricky2148** [Divine-Journey-2/Divine-Journey-2#666]
### Modpack version

2.14.1

### Description

For some reason, if i pick up an item or move stuff in your inventory it doesn't update and it'll just use whatever was there previously. It only is able to be changed when you open a different inventory, backpack/chests

### Steps to reproduce

Not sure

### Expected behavior

The inventory being changed as i change it.

### Additional context

I am playing on a server and i have a few mods externally added, but it's all client side visual mods like dynamic surroundings, optifine, and item physic lite

**Comment by Ringedtech203** [comment]
A: It's an inventory desync. Relog. Commonly caused by: A poor internet connection, the inventory sorting keybind, or trying to use the Roots Open Staff key without a Staff in hand.
