### ISSUE TITLE
Infinite nausea for aparent no reason

### ISSUE THREAD

**Issue by missigno16** [Divine-Journey-2/Divine-Journey-2#669]
### Modpack version

2,14,2

### Description

Hi so i just update my pack to the latest version, and for some odd reason, i have infinite nausea effect, the time changes between 3 and 4 seconds, and doen't go away, i tried with milk aswell.

I tried removing all my equipment and it didn't work either, however i traveled to the nether and the nausea dissapeared but i came back to the overworld and it came back, so i don't know if it has something to do with my base (cause it's huge and sometimes i forget with i added) but i was playing on 2.10.0 today and when i left the game to update the pack i didn't have nausea

![image](https://user-images.githubusercontent.com/65515531/168707472-7aa0c4d6-2d11-47fe-9378-eea93ba1c383.png)

Btw my Demon Will Crystal Cluster doesn't split in the other colored crystals, that also happens but it's not important right now

### Steps to reproduce

Just opened my world and it happened :)

### Expected behavior

The nausea shouldn't be there

### Additional context

Right now i'm on the thaumacraft chapter (19), i really i'm stuck and have no idea how to advance, and the nausea problem isn't making it easier

**Comment by luciscout** [comment]
It sounds like your blood network is out of LP, as this will cause you to have the nausea effect. Please confirm that this is the case

**Comment by missigno16** [comment]
> It sounds like your blood network is out of LP, as this will cause you to have the nausea effect. Please confirm that this is the case

Thank you sorry for the stupid problem, anyway time to erase this post
