### ISSUE TITLE
pentacle recipe differ between infusion and auto infusion

### ISSUE THREAD

**Issue by swear01** [Divine-Journey-2/Divine-Journey-2#674]
### Modpack version

2.14.2

### Description

infusion one use stone ichor
auto infusion one use witches' stonebrew
![image](https://user-images.githubusercontent.com/49574926/170812289-2f7354f2-6f8a-4b6b-8ee3-a7007df010d7.png)
![image](https://user-images.githubusercontent.com/49574926/170812291-3dc110f7-affe-4633-b4e0-a5df24179cf5.png)

### Steps to reproduce

1. Open DJ2
2. look at JEI's pentacle recipe

### Expected behavior

both should use the same ingredient

**Comment by WaitingIdly** [comment]
those are the same recipes, its just using a contenttweaker item to prevent the input bus from being filled with empty jars
