### ISSUE TITLE
Heavy world lag and server crashes

### ISSUE THREAD

**Issue by Stevexeu** [Divine-Journey-2/Divine-Journey-2#676]
### Modpack version

1.14.2

### Java version

1.12.2

### RAM Allocated

12GB server - 8GB personal

### Description

Server keeps crashing and we have this in our crash logg:

05.06 00:26:59 [Server] Server thread/ Can't keep up! Did the system time change, or is the server overloaded? Running 11076ms behind, skipping 221 tick(s)
05.06 00:27:05 [Server] Server thread/ Thaumcraft loaded a new chunk [-1953, 2479] in dimension 0 (overworld) while populating chunk [-1953, 2480], causing cascading worldgen lag.
05.06 00:27:05 [Server] Server thread/ Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
05.06 00:27:06 [Server] Server thread/ Ruins Mod loaded a new chunk [-1954, 2485] in dimension 0 (overworld) while populating chunk [-1953, 2485], causing cascading worldgen lag.
05.06 00:27:06 [Server] Server thread/ Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
05.06 00:27:06 [Server] Server thread/ Ruins Mod loaded a new chunk [-1955, 2485] in dimension 0 (overworld) while populating chunk [-1953, 2485], causing cascading worldgen lag.
05.06 00:27:06 [Server] Server thread/ Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
05.06 00:27:07 [Server] Server thread/ Can't keep up! Did the system time change, or is the server overloaded? Running 3488ms behind, skipping 69 tick(s)
05.06 00:27:14 [Server] Server thread/ Mystical World loaded a new chunk [-1954, 2478] in dimension 0 (overworld) while populating chunk [-1954, 2479], causing cascading worldgen lag.
05.06 00:27:14 [Server] Server thread/ Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
05.06 00:27:15 [Server] Server thread/ Thaumcraft loaded a new chunk [-1955, 2484] in dimension 0 (overworld) while populating chunk [-1954, 2484], causing cascading worldgen lag.

Can someone please help us?
We reinstalled multiple times, switches hosts, and still have heavy block lagg and server issues 

### When did the crash happen?

Every 2/3 hours

### Steps to reproduce

go in the game
Play
Experience

### Minecraft crash report

05.06 00:26:59 [Server] Server thread/ Can't keep up! Did the system time change, or is the server overloaded? Running 11076ms behind, skipping 221 tick(s)
05.06 00:27:05 [Server] Server thread/ Thaumcraft loaded a new chunk [-1953, 2479] in dimension 0 (overworld) while populating chunk [-1953, 2480], causing cascading worldgen lag.
05.06 00:27:05 [Server] Server thread/ Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
05.06 00:27:06 [Server] Server thread/ Ruins Mod loaded a new chunk [-1954, 2485] in dimension 0 (overworld) while populating chunk [-1953, 2485], causing cascading worldgen lag.
05.06 00:27:06 [Server] Server thread/ Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
05.06 00:27:06 [Server] Server thread/ Ruins Mod loaded a new chunk [-1955, 2485] in dimension 0 (overworld) while populating chunk [-1953, 2485], causing cascading worldgen lag.
05.06 00:27:06 [Server] Server thread/ Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
05.06 00:27:07 [Server] Server thread/ Can't keep up! Did the system time change, or is the server overloaded? Running 3488ms behind, skipping 69 tick(s)
05.06 00:27:14 [Server] Server thread/ Mystical World loaded a new chunk [-1954, 2478] in dimension 0 (overworld) while populating chunk [-1954, 2479], causing cascading worldgen lag.
05.06 00:27:14 [Server] Server thread/ Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
05.06 00:27:15 [Server] Server thread/ Thaumcraft loaded a new chunk [-1955, 2484] in dimension 0 (overworld) while populating chunk [-1954, 2484], causing cascading worldgen lag.

**Comment by WaitingIdly** [comment]
that is not a crash report.
your steps listed for reproduction do not result in a reproduction, and are so vague as to be worthless to include.
cascading worldgen is not a resolvable issue (literally, its just "a thing generated crossed a chunk border"). from the times listed, it happens as someone is exploring.
your crash is likely the server watchdog, for which you should set `max-tick-time` to `-1` in `server.properties`.

**Comment by WaitingIdly** [comment]
whoops
