### ISSUE TITLE
invetori bug

### ISSUE THREAD

**Issue by MeyerRage** [Divine-Journey-2/Divine-Journey-2#677]
### Modpack version

2,14,2

### Description

i need help i play on singleplayer server and my Inventory Bug  is keep  bugging and can play the game like this and i hav a video  to show what is worng  can you help ?

### Steps to reproduce

invetori bug

### Expected behavior

i can play nomale 

### Additional context

https://youtu.be/_gSAmWgozbg

**Comment by KleinGrrmpf** [comment]
Just happens sometimes, apparently when you often when you use your "Open Roots Spells" Keybind without a staff in hand. Relog and it's fixed.

**Comment by MeyerRage** [comment]
but is there a way to fix so dont need to relog ?

**Comment by KleinGrrmpf** [comment]
No

**Comment by PantACRO4life** [comment]
This has nothing to do with root, might interfere but this is an inventory tweaker issue and as far as I know the issue is there since forever. Just relog.
