### ISSUE TITLE
Witches Oven voids empty jars if the secondary output is full

### ISSUE THREAD

**Issue by Sbmhawk** [Divine-Journey-2/Divine-Journey-2#679]
### Modpack version

2.1.4.2

### Description

When the secondary output of the witches oven is full, and you feed it more jars/saplings, when it would normally make another oil/not make oil as it is full, it voids the jar it would use to make a new oil.

### Steps to reproduce

Fill witches oven with saplings/coal/jars
wait for secondary output to fill
see jars being voided, yet no more oil is being produced.

### Expected behavior

For it to not void jars

### Additional context

I know its not a problem with the pack, but with the mod, but who knows, maybe itll get fixed in that one DJ2 addon mod

**Comment by WaitingIdly** [comment]
this was resolved when DJ2 addons was updated in #756
