### ISSUE TITLE
So the end dimension just broke

### ISSUE THREAD

**Issue by missigno16** [Divine-Journey-2/Divine-Journey-2#681]
### Modpack version

2,14,2

### Description

So i'm in the bewitchment chapter and for a recipe i needed dragon scales, so since i didn't have any i went to the end to kill the dragon again, and then i noticed something was wrong, cause even tho i killed the dragon way before, the exit portal wasn't there, but all the end crystals were, also i spawned in a box inside the end stone but i wasn't open anywere, also the portals to the far end dissapeared, so i cheated a bit and tried spawning the dragon with commands, but is just he iddle animation of the dragon without moving, and WAILA says it's an "unknown" creature.
I got completely trapped, since apparently i can't die to the void, so i cheated again and used the waypoints to teleport, and since i didn't want to search for the overworld waypoints, i teleporte to the aether, but my surprise was that, my portal wasn't there either, so i had to search for the overworld waypoints, and when i entered the aether portal from there, it suddenly reappeared in the aether, as if nothing had happened.
Now maybe i screwed up, since i cheated again and used creative mod to try and break the end portal to rebuild it again, i guess you can imagen what happened, so now i can't go to the end unless i use the waypoints, how do i fix this freaking mess

### Steps to reproduce

Maybe it was when i was updating the modpack, but basically after a really long time, i just entered the end portal.

### Expected behavior

Well, i killed the dragon a really long time ago, and all the portals should be there, the exit and far end portals

### Additional context

So i went to the DJ2 discord asking for help when i was stuck in the thaumcraft chapter, and it turns out i was using the wrong files, so after changing the files and porting my world, i was able to continue, but since i changed the files, i haven't entered the end, so maybe that's when it happened.

**Comment by WaitingIdly** [comment]
this seems like you improperly migrated from earlier versions and only copied over the overworld, thus resetting your other dimensions.
the end portal not working is obvious - you have to place the portals from the center of the would-be portal, so they are all facing the same way. 

but, this doesn't give me even a hint of how to reproduce your error, and it seems highly likely to be due to some file change you did. please clarify your issue, or join discord and ask for help in the `#tech-support` channel.

**Comment by missigno16** [comment]
> this seems like you improperly migrated from earlier versions and only copied over the overworld, thus resetting your other dimensions. the end portal not working is obvious - you have to place the portals from the center of the would-be portal, so they are all facing the same way.
> 
> but, this doesn't give me even a hint of how to reproduce your error, and it seems highly likely to be due to some file change you did. please clarify your issue, or join discord and ask for help in the `#tech-support` channel.

Well i did not manage to fix the end on itself, but i managed to place the portals, and in the emptiness dimension i found a rift to the end, so i guess i can use that aswell, thank you very much
