### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by 1746813083** [Divine-Journey-2/Divine-Journey-2#682]
### Modpack version

error report

### Description

It has been working for about two months until today's emergency

### Steps to reproduce

It has been working for about two months until today's emergency

### Expected behavior

It has been working for about two months until today's emergency

### Additional context

It has been working for about two months until today's emergenc
[crash-2022-06-17_15.46.29-server.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/8925696/crash-2022-06-17_15.46.29-server.txt)
y

**Comment by KleinGrrmpf** [comment]
Do you want to tell us at all what happened, so that people can try to figure out how to fix it? The fields are there for a reason...

**Comment by Preta-Crowz** [comment]
It looks just your map is too heavy and watchdog crashed server.
This happens when TPS is under 0.016 (60s/tick).
If you want to continue with that world, then change `max-tick-time` on server.properties to `-1`.
You should fix laggy things after this.
