### ISSUE TITLE
 Server does not start

### ISSUE THREAD

**Issue by Furryks** [Divine-Journey-2/Divine-Journey-2#684]
### Modpack version

2.14.2

### Java version

1.8.0_333

### RAM Allocated

16

### Description

I downloaded the archive with the server t moved it to a folder called "1" then went to this folder and started the server "run.bat" but not what was installed the command console opens then after a second 2-3 closes, everything.

### When did the crash happen?

just happend

### Steps to reproduce

The server does not start at all

### Minecraft crash report

There is not even a "crash report" !!!!

**Comment by Ringedtech203** [comment]
If you don't have a crash report upload the normal server log

**Comment by Furryks** [comment]
@Ringedtech203 The log server cannot appear because the server does not have time to create it because the command console closes in seconds.

**Comment by Furryks** [comment]
@Ringedtech203 The log server cannot appear because the server does not have time to create it because the command console closes in seconds.

**Comment by Furryks** [comment]
I didn't want to close the question !!!!

**Comment by Furryks** [comment]
I found and fixed the error !!! It's good when you have your head on your shoulders, who is very interested in what the problem was, the problem was very simple, I had another Java installed, I deleted it and everything worked)))

Я знайшов та виправив помилку!!! гарно коли в тебе своя голова на плечах, кому дуже цікаво що за проблема була, проблема була дуже проста в мене було встановлена ще якась Java я її видалив та все запрацювало)))

**Comment by KleinGrrmpf** [comment]
You can always reopen issues ;)
