### ISSUE TITLE
Uncrafting Table Dupe

### ISSUE THREAD

**Issue by JetMage28** [Divine-Journey-2/Divine-Journey-2#690]
### Modpack version

2.14.2

### Description

one can easilly use the restricted uncrafting table to duplicate items

### Steps to reproduce

1. join world 
2. get uncrafting table and item with compressed/decompressed form (ex. diamonds with nuggets)
3. place most dense form in far left slot
4. select decondensing recipe
5. place item in decondensing recipe in center section of GUI
6. extract item from far right slot 
7. repeat steps 3-6 until you have the desired amount of your resource

### Expected behavior

this should not happen

### Additional context

![image](https://user-images.githubusercontent.com/108558330/176981148-6e30dc75-1619-45a6-bc0c-15fbe9e4ca1d.png)

attempting to add an image of procedure for visual assistance

**Comment by WaitingIdly** [comment]
the uncrafting table is unobtainable

**Comment by Sbmhawk** [comment]
You can find them in hollow hills very rarely, I assume that's what happened

**Comment by JetMage28** [comment]
> the uncrafting table is unobtainable

I obtained it. I looted it from a hollow hill

**Comment by WaitingIdly** [comment]
Apologies, i was incorrect about it being unobtainable. Rather, its function is disabled in the config - heres the direct line where its disabled. If you can use it, the pack must have downloaded incorrectly, and you should reinstall, as there are likely other files missing or incorrect.

https://github.com/Divine-Journey-2/Divine-Journey-2/blob/4849280ff3676d9990bf5506f1c1187b513f69d6/overrides/config/twilightforest.cfg#L24

**Comment by JetMage28** [comment]
> Apologies, i was incorrect about it being unobtainable. Rather, its function is disabled in the config - heres the direct line where its disabled. If you can use it, the pack must have downloaded incorrectly, and you should reinstall, as there are likely other files missing or incorrect.
> 
> https://github.com/Divine-Journey-2/Divine-Journey-2/blob/4849280ff3676d9990bf5506f1c1187b513f69d6/overrides/config/twilightforest.cfg#L24

It’s not that I’m using it. It’s that I’m inputting an item, it’s nugget form, and extracting the original item, and the nuggets are getting duped

**Comment by Preta-Crowz** [comment]
confirmed it happens when there's more than 2 items on center slots (1 will remove item and 2 will not dupe)
confirmed it works on other slot on center 9 slots

**Comment by Preta-Crowz** [comment]
confirmed it happens when Item has other recipe than compressing one

**Comment by Preta-Crowz** [comment]
confirmed it works on non-compressing recipe
