### ISSUE TITLE
Manifest file has wrong modpack verison

### ISSUE THREAD

**Issue by Campionnn** [Divine-Journey-2/Divine-Journey-2#691]
### Modpack version

2.15.0

### Description

The manifest file says the version is 2.14.1 even though the version is 2.15.0

### Steps to reproduce

Open manifest.json and go to "version"

### Expected behavior

Should say 2.15.0 instead of 2.14.1

**Comment by WaitingIdly** [comment]
the release of 2.16.0 fixed this
