### ISSUE TITLE
Some crafting units returns from crafting Ultimate Crafting Table

### ISSUE THREAD

**Issue by Preta-Crowz** [Divine-Journey-2/Divine-Journey-2#693]
### Modpack version

2.15.0

### Description

might same issue with #687, but other recipe
![After craft Ultimate Crafting Table, remains 4 Crafting Units](https://user-images.githubusercontent.com/16697820/177039622-79da1c59-86cc-4ec8-a710-a8387fa5419f.png)

### Steps to reproduce

1. Craft Ultimate Crafting Table
2. Some Crafting Units are remain

### Expected behavior

They all returns or do not return anything

**Comment by WaitingIdly** [comment]
resolved in ae49be5407865a4fa886819f9aaf54e9509e5409, released as part of 2.20.0
