### ISSUE TITLE
Salt Ore dropping the wrong kind of Salt

### ISSUE THREAD

**Issue by Shattered2909** [Divine-Journey-2/Divine-Journey-2#694]
### Modpack version

2.14.1

### Description

Bewitchment Salt Ore (which was made craftable in this update) is meant to just drop Salt which it does when processed with machines but breaking it will drop Ritualistic Salt, allowing players to skip a recipe, this Salt is also not usable for the Warp Ward Flask in the Vethea Dimension.

### Steps to reproduce

Make Salt Ore with Vethea Blocks, break the Block, get Ritualistic Salt

### Expected behavior

The Ore should  drop normal Salt

### Additional context

blah blah

**Comment by Atricos** [comment]
Bewitchment Salt Ore is unobtainable.

**Comment by luciscout** [comment]
Salt ore is obtainable through a crafttweaker craft
