### ISSUE TITLE
Roots (and LagGoggles) crash when using the spectator mode of Roots' Augment spell

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#698]
### Modpack version

2.15.0

### Java version

1.8.0_333

### RAM Allocated

10GB/16GB

### Description

I selected the Augment Spell (which has the spectator augment) from my spell library and used it. I got into spectator mode, but when I exited spectator mode again, the game crashed and sent me back to the main menu. The screen informed me that Roots and LagGoggles were responsible for the crash. I rejoined the server and used the spell again. This time, I crashed immediately and the screen said that only Roots was responsible for the crash. After rejoining the server again, I was in spectator mode however. When the spell ended and I was set into survival mode again, the game crashed yet again saying that Roots and LagGoggles were responsible. From this point on, the game crashed every time I used the spell and when the spell ran out as described above.

### When did the crash happen?

When using the Augment Spell that has been augmented with the spectator augment.

### Steps to reproduce

1. Aquire a Roots Staff, aquire the Augment Spell and upgrade it with the Light Drifter Augment, aquire a Herb Pouch and put all the necessary herbs into it.
2. Use the Augment Spell in the Roots Staff
3. If it doesn't crash immediately, wait for the spectator timer to run out and observe the crash screen.

### Minecraft crash report

[crash-2022-07-09_01.45.15-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9075503/crash-2022-07-09_01.45.15-client.txt)
This one is the crash when entering spectator mode (where the game says that only Roots is responsible)

[crash-2022-07-09_01.46.03-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9075504/crash-2022-07-09_01.46.03-client.txt)
This one is the crash when exiting spectator mode (where the game says that Roots and LagGoggles are responsible)

**Comment by WaitingIdly** [comment]
this was resolved in 2.16.0
