### ISSUE TITLE
 Typo in Facilitate and Capacitate

### ISSUE THREAD

**Issue by PotatoEter** [Divine-Journey-2/Divine-Journey-2#700]
### Modpack version

2.15.0

### Where is the typo located?

In the 4th Chapter of the quest Facilitate and Capacitate the description of the quest.

### Exact fix

The description of the quest says "Craft an HV Capacitator." rather than "Craft an HV Capacitator!" It should have an exclamation mark instead of a period like the other Capacitor quests. Thanks, <3 (The pictures show the HV quest compared to the previous 2)![HV](https://user-images.githubusercontent.com/100160829/178400070-169c249c-b2de-4cb1-bfcd-ce9250507ecb.png)
![LV](https://user-images.githubusercontent.com/100160829/178400071-20e1d19f-91ac-4cf6-a065-ea38cdd86319.png)
![MV](https://user-images.githubusercontent.com/100160829/178400072-5b66d2da-5a47-41f5-9a53-868707a292fb.png)

**Comment by ClosedCosine638** [comment]
what a gamebreaking bug!

**Comment by Ringedtech203** [comment]
That is very alarming!

**Comment by PotatoEter** [comment]
> 

Honestly absolutely cannot stay in the game. SMH can't believe he let this pass, he must be so thankful I caught this one...
