### ISSUE TITLE
Roots 3 Advancement

### ISSUE THREAD

**Issue by warriordubs** [Divine-Journey-2/Divine-Journey-2#701]
### Modpack version

2.15.0

### Description

The Roots 3 Advancement: 'All the Mod(ifier)s 4' is broken. Applying the bafflecap modifier using an imposer does not register for the advancement. I nooby about the bug and he said that the advancement has 'baffle_cap_mushroom' where it should be something like 'baffle_cap'

### Steps to reproduce

Open the game / get into a new world / break grass until you get wildroot / create a staff and imbue it with 2 spells / use an imposer and put a roots staff in the imposer / use a roots knife to enter the staff menu / put one of each plant from roots into the modifiers for both spells

### Expected behavior

The expected behavior is that, after applying all 11 modifiers, the player gets the Roots 3 advancement: 'All the Mod(ifier)s 4'

**Comment by ByThePowerOfScience** [comment]
I'm the active maintainer of the Roots 1.12 distribution, so I'll fix the bug in the next Roots release.  Thanks for letting us know!
