### ISSUE TITLE
Config of Extra Utilities 2 can`t be correctly applied

### ISSUE THREAD

**Issue by YeMengke** [Divine-Journey-2/Divine-Journey-2#712]
### Modpack version

2.15.0

### Description

Mills` config for GP can`t be correctly applied,it is the default configuration.it means i can only get 500GP from dragon egg mill

### Steps to reproduce

1.use PCL2 install modpack
2.start game

### Expected behavior

it should be 10000GP from dragon egg mill.

**Comment by WaitingIdly** [comment]
this is correct - it is a base of 10000 GP, and then reduced by the progressive efficiency loss (something we cannot change) to 1300.

**Comment by YeMengke** [comment]
> this is correct - it is a base of 10000 GP, and then reduced by the progressive efficiency loss (something we cannot change) to 1300.

thank you for your reply.I know that it will be 1300GP,but in fact,it is a base of 500 GP in my game,i don`t know what`s wrong with it.hoping for a solution.Not only the dragon egg,but also all mills can`t get a correct GP in expect
![dragon egg](https://user-images.githubusercontent.com/111678795/185782787-0828a4e4-fa1c-45fc-93f9-e21043112f5a.png)
![mills](https://user-images.githubusercontent.com/111678795/185782791-c994158d-13e8-4e51-a939-b33c7f99e847.png)
![versions](https://user-images.githubusercontent.com/111678795/185782793-30110cc6-4162-4b62-83d8-aae507ad73e7.png)
.

**Comment by WaitingIdly** [comment]
hmm - could you navigate to `config/tmel.cfg` and confirm that lines 221 to 231 match this:
```cfg
    "grid power multipliers" {
        D:"Creative Mill"=10000.0
        D:"Dragon Egg Mill"=20.0
        D:"Fire Mill"=2.0
        D:"Lava Mill"=2.0
        D:"Lunar Panel"=1.0
        D:"Manual Mill"=1.0
        D:"Solar Panel"=1.0
        D:"Water Mill"=0.25
        D:"Wind Mill"=2.0
    }
```

**Comment by YeMengke** [comment]
> hmm - could you navigate to `config/tmel.cfg` and confirm that lines 221 to 231 match this:
> 
> ```haproxy-config
>     "grid power multipliers" {
>         D:"Creative Mill"=10000.0
>         D:"Dragon Egg Mill"=20.0
>         D:"Fire Mill"=2.0
>         D:"Lava Mill"=2.0
>         D:"Lunar Panel"=1.0
>         D:"Manual Mill"=1.0
>         D:"Solar Panel"=1.0
>         D:"Water Mill"=0.25
>         D:"Wind Mill"=2.0
>     }
> ```

thank you for your help,I think it may be the translation makes the config can`t be correctly applied,after changing the config,it can be that it should be
![1](https://user-images.githubusercontent.com/111678795/185785852-f67f351c-c4cf-4ae3-b04f-4bf55ce75a0d.png)
.
