### ISSUE TITLE
The configuration file of extra utilities 2 is invalid in the game

### ISSUE THREAD

**Issue by Langran66** [Divine-Journey-2/Divine-Journey-2#715]
### Modpack version

2.15.0

### Description

When I tried to view **extrautils2.cfg**, I found that the author had allowed non creative players to destroy and change creative items, but I can't use the creation drum in the game, so I think the configuration file is not used correctly

### Steps to reproduce

open the game
get the item creative drum
using a bucket of lava to right click the creative drum.

### Expected behavior

Created items can be destroyed and configured

**Comment by WaitingIdly** [comment]
the creative drum does not respond to this setting. the questbook has been changed to reflect this. cant change this on the preferred end, but i consider this action enough to resolve this issue.
