### ISSUE TITLE
An error in the recipe of Reservoir (creative) from Thermal Expansion

### ISSUE THREAD

**Issue by Langran66** [Divine-Journey-2/Divine-Journey-2#716]
### Modpack version

2.15.0

### Description

![QQ截图20220823224938](https://user-images.githubusercontent.com/109011771/186189722-66cb8849-2e70-4102-b575-62c85eb365de.png)

It seems that we only need the most basic tanks to participate in the recipe.XD

### Steps to reproduce

open the game
open the jei~

### Expected behavior

I don't really want to fix it. Cheap recipe makes me happy. But I also hope the DJ2 can be perfect. Fix it!

**Comment by King65868** [comment]
Requires creative tank still, just shows the wrong tank
