### ISSUE TITLE
Sequential Fabricator can use empty syringe to craft the Peace Essence

### ISSUE THREAD

**Issue by Langran66** [Divine-Journey-2/Divine-Journey-2#717]
### Modpack version

2.15.0

### Description

When I prepared 10 sets of materials of peaceful essence for crafting, I tried to use Sequential Fabricator instead of AE2, and then found this bug.This makes my work seem worthless. Please fix it.

### Steps to reproduce

![QQ截图20220823225448](https://user-images.githubusercontent.com/109011771/186192316-672ff77a-b65c-450f-a497-3abee408bc2f.png)
![QQ截图20220823225458](https://user-images.githubusercontent.com/109011771/186192352-68aba00c-1cab-4f91-849e-0b7373d6c367.png)

### Expected behavior

It should identify the internal NBT and only craft it when appropriate.

**Comment by Preta-Crowz** [comment]
Confirmed this while resetting my id parts
They don't check NBT and it may work too
