### ISSUE TITLE
Rainbow tablet cannot be crafting correctly in vanilla infusion altar

### ISSUE THREAD

**Issue by Langran66** [Divine-Journey-2/Divine-Journey-2#718]
### Modpack version

2.15.0

### Description

![QQ截图20220823230636](https://user-images.githubusercontent.com/109011771/186197534-ff6eac89-a1b3-483e-9fb5-bfd3384506df.png)

I think the vanilla Infusion Altar is great, because it can reduce the use of the source material by half, so I have never made the auto infusion matrix. However, when upgrading the recipe of rainbow tablet, I found that since the base in the middle can only accommodate a single item, only one rainbow tablet will be crafting instead of 32.

### Steps to reproduce

1.open the game
2.build a Infusion Altar
3.craft the rainbow tablet
4.find only one rainbow in the middle base.

### Expected behavior

Maybe we should delete this recipe.

**Comment by ByThePowerOfScience** [comment]
Fixed in DJ2Addons 1.2.1
