### ISSUE TITLE
Remove and Hide the "Requious Frakto" items from JEI as they are admin tools for recipe creation and have no recipe

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#723]
### Describe the feature

Remove and Hide the "Requious Frakto" items from JEI as they are admin tools for recipe creation and have no recipe.

### Reasons why this should be added

Unclutters JEI

### Describe alternatives you've considered

Leave it in

### Additional context

![grafik](https://user-images.githubusercontent.com/50833808/187543059-6b0571ea-2c0b-4248-9086-911fca917813.png)

**Comment by WaitingIdly** [comment]
should have been resolved in #756
