### ISSUE TITLE
Remove/Edit the note about Aerogel in "You're hot then you're cold" (Chapter 8, Quest #1095)

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#725]
### Describe the feature

Remove/Edit the note about Aerogel in "You're hot then you're cold" (Chapter 8, Quest #1095). This note is now (at least partly) obsolete because all lava is turned into Aerogel in the Aether eventually. 

### Reasons why this should be added

The newest update (2.16.0) has added a workaround for the bug described in the note.

### Describe alternatives you've considered

You could change the note to say that the mechanical user works the fastest because it behaves like a player and all lava is instantly turned into Aerogel instead of a little time later.

**Comment by King65868** [comment]
Will fix
