### ISSUE TITLE
Replace "Tartaric Forge" with Alchemy Tables as the Hellfire Forge is already mentioned

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#726]
### Modpack version

2.16.0

### Where is the typo located?

Chapter 18, Quest #39 "Pile on the Pylons"

### Exact fix

Should be "You'll need to heavily automate Blood Magic Reagents, Alchemy Tables, and Runes." instead of "You'll need to heavily automate Blood Magic Reagents, Tartaric Forges, and Runes."

**Comment by King65868** [comment]
Will fix
