### ISSUE TITLE
The compressed package has an error

### ISSUE THREAD

**Issue by luzeas** [Divine-Journey-2/Divine-Journey-2#727]
### Modpack version

2.16.0

### Description

The zip file downloaded from the website contained a large number of duplicate files, so it was impossible to unzip the zip and install the game properly.  All duplicate files have the same name, but all have different sizes and modification dates.  So, we don't know which file is the correct version.

### Steps to reproduce

Download the zip from the CurseForge website and install the game on Windows using a launcher other than FTB and the CurseForge APP, or unzip the zip directly to your computer.And then you can understand what duplicate files are

### Expected behavior

Repack the correct game files and upload them to the website as soon as possible

**Comment by luzeas** [comment]
Most people are using Windows, so please don't package your games in Linux！！！！

**Comment by Preta-Crowz** [comment]
checked downloaded file, no problem confirmed.

**Comment by luzeas** [comment]
I'm sure there's something wrong with the zip pack, and several of my friends are having the same problem

**Comment by Preta-Crowz** [comment]
confirmed some duplicated files and their name are exactly same.
It might not os problem.

**Comment by luzeas** [comment]
> confirmed some duplicated files and their name are exactly same. It might not os problem.
Only Linux is case sensitive for file names

**Comment by KleinGrrmpf** [comment]
Can confirm, I also had duplicate files when extracting. But I overwrote all of them and it worked just fine. I have no idea how there could be two files with the exact same name in the same location...

**Comment by luzeas** [comment]
> 可以确认，我解压时也有重复文件。但我覆盖了所有这些，它工作得很好。我不知道如何在同一位置存在两个具有完全相同名称的文件...

Overwriting duplicate files does solve the problem,but I'm not sure which file is suitable for version 2.16.
On the other hand, if you unzip the package on Linux, none of the files will be counted as duplicates,because the name of the folder in which they are located varies only in letter case,like DivineRGP and divinerpg.These are completely different folders in Linux, but they're exactly the same in Windows.
So I suspect the author made the compressed file in Linux

**Comment by WaitingIdly** [comment]
with the release of 2.17.0, this shouldnt be the case
