### ISSUE TITLE
Renamed vis crystals not accepted by Distillery

### ISSUE THREAD

**Issue by HardeQ** [Divine-Journey-2/Divine-Journey-2#732]
### Modpack version

2.16.0

### Description

Distillery doesn't craft Fiery Unguent when one of the vis crystals are renamed, thus making the AE2 automation impossible. Tried renaming it with inscriber with name press and anvil, none worked.

### Steps to reproduce

1. Rename Ignis Vis Crystal to anything.
2. Insert the renamed vis crystal, not renamed vis crystal and other ingredients for Fiery Unguent to Bewitchment's Distillery.
3. Insert fuel in Distillery.
4. The Distillery doesn't begin crafting, if you replace the renamed ignis crystal with not renamed one, it will begin crafting.

### Expected behavior

Distillery should be able to recognize renamed vis crystals as their not yet renamed counterpart.

### Additional context

https://youtu.be/PtjihK3yY2Y

**Comment by Preta-Crowz** [comment]
They aren't accept renamed item anymore because their nbt is not same.

**Comment by HardeQ** [comment]
Do you maybe know the workaround this problem?

**Comment by King65868** [comment]
Nothing for now

**Comment by Preta-Crowz** [comment]
#728 seems fix about this problem
