### ISSUE TITLE
Enchantment Reallocator can move some enchant that can't applied on target item

### ISSUE THREAD

**Issue by Preta-Crowz** [Divine-Journey-2/Divine-Journey-2#734]
### Modpack version

2.15.0 (I know it's outdated but it doesn't seem reported)

### Description

Enchantment Reallocator can move some enchant that can't applied on target item like mending to soul reaper, vorpal and aftershock to primal cutter.

### Steps to reproduce

1. Prepare two tools.
 - They both should can be enchanted.
 - One should be enchanted and another one should not.
 - Enchanted tool should have enchant that can not be applied to another one.
![Well-prepared tool to reproduce this issue. Pickaxe has Unbreaking and Efficiency. Target tool is fishing rod.](https://user-images.githubusercontent.com/16697820/189240339-ac39e668-9929-48d9-9bd0-0581c3a91d6e.png)
2. Move enchant by using Enchantment Reallocator from Lightningcraft.
![UI of Enchantment Reallocator. Moving enchants to fishing rod, from pickaxe.](https://user-images.githubusercontent.com/16697820/189240432-f5b6fa28-9c83-4b5d-9435-44b83d11ba0f.png)
3. Enchant will moved without any restriction.
![Final result. Pickaxe is now unenchanted and fishing rod has every enchants from pickaxe. Included efficienty, which can not be applied to fishing rod.](https://user-images.githubusercontent.com/16697820/189240546-299a17d4-8e85-4cd0-85b3-57f57ff5752c.png)

### Expected behavior

Enchantments that can not be applied to target tool should not moved.

### Additional context

Last update of Lightningcraft was 2020.

**Comment by WaitingIdly** [comment]
"how did you solve this bug"
promoted to feature
