### ISSUE TITLE
Charging a world keep reverse to peacefull

### ISSUE THREAD

**Issue by MrReps** [Divine-Journey-2/Divine-Journey-2#735]
### Modpack version

2.16.0

### Description

Hello,
I've a problem, when i'm saving my map and reopening it my difficulty keep reverse to peacfull.

I've tried many solution : 
changing diffiiculty and locking it
Changing the nb before loading the map 

but none of this worked. Is there a fix ?

### Steps to reproduce

1 close the save in any difficulty mode
2 open the map again
3 see that you are in peaceful again....

### Expected behavior

loading with the last selected difficulty

**Comment by Preta-Crowz** [comment]
Are you on singleplayer? or server?

**Comment by MrReps** [comment]
Totaly forget to precise that. I'm on singleplayer

**Comment by WaitingIdly** [comment]
there is not enough information here to reproduce or diagnose the issue. it has been over two years now since the last message. if this issue reoccurs, create a new issue instead.
