### ISSUE TITLE
[Mod Req] Integrated NBT

### ISSUE THREAD

**Issue by Preta-Crowz** [Divine-Journey-2/Divine-Journey-2#738]
### Mod Name

[Integrated NBT](https://www.curseforge.com/minecraft/mc-mods/integrated-nbt)

### Reasons why this should be added

ID is very useful to do many automations from read nbt but get values from nbt is quite complex.
This addon makes users to get value from nbt easily.

**Comment by King65868** [comment]
Would be a nice mod to have
