### ISSUE TITLE
Drawer upgrades Dupe Glitch on Multiplayer

### ISSUE THREAD

**Issue by Xyilia** [Divine-Journey-2/Divine-Journey-2#743]
### Modpack version

2.16.0

### Description

There is an issue where a player can dupe drawers' upgrades but it only works on multiplayer

### Steps to reproduce

1. Open the modpack
2. Join a server 
3. Place a drawer with upgrades and access its' inventory
4. Get a second player to break the drawer while you're still accessing it
5. Remove the upgrades
6. Place down the drawer again and it will still have its' upgrades and you will have the duped ones in your inventory

### Expected behavior

The player should be kicked out of the drawer inventory preview when said drawer is broken

**Comment by Preta-Crowz** [comment]
If it really works, may work with automated breakers like auto-breaker can be used to reproduce this on singleplayer.

**Comment by Xyilia** [comment]
> If it really works, may work with automated breakers like auto-breaker can be used to reproduce this on singleplayer.

Apparently this does work using a block breaker too
