### ISSUE TITLE
2.16.0 server consistently crashing within 2 hours

### ISSUE THREAD

**Issue by JCDT37** [Divine-Journey-2/Divine-Journey-2#744]
### Modpack version

2.16.0

### Java version

1.8.0_341

### RAM Allocated

32 GB of 128 GB

### Description

The server pretty consistently crashes within 1 to 2 hours of being up, sometimes even crashing my entire pc.

### When did the crash happen?

There doesn't seem to be any trigger while playing it just kind of happens.

### Steps to reproduce

1. I boot the server
2. I enjoy the server for about an hour
3. Server crashes

### Minecraft crash report

[latest.log](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9611237/latest.log)
[debug.log](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9611239/debug.log)

**Comment by JCDT37** [comment]
I removed the ruins mod which help with server performance but I am still having crash issues.
[latest.log](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9611760/latest.log)
[debug.log](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9611761/debug.log)

**Comment by Preta-Crowz** [comment]
Is there no crash log created?

**Comment by luciscout** [comment]
None of the logs you have produced demonstrate a crash. Please proceed with a crash log that is generated to the crash-reports folder of the server. Also consider joining the discord server as this is easier to facilitate discussion

**Comment by JCDT37** [comment]
> Is there no crash log created?
nope, i cant find anything named crashs, crash-reports, or crash-logs.

**Comment by JCDT37** [comment]
[hs_err_pid11364.log](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9619003/hs_err_pid11364.log)
Is this a crash log? It was mixed in with the main server files. I thought that normally there was a folder for crash logs?

**Comment by Preta-Crowz** [comment]
> [hs_err_pid11364.log](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9619003/hs_err_pid11364.log) Is this a crash log? It was mixed in with the main server files. I thought that normally there was a folder for crash logs?

This is java error log. It generates when jvm itself was crashed.
So, most cases of generate this file means your java is corrupted or installed version has bug.
But sometime, it happens from memory error like failed to access page file, accessed non-exist address, etc.
You may need to find the problem by yourself because reproduce "same" bug on other pc is almost impossible.
One of useful try is change your java to other version or use other things like GraalVM.

**Comment by ByThePowerOfScience** [comment]
That's a log that means Java itself had an error unrelated to Minecraft. It
doesn't tell us much unfortunately.

**Comment by WaitingIdly** [comment]
it has been multiple versions since this point and over two years. the crash report provided was non-conclusive. if this issue occurs again, please create a new issue or reopen this with further information.
