### ISSUE TITLE
Sun crystals can't be picked up while in liquid sunshine

### ISSUE THREAD

**Issue by winco0811** [Divine-Journey-2/Divine-Journey-2#745]
### Modpack version

2.16.0

### Description

Last update added an option to fill sun crystals by dropping them into EnderIO Liquid Sunshine. While it does fill them the item is constantly being "changed" and, as such, can't be picked up manually or by machines until Sunshine is removed or Crystal is moved out of the Sunshine.

### Steps to reproduce

1. Get into a world
2. Place EnderIO Liquid Sunshine anywhere in the world
3. Drop unfilled (or filled) Sun Crystal into the Liquid Sunshine
4. Try to pick it back up while it's in the Liquid Sunshine

### Expected behavior

Sun crystal should fill up and be possible to pick up afterwards, even inside Liquid Sunshine.

**Comment by MrReps** [comment]
I can add that it can be use as a duplication bug, by putting a hopper under it !
