### ISSUE TITLE
Update the "How to automate Essentia" guide in the "THIS IS ESSENTIAL" quest (quest #1707, chapter 21)

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#748]
### Describe the feature

The guide in this quest is out of date, so I suggest updating it with all the features that make things easier and are now possible.

### Reasons why this should be added

As of 2.16.0, the Thaumic Energistics fork has been added to the pack. It allows partitioning of Essentia Storage Cells, priorities and more stuff that was previously not possible. The guide however still says that you can't do all that stuff, suggesting that you need more complicated setups. This is problematic for everyone who is not aware that these things are possible. All that complicated subnetwork talk can be very confusing for people not as well versed with AE2 and is no longer needed anyway. 

### Describe alternatives you've considered

You could even remove the quest completely because the setup is trivial now (partition each storage cell to one type of essentia and then just input from all the smelteries), but this might not be obvious for less experienced players.

**Comment by WaitingIdly** [comment]
already done in #719
