### ISSUE TITLE
AE2 Glass Cable Texture Glitching

### ISSUE THREAD

**Issue by MagnesiumSail** [Divine-Journey-2/Divine-Journey-2#750]
### Modpack version

2.16.0

### Description

AE2 Glass Cable Texture Glitched.
![2022-10-04_09 10 15](https://user-images.githubusercontent.com/91155989/193859242-3df1adb9-6ea3-4770-be47-4329b149522b.png)
When the cable is changed to have new edges the cable reverts to its original texture, but will return to the glitched texture upon removing the new edges.
![2022-10-04_09 22 21](https://user-images.githubusercontent.com/91155989/193859913-9a7b0b33-3e31-4561-841d-670391d14e57.png)

### Steps to reproduce

Running world on server. 
Build with AE2 Glass Cables.
Restart the server.

### Expected behavior

The textures should remain the default AE2 Texture

**Comment by WaitingIdly** [comment]
have you made any changes to the default DJ2 pack? Most notably, have you added optifine?

**Comment by MagnesiumSail** [comment]
No optifine, but added a mod that allows the server provider to get server stats. I can remove it and test, but I doubt its the problem.

**Comment by Preta-Crowz** [comment]
It looks similar to assembler glitch thing which discussed on discord

**Comment by MagnesiumSail** [comment]
Figured out what causes it. Reloading the textures using F3+T causes most wires and cables to have a bugged texture.

**Comment by Preta-Crowz** [comment]
> Figured out what causes it. Reloading the textures using F3+T causes most wires and cables to have a bugged texture. 

That will always cause some texture glitch somewhere in modpack, cable is most common one

**Comment by WaitingIdly** [comment]
yeah: if you reload textures, you have to restart the game. this is true in almost every 1.12 pack
