### ISSUE TITLE
cant craft immersive engineering vacuum tube

### ISSUE THREAD

**Issue by seba5258** [Divine-Journey-2/Divine-Journey-2#751]
### Modpack version

2.16.0

### Description

cant craft immersive engineering vacuum tube
![image_2022-10-04_230329107](https://user-images.githubusercontent.com/115043688/193928100-9f4a4189-4dd2-496b-985a-75d64ec94554.png)

### Steps to reproduce

cant craft

### Expected behavior

shoult craft 2 vacuum tubes

**Comment by WaitingIdly** [comment]
as per the code, you need orange glass
https://github.com/Divine-Journey-2/Divine-Journey-2/blob/ae9fb4e9a30916b5e51e4a38b51bb0fb86a5da43/overrides/scripts/ImmersiveEngineering.zs#L124
