### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by Wandermannn** [Divine-Journey-2/Divine-Journey-2#752]
### Modpack version

2.16.0

### Java version

1.8.0_231

### RAM Allocated

4GB for server, 6GB in total

### Description

I was playing with a friend when suddenly the server shut down. The server starts normally, but when you enter the world, it immediately crashes. The last thing we did was activate the portal to the Twilight Forest.

### When did the crash happen?

When entering world

### Steps to reproduce

Idk

### Minecraft crash report

https://hastebin-plus.herokuapp.com/K4UWiK67V4

**Comment by Preta-Crowz** [comment]
Can't view crash report, it shows only empty page.
Can you upload it again to other site or just here?

**Comment by Wandermannn** [comment]
> Can't view crash report, it shows only empty page. Can you upload it again to other site or just here?

https://pastebin.com/wGckqCEn
Sorry

**Comment by Preta-Crowz** [comment]
You server seems using catserver
It may not bug of mods or pack unless same thing happens on normal forge server
Try change your server core
