### ISSUE TITLE
when viewing some recipes, an error flies and crashes from the server

### ISSUE THREAD

**Issue by bozna** [Divine-Journey-2/Divine-Journey-2#753]
### Modpack version

2.16

### Java version

1.8.0_51

### RAM Allocated

13 GB

### Description

when viewing some recipes, an error flies and crashes from the server. recipes from thaumcraft 6

### When did the crash happen?

when browsing recipes

### Steps to reproduce

when browsing recipes

### Minecraft crash report

when browsing recipes

### Additional context

when browsing recipes

**Comment by luciscout** [comment]
Please actually read the template and upload the crash report here.

**Comment by bozna** [comment]
[
![image](https://user-images.githubusercontent.com/112410211/196521998-0ea409c2-24e7-4cff-8944-4f6669535a57.png)
](url)

**Comment by bozna** [comment]
but how to do it?

**Comment by bozna** [comment]
how to find countdown?

**Comment by Preta-Crowz** [comment]
It looks like this known issue :
> Client crashes when try to view auto-infusion recipes while open infusion matrix itself

**Comment by WaitingIdly** [comment]
please provide a screenshot of your launcher

**Comment by bozna** [comment]
[
![image](https://user-images.githubusercontent.com/112410211/196740321-ffafff83-e248-4096-b273-28596cab243d.png)
](url)

**Comment by LHMezentierB** [comment]
Terraria Launcher

**Comment by luciscout** [comment]
> ![image](https://user-images.githubusercontent.com/112410211/196740321-ffafff83-e248-4096-b273-28596cab243d.png)

You are using a launcher for the purposes of pirating Minecraft. It is also crashing your game. Pirating Minecraft is against the terms of service, is illegal, and we will not support you. Consider buying the game.

**Comment by bozna** [comment]
ok
