### ISSUE TITLE
"A fatal error has occured" crash after i launch my world in solo

### ISSUE THREAD

**Issue by GrosDino** [Divine-Journey-2/Divine-Journey-2#754]
### Modpack version

2.16.0 

### Java version

1.8.0_351

### RAM Allocated

9GB and i have 16Gb on my PC

### Description

After i launch my world and the loading menu is on the screen, after that my game write "Shutting down internal server" and after that i'm in the server menu with the message "A fatal error occured, this connection is terminated".

### When did the crash happen?

it crash but I can pretty much see the game with my hand, 

### Steps to reproduce

1- launch the world
2- waiting for the loading menu to get out
3- pray
4- see the hand of your minecraft skin and a world made of void for like a micro second
5- and you have the message for the crash

### Minecraft crash report

[latest.log](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9834636/latest.log)

### Additional context

![image](https://user-images.githubusercontent.com/116319651/197080669-c1ed9c83-9651-40f1-96dc-ebce8b43fd17.png)
then i press "Back to the game"
![image](https://user-images.githubusercontent.com/116319651/197080718-a0ba5bf4-1712-4940-9db8-8378d005ca3a.png)

**Comment by Preta-Crowz** [comment]
It looks your data was corrupted and game failed to load nbt.
Did you died few times without drop your death log item?

**Comment by GrosDino** [comment]
> It looks your data was corrupted and game failed to load nbt. Did you died few times without drop your death log item?

i died in the nether and after that the game started to crash like that, also i think i have some death log item in my backpack

**Comment by Preta-Crowz** [comment]
If you already have some death logs and died again, nbt will got very long and can corrupt your data.

If you have backup, you can rollback your data by use it.
If you know how to edit data, you can just remove death logs from your inventory.

**Comment by GrosDino** [comment]
and because the game start to crash like that i can't take back my stuff

**Comment by GrosDino** [comment]
i don't have backup :/ any tutorial to edit data ?

**Comment by Preta-Crowz** [comment]
Simple one is get any inventory editor and use it but some editor will not work with mods.
Otherwise, you can use nbt editor to find your inventory and remove item.

**Comment by GrosDino** [comment]
i found how to do and i just removed the death log and it worked, thanks a lot ! u are guys the best !

**Comment by GrosDino** [comment]
i guess i can close now ?
