### ISSUE TITLE
Crash to main menu after requesting autocrafted item

### ISSUE THREAD

**Issue by noel357** [Divine-Journey-2/Divine-Journey-2#758]
### Modpack version

2.17.0

### Java version

CurseForge Default

### RAM Allocated

10GB allocated of 16GB total

### Description

I requested 4 "Storage Upgrade (V)" from the Storage Drawers mod in my ME Crafting Terminal and when clicking on "Start" the crashed and threw me into the main menu.
The autocrafting works and I've requested hundreds of them before and after rejoining the world (singleplayer) they were crafted.

The "Storage Upgrade (V)" item only requires Molecular Assemblers I use and a ME Storage Bus connected to a Drawer Controller with it's drawer wall for ingots so it might be an AE2 internal issue or the combination of AE2 and Storage Drawers.

The "Minecraft crashed!" screen also says that the potential causes are: AE2 Unofficial Extended Life, Mouse Tweaks, LagGoggles

### When did the crash happen?

At the moment I clicked on the "Start" button to request the mentioned items.

### Steps to reproduce

It did happen 3 hours before with a different item so I can't really tell how to reproduce this error other than building the autocrafting in a new world and also requesting the items.

### Minecraft crash report

First crash report where I thought it might be a one time thing:
[crash-2022-11-04_18.36.17-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9941854/crash-2022-11-04_18.36.17-client.txt)

The crash report for this issue:
[crash-2022-11-04_21.21.55-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9941856/crash-2022-11-04_21.21.55-client.txt)

Third crash half an hour later, just opened the ME Crafting Terminal and it threw me into the main menu.
[crash-2022-11-04_22.06.13-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9941962/crash-2022-11-04_22.06.13-client.txt)

### Additional context

It didn't happen once in the 200 hours I played in the 2.16.0 version but 2 times today in the 2.17.0 version.

Edit: My game crashes every 30 mins now, if you want more crash reports just ask me.

**Comment by Preta-Crowz** [comment]
It seems MouseTweaks broke AE

**Comment by noel357** [comment]
> It seems MouseTweaks broke AE

I also noticed that when sorting by "Inventory Tweaks" in a terminal it just doesn't do it and when clicking on the up/down arrow with that sorting the order doesn't reverse. There seem to be some AE2 issues after the update.
