### ISSUE TITLE
Defeating the eldritch quest gives blank books

### ISSUE THREAD

**Issue by Tom4455** [Divine-Journey-2/Divine-Journey-2#76]
**Modpack version:**
beta-version-0.1

**Description:**
Defeating the eldritch quest gives blank books

**Screenshots:**
![image](https://user-images.githubusercontent.com/8618678/128777168-4814b57c-4f06-4d27-a84f-9cb172fc3dea.png)

**Comment by KleinGrrmpf** [comment]
Well, just saying, this is still/again broken...

**Comment by KleinGrrmpf** [comment]
![grafik](https://user-images.githubusercontent.com/50833808/191739885-3f9c3681-62ca-4c51-a535-30c4c9ba54ec.png)
