### ISSUE TITLE
Enchanter : Decay 

### ISSUE THREAD

**Issue by andrelec1** [Divine-Journey-2/Divine-Journey-2#766]
### Modpack version

2.17

### Description

Provide wrong enchanted book...

### Steps to reproduce

![image](https://user-images.githubusercontent.com/3273204/200154440-c991fe17-a6bf-446f-af14-d5bff3831b3d.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/3273204/200154447-3d49e255-6aab-44b7-994b-6e6d6a90bf8b.png)

### Your Divine Journey 2 Discord Username

Andrelec1#0001

**Comment by andrelec1** [comment]
File Enchantements.zs missing from server.zip

![image](https://user-images.githubusercontent.com/3273204/200154688-93cfe4ba-5338-4c82-9567-34f4d0e3a118.png)

**Comment by WaitingIdly** [comment]
for context: this was due to the clientside having the script file (so it shows in JEI), but the server side missing the script file.
