### ISSUE TITLE
rendering Item Crash when joining world / server

### ISSUE THREAD

**Issue by 0brine** [Divine-Journey-2/Divine-Journey-2#767]
### Modpack version

2.16.0

### Java version

8.0.312+7

### RAM Allocated

9GB

### Description

On a server that my friend hosted, when I join my client kicks me back into the main menu.
This also happens when I join a singleplayer world
The crashlog says: 

Time: 2022-11-06 11:43:07 CET
Description: Rendering item

java.lang.OutOfMemoryError: Java heap space
---------------------------------------------------------------------------------------

-- Item being rendered --
  Item Type: divinerpg.objects.items.base.ItemSlowingSword@54a5b067
  Registry Name: divinerpg:frostking_sword
  Item Aux: 0
  Item NBT: {ench:[{lvl:5s,id:16s},{lvl:3s,id:21s},{lvl:3s,id:34s},{lvl:1s,id:70s}],RepairCost:31}
  Item Foil: true

-- Item being rendered --
  Item Type: divinerpg.objects.items.base.ItemSlowingSword@54a5b067
  Item Aux: 0
  Item NBT: {ench:[{lvl:5s,id:16s},{lvl:3s,id:21s},{lvl:3s,id:34s},{lvl:1s,id:70s}],RepairCost:31}
  Item Foil: true

I have the sword in my inventory on the first hotbar slot
Cant drop it because it crashes before i can input anything

### When did the crash happen?

When joining the Server, first frame that renders

### Steps to reproduce

I dont know how to reproduce it

### Minecraft crash report

https://pastebin.com/1Wjavp3M

### Your Divine Journey 2 Discord Username

ZRO#8816

**Comment by 0brine** [comment]
I am sorry, this description is wrong, just tried to join a singleplayer world and go the same crash with a different item

**Comment by WaitingIdly** [comment]
shot in the dark: consider reinstalling your video drivers? there not being a stacktrace gives me basically nothing to go on, and i dont know why there wouldnt be a stacktrace.

**Comment by 0brine** [comment]
Yeah, really weired bug, restarting my client resolved the issue
