### ISSUE TITLE
End Dimension doesn't work

### ISSUE THREAD

**Issue by DemangelM** [Divine-Journey-2/Divine-Journey-2#768]
### Modpack version

2.16.0

### Description

I went and crafted the eyes of ender that I needed to fill the end portal (so the quest was validated) , put just the correct amount of them on the portal, it infact opened but when I jumped in, it told me "Please craft a Eye of Ender to enter the End". I recrafted one, rejumped in, and it still told me that ! Does it have something to do with the fact that when I jumped in I didn't have any left ?

### Steps to reproduce

1. Finish all quests up onto the "Craft an Eye of Ender" one with the Alloy Smelter
2. Find the Portal and put the eyes
3. And when it does activate, game doesn't consider that I actually crafter eyes of ender
4. Can't get into the End :'(

### Expected behavior

End portal should activate after crafting eyes of ender

**Comment by Atricos** [comment]
Are you sure you're playing Divine Journey 2? This is not a thing in the pack. Eyes of Ender have to be made in the Induction Smelter here, not crafted. Did you mean that?

**Comment by DemangelM** [comment]
Well I mean craft in the way of making in the induction smelter in the rest of the comment, but in the quoted sentence I putted, the game did in fact tell me to craft eyes of ender!

**Comment by Atricos** [comment]
Can you post a screenshot?

**Comment by DemangelM** [comment]
I will tomorrow! Thx for your fast answers though!

**Comment by DemangelM** [comment]
(I got teleported back to my home after jumping in the portal)

**Comment by WaitingIdly** [comment]
this is not a requirement in DJ2. However, it is the default config of one of the mods. It appears you didnt get the correct config folder when you installed the modpack. the only fix for this is reinstalling. 
Note that curseforge is quite bad at confirming everything downloaded correctly, so you should download the zip file of the modpack and then install from the zip file, rather than directly installing the pack.

**Comment by DemangelM** [comment]
Oh ok, thx a lot!
