### ISSUE TITLE
Enriching Factory recipe removed for Quartz Ore (bug?)

### ISSUE THREAD

**Issue by noel357** [Divine-Journey-2/Divine-Journey-2#769]
### Modpack version

2.17.1

### Description

After the 2.17.1 update the Enriching Factory recipe for the remaining Quartz Ore was removed but there was no note in the patch notes. Since there is no "general question" tag I used the "bug" one since I don't know if it's intentional or not.

### Steps to reproduce

Place down Enriching Factory and put in the Quartz Ore.

### Expected behavior

Recipe being there.

**Comment by WaitingIdly** [comment]
there is a recipe in the enrichment chamber for quartz ore?

![Screenshot_07-1](https://user-images.githubusercontent.com/25394029/200282432-b84ea1ff-3175-4150-86b1-d8353f715bc5.png)
![Screenshot_07](https://user-images.githubusercontent.com/25394029/200282166-29403865-b1ee-4f50-95f5-529f0766098f.png)

**Comment by noel357** [comment]
![image](https://user-images.githubusercontent.com/35464991/200381059-1bdb479d-289f-45a0-b817-f0f30938071f.png)
Not for this Quartz Ore from Mystical World which my Builder in the Deep Dark is gathering.
JEI also says that it still generates so I assume the "mysticalworld:quartz_ore" was removed from generating and not the "mysticalworld:granite_quartz_ore".
![image](https://user-images.githubusercontent.com/35464991/200381457-3dac7064-dcbe-459c-b609-31b24a4c7cb9.png)

**Comment by King65868** [comment]
Granite Quartz Ore doesn't spawn anymore, but still shows in JER. Should be removed to remove confusion. Also there is a sag mill recipe for the Granite Quartz ore, but that's the only machine way to process this, probably fine since it is removed.
