### ISSUE TITLE
Crash on Startup due to Ender IO Fatal Recipe Error

### ISSUE THREAD

**Issue by Squidsty** [Divine-Journey-2/Divine-Journey-2#776]
### Modpack version

2.17.1

### Java version

1.8.0_351

### RAM Allocated

6GB dedicated 16GB total

### Description

While starting up the mod, at around 5/7ths of the way started up the game crashes and gives this error message
![image](https://user-images.githubusercontent.com/117716164/200504074-22780f2e-c313-4bae-bdf3-6eeac421551b.png)
Me and my friends on our server have all experienced it at least once, most of us more then 30 times. We crash on start up.  We have all been able to join a server at least once though.
Given ENDER IO FATAL RECIPE ERROR with bad file user_recipes.xml. We reviewed user_recipies.xml but found nothing really different in people that were currently playing, we aren't tech savvy in any way though

### When did the crash happen?

5/7 loadup phase

### Steps to reproduce

1. Open the game, fails to open at 5/7ths loading. 

### Minecraft crash report

[latest.log](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9958838/latest.log)

**Comment by WaitingIdly** [comment]
the curseforge launcher updated, and literally nobody can launch using it currently. You must use a different launcher, at least until they resolve this problem.
