### ISSUE TITLE
Ender IO Enchanter Cannot Differentiate Between Tinker's Construct Modifiers

### ISSUE THREAD

**Issue by NickZumb** [Divine-Journey-2/Divine-Journey-2#779]
### Modpack version

2.17.1

### Description

When using the Ender IO Enchanter to create silk touch enchanted books, the recipe instead gives mending enchanted books.  I believe this is because the Enchanter can not tell the difference between Tinker's Construct Modifiers.  The same applies to the reinforcement modifier giving mending books instead of unbreaking books.

### Steps to reproduce

1. Open the Ender IO Enchanter
2. Put in the recipe for a silk touch enchanted book (Book and Quill, Silky Jewel, 15 Lapis)
3.  The Enchanter thinks you are tying to make a mending book

### Expected behavior

The enchanter should be able to use the correct recipe.   To tell the difference between the modifier items, I believe the script needs to also match item data, not just the item.

### Additional context

![image](https://user-images.githubusercontent.com/87913921/200671108-549efe5c-8ae2-4c3e-bffa-aefb10e75974.png)

### Your Divine Journey 2 Discord Username

NickZumb1234#4703

**Comment by WaitingIdly** [comment]
yup already fixed in dev
