### ISSUE TITLE
Server Crash in Eden (Possibly caused by structure generation overload)

### ISSUE THREAD

**Issue by KingFishQiu** [Divine-Journey-2/Divine-Journey-2#780]
### Modpack version

2.17.1

### Java version

1.8.0_311

### RAM Allocated

8, 24

### Description

When my friend entered Eden for the first time and went South of our Eden spawn, the server crashed. (He used the root sky soarer to fly). When server restarted, I entered the eden, it was fine. But when he joined again, the server crashed again. (He was at his last position when server crashed previously). I am able to tp him back to me once, but when he went South again (trying to trace back what he did to cause server crash), the server did crash again. And I noticed that on the server console, there is a huge lag caused by  Recurrent Complex loading a new chunk. 

After the server restarted, I also tried to go South (try to reproduce the crash) (I was walking instead of flying though), I noticed that there is a huge lag when the dungeons are generating, and the console again shows the lag is caused by Recurrent Complex loading a new chunk. After I loaded (generated) the entire island by walking around, my friend connect in, spawned near me, and there is no crash this time.

Just want to make sure if it is the fast movement causing too much structure generation that overloaded and crashed the server or if it is some other problem. Our servers spec is Premium Minecraft Hosting 6GB Ram

(And thank God we were playing on a bisect server and we were not flying together when the server crashed for the first time so I can salvage the situation) I am already downloading the previous backup to roll back the saves if the situation can't be salvaged...

### When did the crash happen?

Exploring Eden

### Steps to reproduce

Explained in description..

1. Go to Eden.
2. Flying using Root Sky Soarer
3. Server Crashes

### Minecraft crash report

Crash Report (one of them)
https://pastebin.com/zXiD7aFX

Console command lines before server crashed
https://pastebin.com/xhg62tZQ

### Your Divine Journey 2 Discord Username

KingFish-v-#9740

**Comment by luciscout** [comment]
`java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)`

Your server is being stopped by Watchdog as ticks are taking too long. This is intended as ticks taking too long can hang your server indefinitely. Tick lag is typical in exploring the custom dimensions as there are many structures that span multiple chunks and must generate multiple chunks at once (cascading world gen lag).

To resolve your issue you can set `max-tick-time` to `-1` in `server.properties` or any other large number.
