### ISSUE TITLE
Jei display wrong recip for Infused Wood from 

### ISSUE THREAD

**Issue by andrelec1** [Divine-Journey-2/Divine-Journey-2#784]
### Modpack version

2.17.1

### Description

Looking recip for Infused Wood in JEI
JEI display 2tab...
Tab InWorldCrafting display right recip.
The tab "Just Enough Throwing In Fluids" display wrong recip. ( crafting from oredictionary wood )
![image](https://user-images.githubusercontent.com/3273204/201352384-428db4ba-6a0f-4b96-a46b-04594de0746d.png)

### Steps to reproduce

Loiking for Infused Wood recip

### Expected behavior

Only show the recip from "InWorldCrafting"

### Your Divine Journey 2 Discord Username

Andrelec1#0001

**Comment by WaitingIdly** [comment]
known issue, there is no config option & doesnt respect the Astral Sorcery config: it just registers if the mod is detected
