### ISSUE TITLE
/dank/null/ stuck in a ME system

### ISSUE THREAD

**Issue by Janda2304** [Divine-Journey-2/Divine-Journey-2#786]
### Modpack version

2.17.1

### Description

Accidentally put my /dank/null/ MK V in the ME system and cant get it out again. 

### Steps to reproduce

1.Open the Game
2. get a /dank/null/
3. get a ME system
4. put /dank/null/ into ME system
5. i wish u luck with getting it out again

### Expected behavior

Should be able to get it out 

### Your Divine Journey 2 Discord Username

janda_voee#9889

**Comment by WaitingIdly** [comment]
use an export bus with fuzzy card
