### ISSUE TITLE
Using arcane ansorcellator for enchanted book doesn't want to go in a dischantment generator

### ISSUE THREAD

**Issue by Felix201b** [Divine-Journey-2/Divine-Journey-2#788]
### Modpack version

2.17.1

### Description

With the arcane Ensorcellator while making book the dischantement generator wont take the enchanted book even for exemple lure 1.

### Steps to reproduce

1. Make a enchanted book using the Arcane Ensorcellator.
2 Using any types of item transportation. even hopper
3. The enchanted book doesn't want to go in the dischantment generator

### Expected behavior

The book in the arcane ensorcelator go in the dischantment generatorà

I think is the yellow and the aqua color or the nbt causing the issue

I switch version before the bug arrived (2.16.0 to 2.17.1

### Additional context

https://youtu.be/Tj572NvEjvM

### Your Divine Journey 2 Discord Username

Felix201b#3735

**Comment by Preta-Crowz** [comment]
they might accept only exact nbt, not calculated from their enchant
