### ISSUE TITLE
openblocks tank cannot be crafted inside the ME crafting terminal

### ISSUE THREAD

**Issue by Janda2304** [Divine-Journey-2/Divine-Journey-2#789]
### Modpack version

2.17.1

### Description

After the new update made openblocks tanks unstackable it also made them uncraftable in the ME crafting terminal
Still can be crafted in a normal crafting table 

### Steps to reproduce

1. Open the game
2. craft openblocks tank
3. try to craft openblocks tank in ME crafting terminal
4. You can keep trying but it wont work 

### Expected behavior

Should be craftable 

### Your Divine Journey 2 Discord Username

janda_voee#9889

**Comment by KleinGrrmpf** [comment]
Can confirm
