### ISSUE TITLE
AS Infused Wood displays wrong tooltip

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#791]
### Modpack version

2.17.1

### Where is the typo located?

In the tooltip of Astral Sorcery's Infused Wood

### Exact fix

Should be "Only accepts Glimmering Dreamwood" not "Only accepts Glimmering Livingwood" to represent the crafting recipe

### Your Divine Journey 2 Discord Username

KleinGrrmpf#9186

**Comment by King65868** [comment]
Going to be fixed by #772
