### ISSUE TITLE
Enchanter doesn't work for certain recipes

### ISSUE THREAD

**Issue by DwardEE** [Divine-Journey-2/Divine-Journey-2#822]
### Modpack version

2.17.1

### Description

When using the enchanter for ender io, tring to make a enchanted book of fire protection results in a enchanted book of bladerang.

### Steps to reproduce

Use a ender io enchanter
input the required lapis and sulfur

### Expected behavior

produces a enchanted book of fire protection

### Additional context

some other recipes like trying to make enchanted book of mending with mending moss doesn't work either. It returns a book of unbreaking.

**Comment by KleinGrrmpf** [comment]
Duplicate of #779 and #790 and fixed indev. Please also check closed issues for the issue you want to open before doing so ;)
But hopefully the update comes soon!
