### ISSUE TITLE
Remove Tooltip on various items as they are now in the Activate Item JEI category

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#831]
### Describe the feature

Remove Tooltip on various items as they are now in the Activate Item JEI category. The items in question are the metamorphic stones, the potato armor pieces, Activated Ender Cores, the Arcane Workbench, 

### Reasons why this should be added

There is no reason for the tooltips to exist anymore. They can be removed for the same reason that the tooltips on Fluxed Phyto-Gro and Fluxed Aqua-Chow were removed.

### Describe alternatives you've considered

You can leave them in but they are superfluous now that the blocks and items are represented in the Activate Item JEI category. 

### Your Divine Journey 2 Discord Username

KleinGrrmpf#9186

**Comment by King65868** [comment]
These tooltips will stay
