### ISSUE TITLE
Quantum Quarry Quest Gives Incorrect Information on How to Get Corralium Ore

### ISSUE THREAD

**Issue by NickZumb** [Divine-Journey-2/Divine-Journey-2#837]
### Modpack version

2.18.0

### Where is the typo located?

In Chapter 13, Quest 1465: "Don't quarry about it!"
Near the bottom where it describes how the biome marker works

### Exact fix

Add "Coralium Infested" in front of "Swamp"

**Comment by WaitingIdly** [comment]
swamp is correct
https://github.com/Shinoow/AbyssalCraft/blob/2fd00e1444c7d06c9cbe1472ece75ca838c73cf4/src/main/java/com/shinoow/abyssalcraft/common/world/AbyssalCraftWorldGenerator.java#L80
