### ISSUE TITLE
Most Biome Markers do not Function Properly in the Quantum Quarry

### ISSUE THREAD

**Issue by NickZumb** [Divine-Journey-2/Divine-Journey-2#838]
### Modpack version

2.18.0

### Description

While I am not certain most biome marker do nothing or do not function entirely properly in the Quantum Quarry.  I ran some tests by filling storage crates and compared what I got.  I primarily just looked for blocks specific to that biome.

Savanna - Does work
Hell - Does not work
Swampland - Does work, but does not give coralium ore
Infested Swamp - Does work
Ocean - Unsure, but does not give coralium ore
Darklands - Does work
Eden - Does not work
Twighlight Highlands - Does work
Venus Mountain - Does not work
Aether - Does not work
Deep Mushroom Forest - Does work
Sand Plains (Atum Biome) - Does not work
Subterranean Savanna - Does not work

### Steps to reproduce

1. Build a quantum quarry with a biome marker
2. put in a silk touch book
3. Look for biome specifc blocks (Different ores, stone, trees)

### Expected behavior

These biomes would generate and be mined properly.  This is probably a bug with the mod itself, so I don't how it may be fixed.
The questbook should probably be update to say that it does only works with overworld and twilight forest biomes.

### Your Divine Journey 2 Discord Username

NickZumb1234#4703

**Comment by WaitingIdly** [comment]
non-overworld biomes are not generated properly. Savanna, Swampland, and Ocean do work.

**Comment by King65868** [comment]
By default Hell and End biomes are disabled

**Comment by WaitingIdly** [comment]
information was added on why most of the biomes you tried dont work
