### ISSUE TITLE
Bug with creating an Iceworld II potion for Bewitchment

### ISSUE THREAD

**Issue by bommerhondjes14** [Divine-Journey-2/Divine-Journey-2#843]
### Modpack version

2.7.1

### Description

![image](https://user-images.githubusercontent.com/16944023/205495922-5a4a536a-3225-45fa-a700-16551de249d2.png)

The recipe shown in the quest makes an Iceworld II potion, but the quest needs a blue Hellworld II potion, which is impossible to make. 

Even creating a Hellworld II potion does not work as that makes a red Hellworld II potion, making this quest impossible to complete without cheating it.

### Steps to reproduce

1. Have the open task for quest id 184
2. Follow the steps in the quest description to make the potion
3. The task does not complete as the potion in the task is incorrect.

### Expected behavior

The potion shown in the task should have Iceworld II but instead it has Hellworld II.

### Your Divine Journey 2 Discord Username

Bommerhond#9411

**Comment by WILSONowo** [comment]
i still can't finish as i play in 2.19.1  :(
