### ISSUE TITLE
Eternal Water Bucket tip in Witches' Cauldron's Quest Book page

### ISSUE THREAD

**Issue by noel357** [Divine-Journey-2/Divine-Journey-2#861]
### Describe the feature

The Quest Book page for the Witches' Cauldron says that it can be automated using a Mechanical User with a Water Bucket inside, getting powered when an ID Block Reader detects that the Cauldron is empty. In my opinion it's easier to place an Eternal Water Bucket from Evilcraft in the Mechanical User because it doesn't have the downside of picking up the water again when left on Always On.
If the dev also thinks that this is an easier way it could be added to the Quest Book or replace the existing note.

### Reasons why this should be added

Easier to set up in my opinion.

### Additional context

Thanks to Campion for letting me know about this.

### Your Divine Journey 2 Discord Username

NOEL357#5878

**Comment by KleinGrrmpf** [comment]
Not just the Eternal Water Bucket works, you can also just place a Neverending Bowl in the user and it automatically fills the cauldron with water

**Comment by King65868** [comment]
Yep, also was added.
