### ISSUE TITLE
Can't make pickaxe heads

### ISSUE THREAD

**Issue by agabeluga** [Divine-Journey-2/Divine-Journey-2#862]
### Modpack version

2.18.0

### Description

I don't know if that isn't supposed to work. I'm trying to get the allumite pickaxe head. I previously chose the ingot cast so I need to make a pickaxe cast, but to make that I need a pickaxe head. I tried to make the pickaxe head out of stone. So I placed a pickaxe head pattern and cobblestone into their corresponding slots, and it said material value: 1 Stone, it didn't let me get the pickaxe, even though I had more cobblestone in my inventory. 

### Steps to reproduce

1.Get a Part Table, a pickaxe head pattern and a material.
2.Place down the part table and put the pattern and material into their corresponding slots.
3.Make sure you have more of that material in your inventory.
4.As you can see it doesn't work.

### Expected behavior

I think that I should get a pickaxe head.

**Comment by agabeluga** [comment]
No

**Comment by KleinGrrmpf** [comment]
![grafik](https://user-images.githubusercontent.com/50833808/207393478-3d2f201c-77d4-429c-bd8d-6080d2a4f5ca.png)

It does work... You need to put all three stones in at once tho. If you put them in one by one, the number turns from red to gray but it doesn't give you an output.

**Comment by agabeluga** [comment]
Thanks
