### ISSUE TITLE
Energy Laser Relays + Modifier: Range

### ISSUE THREAD

**Issue by AlfredTheSalmon** [Divine-Journey-2/Divine-Journey-2#863]
### Modpack version

2.18.0

### Description

The range upgrade doesn't get applied to the laser if it's the only one left in your hand. If there's one left (lets say you have 2 and apply 1 to a laser), it works as intended.

### Steps to reproduce

Put 2 lasers around 30 blocks away. Base lasers can't create a connection this way.
Get 1 modifier: range on 1 inventory slot, and at least 2 in another. 
Apply the 1 range upgrade to the laser, it gets consumed. 
Hold the Actually Additions wrench and watch the laser, it didn't get applied, and the connection between lasers can't be made.
Apply the other stack to the same laser, it consumes 1, leaving you with the remaining ones. 
Holding the wrench, now it shows a hovering range upgrade on the laser. 
Apply the same stack to the other laser and the connection can now be made.
Video:

https://user-images.githubusercontent.com/26433824/207397747-6d67d032-7821-4578-b541-61ce59514277.mp4

### Expected behavior

The range should be applied on both situations

### Your Divine Journey 2 Discord Username

Sérgio. The Salmon.#4166

**Comment by King65868** [comment]
Experienced the same issue before, a bit annoying

**Comment by KleinGrrmpf** [comment]
It is. And it is not just Energy Lasers, it's also Item Lasers and probably Fluid Lasers
