### ISSUE TITLE
ProjectRed - Fabrication

### ISSUE THREAD

**Issue by mycroftjr** [Divine-Journey-2/Divine-Journey-2#868]
### Mod Name

Project Red - Fabrication https://www.curseforge.com/minecraft/mc-mods/project-red-fabrication/files/2745547

### Reasons why this should be added

Allows you to build complex circuits that fit within a single block. Completes the ProjectRed arsenal for this version of Minecraft.

### Your Divine Journey 2 Discord Username

MycroftJr#9263

**Comment by WaitingIdly** [comment]
while Fabrication allows for higher density of redstone logic via ProjectRed, it is superfluous in this modpack - you rarely need such size to begin with, and Integrated Dynamics can let you achieve similar things.
additionally, we only have ProjectRed Core and Transmission - only 2 or the 7 possible ProjectRed mods. adding this to "complete" the arsenal is missing several pieces of that puzzle.
