### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by agabeluga** [Divine-Journey-2/Divine-Journey-2#871]
### Modpack version

2.18.0

### Java version

1.8.0_51

### RAM Allocated

I dedicated 8Gb of RAM. My PC has 16Gb of RAM.

### Description

I loaded my world. I  walked around a bit and it crashed. Vanilla Fix says the cause is unknown. I launched the world again, but this time it crashed immediately with the cause unknown. 

### When did the crash happen?

First after walking a bit between a savanna and a mystical forest. The second time, just as it loaded.

### Steps to reproduce

1. Go into the game
2. The game crashes

### Minecraft crash report

[https://justpaste.it/5zd89](url)

**Comment by WaitingIdly** [comment]
this is world corruption. restore from a backup.
