### ISSUE TITLE
Exporting Fluids from Modular Machinery Fluid Input Hatches

### ISSUE THREAD

**Issue by noel357** [Divine-Journey-2/Divine-Journey-2#872]
### Describe the feature

I would like to be able to export fluids from Modular Machinery Fluid Input Hatches. It's the only problem I have right now with my setup and I don't think there's a balance or other logical reason to not being able to.
I can imagine that it may not be possible from the mod's programming but if it can be changed to be able to export fluids from the Input Hatches I'd appreciate it.

### Reasons why this should be added

Since the Liquicrafter has two recipes with Sulfuric Acid it occurs that my setup imports Sulfuric Acid and Purifying Liquid into the Fluid Input Hatches if there's a Solar Dust in the Item Input but if there's also a Crystallized Sulfur Cluster in the Item Input the Sulfuric Acid is used by the duplication recipe and the Purifying Liquid stays in the Hatch blocking further recipes.
If I would be able to export the Purifying Liquid when there's no Sulfuric Acid in the Hatch the problem would be solved but that isn't possible right now.

### Your Divine Journey 2 Discord Username

NOEL357#5878

**Comment by Preta-Crowz** [comment]
simply right-click tank on hatch works, others might work

**Comment by noel357** [comment]
I hope my current workaround works and that might also be another way, my question is just is it not possible because nobody needed it before and it was just not coded this way (which would be fine) or is it specifically forbidden (which wouldn't make sense imo)? Because putting a Fluid Importer on the Hatch would be way simpler than right-clicking with a tank, emptying it and putting it back.

**Comment by King65868** [comment]
It was just not coded that way
