### ISSUE TITLE
Easy Mode

### ISSUE THREAD

**Issue by agabeluga** [Divine-Journey-2/Divine-Journey-2#874]
### Describe the feature

It would be great, if you added an easy mode to the game. Now here's my idea on how it would look:
1. Some DivineRPG mobs would be blacklisted from spawning (The Grue, The Eye etc.)
2. The quests would give better rewards (10 Iron -> 15 Iron)
3. The recipes would be easier to make (2 Iron for 1 iron plate -> 1 iron for 1 iron plate)
And more

### Reasons why this should be added

New players could have an easier and more pleasant time, rather than giving up early.

**Comment by Atricos** [comment]
It would probably take another 16 months of work. No.

**Comment by agabeluga** [comment]
I could help

**Comment by WaitingIdly** [comment]
feel free to fork the repo and work on one then.

**Comment by MaxistheSpy** [comment]
Im not sure if it would be enjoyable but you could also just write a script that multiplies all quest rewards by 10x and blacklists a few mobs then post it on gh. But something like that is going to take a lot of effort, if it didnt it probably wouldent be as fun, and its not fair to the devs to ask them to make a feature that they know will be low effort and bad, which means they would have to write an entire new pack re balanced around being easy. 

> I could help
