### ISSUE TITLE
Bq doesn't work in LAN?

### ISSUE THREAD

**Issue by SLoppyslime** [Divine-Journey-2/Divine-Journey-2#875]
### Modpack version

2.18.0

### Description

I launched a dedicated server on hamachi(basically worldwide LAN) with the modpack and my quests don't appear nor
the /bq_admin default command work, is there something to be resolved?

### Steps to reproduce

Set up an hamachi server
connect to said hamachi server
try /bq_admin default load
Fail.

### Expected behavior

having quests in the questbook instead of a blank page

### Additional context

help pls

### Your Divine Journey 2 Discord Username

SloppySlime#8087

**Comment by Preta-Crowz** [comment]
Known mod issue, BQ will never work right on lan server
If you want to play with your friends, you must setup server or join public server.

**Comment by Preta-Crowz** [comment]
wait, you wrote wrong title

**Comment by Preta-Crowz** [comment]
Check your server is running with forge

**Comment by SLoppyslime** [comment]
I'm checking to see if forge.jar is working at least hold on

**Comment by SLoppyslime** [comment]
Run.bat didn't work So I launched minecraft.jar maybe that's the issue

**Comment by Preta-Crowz** [comment]
> Run.bat didn't work So I launched minecraft.jar maybe that's the issue

minecraft.jar will launch vanilla server, any mods will not applied and you need to delete world to generated again

**Comment by SLoppyslime** [comment]
I deleted world, launched it again and it still didn't work, check in #techsupport in the discord I sent a cmd screenshot

**Comment by SLoppyslime** [comment]
according to waitingIdly it might be the java version that is wrong, I will give updates

**Comment by SLoppyslime** [comment]
There Is the same Issue but I think it's because the run.bat is trying to use java 19 again, I need a way to redirect it

**Comment by SLoppyslime** [comment]
Issue resolved! I had to put java 8 into my server folder and instead of
Java -server ...
I put 
\Java\java8\bin\java.exe -server ...
thank you to an actual dev for helping me with it
