### ISSUE TITLE
Can't smelt Pulverized Iron in the ARC Furnace

### ISSUE THREAD

**Issue by LHMezentierB** [Divine-Journey-2/Divine-Journey-2#878]
### Modpack version

2.18.0

### Description

Pulverized Iron Can't be smelt in the arc furnace, while other thermal dusts can.
![image](https://user-images.githubusercontent.com/113219956/210810910-296c09a5-422d-4c2d-b5cc-1be46debc8e0.png)
![image](https://user-images.githubusercontent.com/113219956/210810915-7b82d3ff-5143-420f-857c-643432821149.png)

### Steps to reproduce

Start the modpack, go into a world, and try to smelt pulverized iron in a arc furnace.

### Expected behavior

I believe pulverized iron should turn into iron ingots.

### Your Divine Journey 2 Discord Username

LHRat#7353

**Comment by King65868** [comment]
Duplicate of #536
