### ISSUE TITLE
Resonating Gem autocrafting causes console spam

### ISSUE THREAD

**Issue by C0D3-M4513R** [Divine-Journey-2/Divine-Journey-2#881]
### Modpack version

2.18.0

### Description

When trying to automate Resonating Gem autocrafting, we get a lot of console messages.
This makes it harder to find relavent stuff in the console.
He have banned items for console spamming, but in this inctance, if there is no solution I might end up altering the AstralScorcery java bytecode and remove the relavent logging statements

### Steps to reproduce

1. Create a Server
2. Automate the Resonating gem autocrafting as shown in the screenshot.

### Expected behavior

No Console spam.

### Additional context

![grafik](https://user-images.githubusercontent.com/28912031/211639816-da4a9412-e4d2-4768-97bc-31a5b4da1810.png)
The endertank has liquid starlight in it, and keeps the Containment Chalice full.
The back Mechanical User has a Wand in it, and the right one has a Sparkeling Aquamarine.
In the Corner is a Ranged collector.
![grafik](https://user-images.githubusercontent.com/28912031/211640696-41319ca8-39a7-4bbd-afc7-da74b61dae92.png)

### Your Divine Journey 2 Discord Username

WaitingIdly is on the PixelGaming discord, or just @`C0D3 M4513R` in the Divine Jouney 2 discord.

**Comment by Atricos** [comment]
It might be worth [reporting this to Astral Sorcery](https://github.com/HellFirePvP/AstralSorcery/issues) as well.
