### ISSUE TITLE
Give more chunkloading to players

### ISSUE THREAD

**Issue by Leclowndu93150** [Divine-Journey-2/Divine-Journey-2#883]
### Describe the feature

I would like to see more chunkloading for players like 50 more chunks or 100 more because some players refuse to "cheat"

### Reasons why this should be added

People limit themselves to 50 chunks and it starts lag

### Describe alternatives you've considered

Chunkloading wand that doesnt work

### Your Divine Journey 2 Discord Username

Leclowndu93150

**Comment by Preta-Crowz** [comment]
edit your ftb utilities permission, not pack issue

**Comment by Leclowndu93150** [comment]
I know that but players refuse to do so

**Comment by WaitingIdly** [comment]
its already possible. if your players dont want to "cheat", i dont consider this cheating and they shouldnt either.
