### ISSUE TITLE
does not write the name of the block on top

### ISSUE THREAD

**Issue by JfsWeg123** [Divine-Journey-2/Divine-Journey-2#903]
### Modpack version

2.18.0

### Description

for some reason does not write the name of the block on top and its description

![image](https://user-images.githubusercontent.com/123690399/214953609-7dbcd523-02ea-4f63-b826-3ade8b3d72c2.png)

### Steps to reproduce

1.launch the game using Tlauncher
2.launch my world
3. the mod that shows the description of the block and the name does not work
![image](https://user-images.githubusercontent.com/123690399/214953983-323d6188-5116-43fb-8413-cde4c8f9b527.png)

### Expected behavior

should be like this
![image](https://user-images.githubusercontent.com/123690399/214954229-a708067e-ae4b-4e1d-b625-15f706ebfa9f.png)

### Your Divine Journey 2 Discord Username

JfsWeg#2285

**Comment by WaitingIdly** [comment]
english issues only, please translate to english.

**Comment by WaitingIdly** [comment]
this feature is called WAILA (What Am I Looking At), and by default has a "Toggle Show/hide" keybind bound to NUMPAD1. probably accidentally pressed it.

**Comment by JfsWeg123** [comment]
Thanks a lot
