### ISSUE TITLE
GalacticraftPlanets.zs missing semicolon in server files

### ISSUE THREAD

**Issue by sarcastic6** [Divine-Journey-2/Divine-Journey-2#907]
### Modpack version

2.19.0

### Description

scripts/GalacticraftPlanets.zs is missing a semicolon at the end of line 276 in the server zip package.  Interestingly, the version included in the client package seems fine.

### Steps to reproduce

Update client and server to 2.19.0
Connect to server
Observe crafttweaker error upon connecting

### Expected behavior

After adding a semicolon to the end of line 276, the error does not appear.

### Your Divine Journey 2 Discord Username

sarcastic6#6666

**Comment by King65868** [comment]
Will be fixed hopefully soon, already known
