### ISSUE TITLE
LE Transmitter/Receiver quests still don't work correctly

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/Divine-Journey-2#910]
### Modpack version

2.19.1

### Description

I updated the quest book and took my Tier 3 receiver from the LE Multiblock but the quest still coudn't be completed despite it showing me that the Receiver task is completed and the quest states that only one of the tasks has to be completed. The same thing goes for the Tier 1 and 2 quests. 

### Steps to reproduce

1. Update the questbook to 2.19.1
2. Unlock the LE Transmitter/Receiver quests
3. Acquire a Tier 1/2/3 LE Receiver

### Expected behavior

The quests should complete.

### Additional context

I relogged after updating the questbook but that didn't fix it.

![grafik](https://user-images.githubusercontent.com/50833808/215242152-a5e5eae8-3a87-4edf-98fa-9f90d46d922a.png)

![grafik](https://user-images.githubusercontent.com/50833808/215242171-2df851ea-8c67-4a4b-a1b8-bf410d6369f4.png)

![grafik](https://user-images.githubusercontent.com/50833808/215242193-d6c25e67-d686-48ec-b816-baf76b5e3ad3.png)

![grafik](https://user-images.githubusercontent.com/50833808/215242204-dee9681f-98f4-4d6e-b513-4dbaf2c599c6.png)

### Your Divine Journey 2 Discord Username

KleinGrrmpf#9186

**Comment by King65868** [comment]
Woops
