### ISSUE TITLE
Recipes not outputting anything or outputting a wrong item

### ISSUE THREAD

**Issue by ElPupus** [Divine-Journey-2/Divine-Journey-2#912]
### Modpack version

2.19.0

### Description

Several recipes (found 3 so far) don't output anything either in a crafting table or a AE Crafting Terminal.

OpenBlock elevators
![DJ2 bug](https://user-images.githubusercontent.com/123821683/215274044-4352af70-510d-409b-b967-2dac4180c5d7.png)

Hand Framing Tool
![DJ2 bug 2](https://user-images.githubusercontent.com/123821683/215274082-3da6ea13-31bc-4d58-ad85-10ed7d642c34.png)

Firestarter
![DJ2 bug 3](https://user-images.githubusercontent.com/123821683/215274478-056d6996-f227-4da6-8421-24098eb3b104.png)

### Steps to reproduce

1. Get into a world
2. Place required items in a crafting grid
3. Recipe doesn't output anything (not a visual bug where you can actually craft the item but don't see it in the output).
4. In the case of the 3rd example, when I click the diamond stack I get a Fire Starter (from Roots) instead while it doesn't appear in JEI. And this bug only appears in a crafting station from Tinker's Construct.

### Expected behavior

It should output the correct item.

### Your Divine Journey 2 Discord Username

ElPupus#3660

**Comment by King65868** [comment]
Update to 2.19.1, likely will fix the issue

**Comment by ElPupus** [comment]
Yep. Fixed it ! Thanks.
