### ISSUE TITLE
ch.20 bewitchment,splash potion task

### ISSUE THREAD

**Issue by WILSONowo** [Divine-Journey-2/Divine-Journey-2#914]
### Modpack version

2.19.1

### Description

It seems that task can not finish after update,the hell world II potion is different from the crafting one.

### Steps to reproduce

1.play in a new save,use bq_admin finish 160 to finish the front task.
2.build an altar and a cauldron,make two kinds of potion
3.the iceworld II can be detected,but hell world can't
4.can't finish the task

### Expected behavior

I think use the crafting potion in the task request can solve.   :D

### Your Divine Journey 2 Discord Username

WILSONawa#1099

**Comment by WILSONowo** [comment]
the hellworld II potion is red fluid in the bottle

**Comment by King65868** [comment]
Will be fixed in next update
