### ISSUE TITLE
Lot of crashes

### ISSUE THREAD

**Issue by Losiqpl** [Divine-Journey-2/Divine-Journey-2#918]
### Modpack version

14.23.5.2860

### Java version

1.8.0_51

### RAM Allocated

I dedicated 13GB my pc have 16GB

### Description

Game work couple of minutes, then crashes (if it turn on)

### When did the crash happen?

Crash is happening at loading od random stages, but when you turn on again couple of times it turns on, but when you are couple minutes on world it crashes to desktop, "anti-crash mod" (yes, I forgot name) don't work in this case and there is no crash report. Once when the game crashed i got a crash report and I've been still in Minecraft (because of this mod), but it happened when I started the LAN world, when i tried to do it again still crashes to desktop

### Steps to reproduce

1. Open the game (if you can on 1st try)
2. Get into the world
3. Wait couple of minutes
4. Crash

### Minecraft crash report

https://paste.ee/p/x3WXM I have another amount of RAM dedicated (proposed by TLauncher)

**Comment by WaitingIdly** [comment]
you are using tlauncher. this is a pirate launcher, which comes with a number of exclusive bugs. your launcher is not and will never be supported.
buy minecraft if you havent and switch to a different launcher - for instance, Prism Launcher.
