### ISSUE TITLE
Recipe crash report

### ISSUE THREAD

**Issue by Jair0Z** [Divine-Journey-2/Divine-Journey-2#920]
### Modpack version

2.19.1

### Java version

1.8.0_301

### RAM Allocated

I dedicated 6 GBS and my PC has 16 GBs of RAM.

### Description

when open recipe of some seeds from mystical agriculture

### When did the crash happen?

when open recipe of some seeds from mystical agriculture

### Steps to reproduce

1. Get into a world
2. open recipe of nether seeds or some other seeds
3. game crashes

### Minecraft crash report

[crash-2023-02-04_22.05.59-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/10608810/crash-2023-02-04_22.05.59-client.txt)

### Additional context

![image](https://user-images.githubusercontent.com/124442506/216772126-415aace5-9dc7-4115-b710-4171ff52bc9e.png)

### Your Divine Journey 2 Discord Username

Jairo#8174

**Comment by noel357** [comment]
I think you're using the tlauncher which is a pirate launcher and has bugs of it's own. If you haven't bought Minecraft already you should buy it and switch to a different launcher like Prism or switch immediately if you've already bought it. I don't think the tlauncher will ever be supported.

**Comment by KleinGrrmpf** [comment]
It won't, it has been stated multiple times, including in #918
