### ISSUE TITLE
add heliosis lumps to the mob loot fabricator loot table

### ISSUE THREAD

**Issue by InfernalGrumbler** [Divine-Journey-2/Divine-Journey-2#923]
### Describe the feature

Basically, it just adds one heliosis lump to the mob loot fabricator loot table.

### Reasons why this should be added

I would like to see this in the pack to make ender chest crafting later game more convenient. I know by then ender chest crafting shouldn't be much of a problem, but it'd just help with QOL. You don't get the mob loot fab until chapter 23, ten chapters after the ender chest is initially unlocked. Heliosis lumps are pretty impossible to spawn in in any other way because of the nature of the boss it drops from and because you can only find them in a rare chest.

**Comment by WaitingIdly** [comment]
given that their only use is to craft the Ender Chest, and as stated crafting one normally isnt much of a problem by this point in the game, i am going to reject this request.
