### ISSUE TITLE
Mod Request (Opencomputers/Computercraft)

### ISSUE THREAD

**Issue by mantikafasi** [Divine-Journey-2/Divine-Journey-2#925]
### Mod Name

Opencomputers/computercraft

### Reasons why this should be added

~~integrated dynamics cause so much tps lag if used too much, with opencomputer/computercraft it might help to automate things without causing too much tps lag~~
it seems like both opencomputers and computercraft only support reading items from inventory without nbt data,so it would be probably usuless in most cases but still would be cool to see in modpack

**Comment by Atricos** [comment]
I initially contemplated on adding ComputerCraft / OpenComputers, but I figured it would be too intimidating for most players, and some would see it as "necessary to use", which would drive players away. WaitingIdly's comment on the matter is "you can add it if you want, but otherwise no". Sorry!
