### ISSUE TITLE
add pink slime and liquid meat to the mob loot fabricator

### ISSUE THREAD

**Issue by InfernalGrumbler** [Divine-Journey-2/Divine-Journey-2#930]
### Describe the feature

Allow liquid meat and pink slime balls(maybe like 8) to be output from the mob loot fabricator with a mob slaughter factory as a catalyst. 

about 1k mb of liquid meat per 20 ticks or whatever yall deem fit

### Reasons why this should be added

Would allow for less lag automation for a liquid meat farm. Liquid meat is better than the nourishment botania charm in many cases so many people might prefer it.

**Comment by KleinGrrmpf** [comment]
But why the Pink Slime Fluid tho? That is literally useless!

**Comment by InfernalGrumbler** [comment]
It isn't useless, but it is more inefficient than the slime balls and is kinda against the point of having a mob loot fab. i already suggested it in alternatives, but i changed it to the main request just in case

**Comment by KleinGrrmpf** [comment]
I didn't think you didn't already get the balls... That's why I thought the liquid was useless...
