### ISSUE TITLE
Server crashed when chiseling

### ISSUE THREAD

**Issue by TheGamingGeneral** [Divine-Journey-2/Divine-Journey-2#932]
### Modpack version

2.19.1

### Java version

1.8.0_292, AdoptOpenJDK

### RAM Allocated

6144mb server

### Description

Happened when using an iron chisel on a fancy lamp from bibliocraft. (left clicking)

### When did the crash happen?

Happened when using an iron chisel on a fancy lamp from bibliocraft. (left clicking)

### Steps to reproduce

Left click chisel on a fancy lamp from bibliocraft

### Minecraft crash report

[crash-2023-02-25_19.09.30-server.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/10832473/crash-2023-02-25_19.09.30-server.txt)

### Your Divine Journey 2 Discord Username

General#0420

**Comment by WaitingIdly** [comment]
amazing thanks bibliocraft.
going to have to remove chiseling options for probably most bibliocraft blocks then. smh cant have nice things
