### ISSUE TITLE
"Shuffling" of livingrock on nearby runic altars

### ISSUE THREAD

**Issue by osimon8** [Divine-Journey-2/Divine-Journey-2#941]
### Modpack version

2.19.2

### Description

When runic altars are nearby, sometimes the livingrock on top of the altars will sort of shuffle over to nearby altars (up to 2 blocks away from what I've seen). This doesn't always happen, and when there are more than 2 altars I've noticed the livingrock tends to clump up at a particular altar, it doesn't seem totally random. I'm fairly certain this is new behavior in 2.19.2

### Steps to reproduce

1. Get into game
2. Place two runic altars within a few blocks of each other on the same y-level
3. Insert valid recipes into each of them with mechanical users
4. Watch the livingrock shuffle from one altar to another

It's possible you may need to actually set up spreaders into the altars, and you may need more than two altars to see the bug - I haven't tested it out all that thoroughly but the bug is definitely present in my setups and others have reported it as well.

### Expected behavior

The livingrock should stay on the altar it was put into

### Additional context

This post is a good example: https://discord.com/channels/691927762755387402/691927762755387405/1081013191385034842

### Your Divine Journey 2 Discord Username

goodolflip#9466

**Comment by Sleeeper** [comment]
With at least 2 blocks gap between runic altars, shuffling doesn't happen.
Just workaround.
