### ISSUE TITLE
Ch.13,ch.30 wandUnbreakable

### ISSUE THREAD

**Issue by WILSONowo** [Divine-Journey-2/Divine-Journey-2#945]
### Modpack version

2.19.1

### Description

the wandUnbreakable task can't be finished because the request tag is #XXXX/0,but the one you can make is #XXXX/12,and Creative ME Storage Cell needs a wandUnbreakable is also #XXXX/0,it cannot be used to craft Wand of Animation.

### Steps to reproduce

craft a wandUnbreakable to see if the task can be finished.
use the one you crafted to craft Wand of Animation,see if it can be used.

### Expected behavior

maybe change the task request and modify the material of Wand of Animation.

### Your Divine Journey 2 Discord Username

WILSONawa#1099

**Comment by King65868** [comment]
Update to 1.19.2, already been fixed

**Comment by WILSONowo** [comment]
Okay~Thanks~

**Comment by WILSONowo** [comment]
Okay,thanks~
