### ISSUE TITLE
Golden bag of holding wiped all items inside

### ISSUE THREAD

**Issue by Tubby737** [Divine-Journey-2/Divine-Journey-2#951]
### Modpack version

2.19.1

### Description

Not to sure how it happened, really. I was looking to get dirt and decided to go to the twilight forest. I got my shovel out from my bag and went digging. Now at this point I've been to twilight forest many of times before and was able to open the bag and nothing happened. This time when I went for dirt and came back through the portal, all my items in the bag went missing, and I mean like I was able to put cobblestone in slots where there used to be tools/other items and there was nothing there. Now I've tried re-logging in and out, restarting the client, but nothing seems to have fixed the issue. 

Note: I'm not sure if it happened right after coming out of the portal, but I only noticed when I went to go put my shovel away into my bag. 

### Steps to reproduce

Not to sure if it can be reproduced. Since I've been to the twilight forest many times with the bag before and nothing happened. 

### Expected behaviour

N/A

### Additional context

After the incident, I decided to update to the newest version of the pack to 2.19.2 to see if it fixed it, but it didn't. I think I should also mention that I've added a few extra mods to the pack, which hopefully didn't cause the issue.

### Your Divine Journey 2 Discord Username

tubby736#5210

**Comment by WaitingIdly** [comment]
We need reproduction steps for a reason. Without them, I couldnt possibly reproduce this, and as you included extra mods, unless you can give me reproduction without those extra mods (as explicitly requested in the issue template), this isnt an actionable issue - so Im going to close it.
