### ISSUE TITLE
Laser drill don't work in The End

### ISSUE THREAD

**Issue by Dovahkill** [Divine-Journey-2/Divine-Journey-2#961]
### Modpack version

2.19.2

### Description

Laser drill from Industrial Foregoing does not generate ores in The End

### Steps to reproduce

- Go in The End
- Place a laser drill full update at Y 8 for exemple (for iridium with white lens or draconium with purple lens, or without lens)
- Wait 5 minutes
- No ore generate

### Expected behavior

JEI indicate for iridium and draconium the biome The End is best place between Y 5 to Y 68 for iridium and Y 5 to Y 12 for draconium.

### Additional context

![image](https://user-images.githubusercontent.com/32287303/229780714-c4924f4c-2c4e-4686-9df4-76e4289ccdb3.png)
![image](https://user-images.githubusercontent.com/32287303/229780764-3bdaa678-4193-491a-91f2-ca2063c0fc50.png)

### Your Divine Journey 2 Discord Username

NeutronSelector#7225

**Comment by King65868** [comment]
Did you change the Y level in the GUI or did you just place it at Y level 8? You need to change the GUI if you didn’t.

**Comment by Dovahkill** [comment]
Oh sorry, i never saw this option in GUI, my bad. it's work after change the Y level in GUI. I close this issue.
Thank's !
