### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by emmygaming12** [Divine-Journey-2/Divine-Journey-2#965]
### Modpack version

1.12.2

### Description

Was working fine, logged on today and all of my quest progress has erased

### Steps to reproduce

Saved game everytime.
opened modpack and world
opened quests 
all progress gone
(other items/progress fine)

### Expected behavior

Should be on 2nd line/ group of quests (almost finished)

**Comment by WaitingIdly** [comment]
quests can get reset if the server does not shut down properly. there simply isnt anything that can be done about that possibility. there are a few other things that can reset quest progress, such as randomly while playing via LAN.
in this case, the reason for the quests getting reset is completely unknown.
when a backup is made, the backup also saves the quest progress, so copying that over can at least restore the state to near the prior point. 

probably wont help you here, given the date. sorry about that.
