### ISSUE TITLE
Make obtaining a Matter Receiver an optional quest

### ISSUE THREAD

**Issue by Pikaton659** [Divine-Journey-2/Divine-Journey-2#969]
### Describe the request

The Matter Receiver is not needed, so make the quest for obtaining one unnecessary as well.

### Reasons why this should be changed

By this point you can already have other ways to extract yourself from the dimensions that don't cost nearly as much. At this rate, I'm going to be well into ProjectE by the time I can make actual quest progress because the Matter Receiver is absurdly expensive for how completely and utterly optional it is. 

### Your Divine Journey 2 Discord Username

Pikaton#5927

**Comment by King65868** [comment]
You should be able to grab one from one of the rftools dimensions that you make for the quest

**Comment by Pikaton659** [comment]
I tried, it didn't register.
