### ISSUE TITLE
Crashed upon vein-mining Amber in Erebus

### ISSUE THREAD

**Issue by Donaldduck8** [Divine-Journey-2/Divine-Journey-2#981]
### Modpack version

2.19.3

### Java version

jre-8.0.362.9

### RAM Allocated

I dedicated 12GB and have 32GB

### Description

I vein-mined amber in the Erebus dimension and immediately crashed the server.

### When did the crash happen?

I vein-mined amber in the Erebus dimension and immediately crashed the server.

### Steps to reproduce

1. Enter Erebus.
2. Vein-mine amber.
3. The server crashes.

### Minecraft crash report

[crash-2023-05-04_11.16.30-server.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/11399093/crash-2023-05-04_11.16.30-server.txt)

### Additional context

Erebusfix is present on both server and client.

### Your Divine Journey 2 Discord Username

buyerbeware#0728

**Comment by isaacszf** [comment]
Did you manage to solve it? If not, were you able to proceed with the modpack normally?

**Comment by ByThePowerOfScience** [comment]
This should have been fixed in ErebusFix, whose code got merged into UniversalTweaks.  I'll add it to the list if someone can reproduce it.

**Comment by WaitingIdly** [comment]
there has been no update in over a year and could not reproduce this issue.
