### ISSUE TITLE
Unable to drag items from JEI to ME Interface

### ISSUE THREAD

**Issue by Attakajakka** [Divine-Journey-2/Divine-Journey-2#990]
### Modpack version

2.19.3

### Description

Unable to drag items from JEI to ME Interface
When placing the item the item never gets placed but can select in JEI

### Steps to reproduce

Open Game and login
Drag item from JEI to Interface

### Expected behavior

Should populate slot with selected item

### Your Divine Journey 2 Discord Username

Attakajakka#2874

**Comment by King65868** [comment]
Use JEI pins instead

**Comment by Zo1an** [comment]
In the last few days, I've updated my Java installation to Java 8 Update 371 (64-bit) _(Besides updating my graphics card driver as well, but I don't think that should have any effect on this issue)_.
To my surprise today the dragging from JEI worked from all 3 sides.

Could anyone else maybe confirm whether a Java update could solve the dragging issue?
