### ISSUE TITLE
Inventory Desync

### ISSUE THREAD

**Issue by kotkowski** [Divine-Journey-2/Divine-Journey-2#994]
### Modpack version

2.19.2

### Description

Started playing on a server with friend; issue isn't server-specific and occurs to me, but not friend.

After +- 2 minutes, client inventory gets desynchronised from server inventory. It force updates upon opening container (chest/furnace), but creates ghosts items and bugs game otherwise (if you move items in inventory/to and from hotbar/to 2nd hand, they don't actually move server-side, creating some issues)

### Steps to reproduce

1. Join server
2. Play for +- 2 minutes
3. Attempt to craft something in 2x2 crafting/move items in inventory
4. Items aren't moved, ghost versions of items seemingly swapped places, but they didn't actually swap places

### Expected behavior

Default minecraft inventory behaviour (moving pickaxe from inventory to hotbar slot 1 allows you to mine stone with hotbar slot 1 selected etc)

### Your Divine Journey 2 Discord Username

kotkowski#1160

**Comment by KleinGrrmpf** [comment]
This is a known bug, likely related to the Roots Staff Keybind. You just need to relog to fix it.

**Comment by WaitingIdly** [comment]
duplicate of #666, #606, #511, #508, and probably one or two more
